import { INITIAL_AGGREGATE_VERSION,nextAggregateVersion } from "@domain/aggregate";
import type { OrganizationRoleAssignmentEvent,OrganizationRoleEvent } from "@domain/organization/organization-authorization.events";
import { ORGANIZATION_PERMISSIONS } from "@domain/organization/organization-authorization.types";
import type { OrganizationPermission,OrganizationRole,OrganizationRoleAssignment } from "@domain/organization/organization-authorization.types";
import { Result } from "@shared/kernel";import type { DomainError,Id,ISODateString,Result as R } from "@shared/kernel";
type Meta={now:ISODateString;eventId:string};
export function normalizeRoleKey(v:string):string{return v.trim().toLowerCase().replace(/[\s_]+/g,"-").replace(/-+/g,"-");}
export function parsePermissions(values:readonly string[]):R<readonly OrganizationPermission[],DomainError>{if(values.length===0)return Result.fail(err("permissions_required","At least one permission is required."));if(new Set(values).size!==values.length)return Result.fail(err("duplicate_permission","Permissions cannot contain duplicates."));if(!values.every(v=>ORGANIZATION_PERMISSIONS.includes(v as OrganizationPermission)))return Result.fail(err("unknown_permission","Unknown organization permission."));return Result.ok([...values].sort() as OrganizationPermission[]);}
export function parsePermission(value:string):R<OrganizationPermission,DomainError>{return ORGANIZATION_PERMISSIONS.includes(value as OrganizationPermission)?Result.ok(value as OrganizationPermission):Result.fail(err("unknown_permission","Unknown organization permission."));}
export function createOrganizationRole(i:{roleId:Id<"OrganizationRole">;organizationId:Id<"Organization">;name:string;key:string;permissions:readonly string[]}&Meta):R<{role:OrganizationRole;event:OrganizationRoleEvent},DomainError>{const name=i.name.trim().replace(/\s+/g," "),key=normalizeRoleKey(i.key),permissions=parsePermissions(i.permissions);if(!i.roleId.trim()||!i.organizationId.trim())return Result.fail(err("required_id","Role and Organization identifiers are required."));if(!name||name.length>100)return Result.fail(err("invalid_name","Role name must contain 1 to 100 characters."));if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(key)||key.length>64)return Result.fail(err("invalid_key","Role key is invalid."));if(!permissions.ok)return permissions;const role:OrganizationRole={id:i.roleId,organizationId:i.organizationId,name,key,permissions:permissions.value,status:"active",createdAt:i.now,updatedAt:i.now,version:INITIAL_AGGREGATE_VERSION};return Result.ok({role,event:roleEvent("organization.role_created",role,i)});}
export function updateOrganizationRolePermissions(role:OrganizationRole,values:readonly string[],m:Meta):R<{role:OrganizationRole;event:OrganizationRoleEvent},DomainError>{const p=parsePermissions(values);if(!p.ok)return p;if(equal(role.permissions,p.value))return Result.fail(err("no_permission_change","Permission set is unchanged."));return roleTransition({...role,permissions:p.value},"organization.role_permissions_updated",m);}
export function deactivateOrganizationRole(role:OrganizationRole,m:Meta){if(role.status!=="active")return Result.fail(err("role_not_active","Role is not active."));return roleTransition({...role,status:"inactive"},"organization.role_deactivated",m);}
export function reactivateOrganizationRole(role:OrganizationRole,m:Meta){if(role.status!=="inactive")return Result.fail(err("role_not_inactive","Role is not inactive."));return roleTransition({...role,status:"active"},"organization.role_reactivated",m);}
export function createOrganizationRoleAssignment(i:{assignmentId:Id<"OrganizationRoleAssignment">;organizationId:Id<"Organization">;membershipId:Id<"OrganizationMembership">;roleId:Id<"OrganizationRole">}&Meta):R<{assignment:OrganizationRoleAssignment;event:OrganizationRoleAssignmentEvent},DomainError>{if(!i.assignmentId.trim()||!i.organizationId.trim()||!i.membershipId.trim()||!i.roleId.trim())return Result.fail(err("required_id","Assignment identifiers are required."));const assignment:OrganizationRoleAssignment={id:i.assignmentId,organizationId:i.organizationId,membershipId:i.membershipId,roleId:i.roleId,status:"active",createdAt:i.now,updatedAt:i.now,version:INITIAL_AGGREGATE_VERSION};return Result.ok({assignment,event:assignmentEvent("organization.role_assigned",assignment,i)});}
export function deactivateOrganizationRoleAssignment(a:OrganizationRoleAssignment,m:Meta){if(a.status!=="active")return Result.fail(err("assignment_not_active","Assignment is not active."));return assignmentTransition({...a,status:"inactive"},"organization.role_assignment_deactivated",m);}
export function reactivateOrganizationRoleAssignment(a:OrganizationRoleAssignment,m:Meta){if(a.status!=="inactive")return Result.fail(err("assignment_not_inactive","Assignment is not inactive."));return assignmentTransition({...a,status:"active"},"organization.role_assignment_reactivated",m);}
export function isValidOrganizationRole(r:OrganizationRole):boolean{return Boolean(r.id&&r.organizationId&&r.name&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(r.key))&&parsePermissions(r.permissions).ok&&["active","inactive"].includes(r.status)&&valid(r.version,r.createdAt,r.updatedAt);}
export function isValidOrganizationRoleAssignment(a:OrganizationRoleAssignment):boolean{return Boolean(a.id&&a.organizationId&&a.membershipId&&a.roleId)&&["active","inactive"].includes(a.status)&&valid(a.version,a.createdAt,a.updatedAt);}
function roleTransition(base:OrganizationRole,type:OrganizationRoleEvent["type"],m:Meta):R<{role:OrganizationRole;event:OrganizationRoleEvent},DomainError>{const role={...base,updatedAt:m.now,version:nextAggregateVersion(base.version)};return Result.ok({role,event:roleEvent(type,role,m)});}
function assignmentTransition(base:OrganizationRoleAssignment,type:OrganizationRoleAssignmentEvent["type"],m:Meta):R<{assignment:OrganizationRoleAssignment;event:OrganizationRoleAssignmentEvent},DomainError>{const assignment={...base,updatedAt:m.now,version:nextAggregateVersion(base.version)};return Result.ok({assignment,event:assignmentEvent(type,assignment,m)});}
function roleEvent(type:OrganizationRoleEvent["type"],r:OrganizationRole,m:Meta):OrganizationRoleEvent{return {type,eventId:m.eventId,occurredAt:m.now,aggregateId:r.id,aggregateType:"OrganizationRole",organizationId:r.organizationId,roleId:r.id,aggregateVersion:r.version};}
function assignmentEvent(type:OrganizationRoleAssignmentEvent["type"],a:OrganizationRoleAssignment,m:Meta):OrganizationRoleAssignmentEvent{return {type,eventId:m.eventId,occurredAt:m.now,aggregateId:a.id,aggregateType:"OrganizationRoleAssignment",organizationId:a.organizationId,assignmentId:a.id,membershipId:a.membershipId,roleId:a.roleId,aggregateVersion:a.version};}
function equal(a:readonly string[],b:readonly string[]){return a.length===b.length&&[...a].sort().every((v,i)=>v===[...b].sort()[i]);}function valid(v:number,c:string,u:string){return Number.isInteger(v)&&v>0&&!Number.isNaN(Date.parse(c))&&Date.parse(u)>=Date.parse(c);}function err(code:string,message:string):DomainError{return {code,message};}
