import type {TournamentOperationsPhase,TournamentOperationsView,TournamentParticipantView} from "@app/contracts/tournament-operations-reader";
import type React from "react";

export const phasePresentation:Record<TournamentOperationsPhase,{label:string;detail:string;tone:string}>={setup:{label:"Setup",detail:"Competition structure is being prepared.",tone:"quiet"},awaiting_seeding:{label:"Awaiting seeding",detail:"Entrants are ready to be assigned seeds.",tone:"attention"},seeding:{label:"Seeding in progress",detail:"Seed assignments are being finalized.",tone:"attention"},ready:{label:"Ready to compete",detail:"The bracket is prepared for match operations.",tone:"ready"},in_progress:{label:"In progress",detail:"Competition is underway.",tone:"live"},final_pending:{label:"Final pending",detail:"The final result awaits outcome completion.",tone:"attention"},completed:{label:"Completed",detail:"The competition outcome is final.",tone:"complete"}};
export function shortEntry(id:string){const clean=id.replace(/-/g,"");return `Entry •••${clean.slice(-4).toUpperCase()}`;}
const participantLabel=(p:TournamentParticipantView)=>p.sourceSeedNumber?`Seed ${p.sourceSeedNumber}`:shortEntry(p.competitionEntryId);
export function StatusBadge({phase}:{phase:TournamentOperationsPhase}){const p=phasePresentation[phase];return <span className={`status status--${p.tone}`}><i aria-hidden="true"/>{p.label}</span>}
export function EmptyState({title="No tournament selected",children}:{title?:string;children:React.ReactNode}){return <section className="empty-state"><span className="empty-mark" aria-hidden="true">＋</span><h2>{title}</h2><p>{children}</p></section>}
export function LoadingState(){return <section className="loading-state" aria-label="Loading tournament" aria-live="polite"><div className="skeleton skeleton--title"/><div className="skeleton-grid"><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/></div></section>}
export function MessageState({kind,title,children}:{kind:"error"|"forbidden"|"unsupported";title:string;children:React.ReactNode}){return <section className={`message-state message-state--${kind}`} role={kind==="error"?"alert":"status"}><span aria-hidden="true">{kind==="forbidden"?"⊘":"!"}</span><div><h2>{title}</h2><p>{children}</p></div></section>}
function EntryLine({participant,result}:{participant?:TournamentParticipantView;result?:TournamentOperationsView["contests"][number]["result"]}){if(!participant)return <div className="entry-line entry-line--bye"><span>Bye</span><small>No entry assigned</small></div>;const won=result?.winnerCompetitionEntryId===participant.competitionEntryId;const lost=result?.loserCompetitionEntryId===participant.competitionEntryId;return <div className={`entry-line ${won?"is-winner":""} ${lost?"is-loser":""}`}><span>{participantLabel(participant)}</span><small>{participant.sourceSeedNumber?shortEntry(participant.competitionEntryId):participant.sourceOutcome?`Advances as ${participant.sourceOutcome}`:"Competition entry"}</small>{won&&<b>Winner</b>}</div>}
export function Bracket({view}:{view:TournamentOperationsView}){if(view.formatKind!=="single_elimination")return <MessageState kind="unsupported" title="Bracket preview unavailable">This workspace only visualizes supported Single Elimination competitions.</MessageState>;if(!view.stages.length)return <EmptyState title="Bracket not materialized">Stages and matches appear after the competition structure is prepared.</EmptyState>;return <div className="bracket-wrap" tabIndex={0} aria-label="Single Elimination bracket; scroll horizontally to review stages"><div className="bracket">{view.stages.map(stage=><section className="round" key={stage.stageId} aria-labelledby={`stage-${stage.stageId}`}><header><span>Competition stage</span><h3 id={`stage-${stage.stageId}`}>Stage {stage.sequence}</h3><small>{stage.contests.length} {stage.contests.length===1?"match":"matches"}</small></header><div className="round-matches">{stage.contests.map(contest=><article className="match-card" key={contest.contestId}><div className="match-meta"><span>Match {contest.sequence}</span><span>{contest.result?"Final":"Pending"}</span></div><EntryLine participant={contest.participants.find(p=>p.position===1)} result={contest.result}/><EntryLine participant={contest.participants.find(p=>p.position===2)} result={contest.result}/><footer>{contest.progressionState.replaceAll("_"," ")}</footer></article>)}</div></section>)}</div></div>}
export type WorkspaceTab="overview"|"seeding"|"bracket"|"matches"|"results";
export function TournamentWorkspace({view,tab,onTab}:{view:TournamentOperationsView;tab:WorkspaceTab;onTab:(tab:WorkspaceTab)=>void}){const phase=phasePresentation[view.phase];const tabs:WorkspaceTab[]=["overview","seeding","bracket","matches","results"];return <div className="workspace"><header className="workspace-head"><div><p className="eyebrow">Tournament workspace</p><h1>Competition <span>{shortEntry(view.competitionId).slice(-7)}</span></h1><p>Sport-neutral · Single Elimination</p></div><div className="phase-block"><StatusBadge phase={view.phase}/><small>{phase.detail}</small></div></header><nav className="tabs" aria-label="Tournament workspace">{tabs.map(item=><button key={item} className={tab===item?"active":""} aria-current={tab===item?"page":undefined} onClick={()=>onTab(item)}>{item}</button>)}</nav>{tab==="overview"&&<Overview view={view}/>} {tab==="seeding"&&<Seeding view={view}/>} {tab==="bracket"&&<Bracket view={view}/>} {tab==="matches"&&<Matches view={view}/>} {tab==="results"&&<Results view={view}/>}</div>}
function Overview({view}:{view:TournamentOperationsView}){const next=view.contests.find(c=>!c.result);return <div className="overview-grid"><section className="feature-panel"><p className="eyebrow">Operations pulse</p><h2>{phasePresentation[view.phase].label}</h2><p>{phasePresentation[view.phase].detail}</p><div className="progress"><span style={{width:`${view.contests.length?Math.round(view.contests.filter(c=>c.result).length/view.contests.length*100):0}%`}}/></div><small>{view.contests.filter(c=>c.result).length} of {view.contests.length} matches finalized</small></section><section className="stat-stack"><article><span>Entrants</span><b>{view.entrantCount??"—"}</b><small>{view.seeding.assignedCount} seeded</small></article><article><span>Structure</span><b>{view.stages.length}</b><small>stages · {view.contests.length} matches</small></article></section><section className="next-panel"><p className="eyebrow">Next operation</p><h3>{next?`Match ${next.sequence}`:"No pending matches"}</h3><p>{next?`Stage ${view.stages.find(s=>s.stageId===next.stageId)?.sequence??"—"} · ${next.participants.length} entries assigned`:"All materialized matches have finalized results."}</p></section></div>}
function Seeding({view}:{view:TournamentOperationsView}){return <section className="data-panel"><header><div><p className="eyebrow">Entry order</p><h2>Seeding</h2></div><span>{view.seeding.finalized?"Finalized":"Working order"}</span></header>{view.seeding.assignments.length?<ol className="seed-list">{[...view.seeding.assignments].sort((a,b)=>a.seedNumber-b.seedNumber).map(a=><li key={a.competitionEntryId}><b>{a.seedNumber}</b><span>Seed {a.seedNumber}<small>{shortEntry(a.competitionEntryId)}</small></span></li>)}</ol>:<EmptyState title="No seeds assigned">Seed assignments appear here from the authoritative competition view.</EmptyState>}</section>}
function Matches({view}:{view:TournamentOperationsView}){return <section className="data-panel"><header><div><p className="eyebrow">Competition order</p><h2>Matches</h2></div><span>{view.contests.length} total</span></header><div className="match-list">{view.contests.map(c=><article key={c.contestId}><b>Match {c.sequence}</b><span>Stage {view.stages.find(s=>s.stageId===c.stageId)?.sequence}</span><small className="mini-status">{c.result?"Final":"Pending"}</small></article>)}</div></section>}
function Results({view}:{view:TournamentOperationsView}){if(!view.outcome)return <EmptyState title="Outcome not finalized">Final placements appear after competition outcome completion.</EmptyState>;return <section className="results-panel"><p className="eyebrow">Final outcome</p><h2>Official placements</h2><ol>{[...view.outcome.placements].sort((a,b)=>a.position-b.position).map(p=><li key={p.competitionEntryId}><b>{String(p.position).padStart(2,"0")}</b><span>{p.position===1?"Champion":`Place ${p.position}`}<small>{shortEntry(p.competitionEntryId)}</small></span></li>)}</ol></section>}
