import { describe,expect,it } from "vitest";
import { NodeClaimTokenGenerator,VersionedHmacClaimHashKeyProvider,readClaimHashKeyConfig } from "@adapters/auth/node-claim-token-crypto";
import type { ClaimHashKeyVersion,ClaimLookupId } from "@domain/auth/person-claim";
import type { RawClaimSecret,RawClaimToken } from "@app/contracts";
const secret="a-server-key-with-at-least-thirty-two-characters";
describe("versioned claim crypto",()=>{
 it("supports one key and round-trips the credential",()=>{const keys=new VersionedHmacClaimHashKeyProvider({activeVersion:"v1",keys:[{version:"v1",secret}]});const generator=new NodeClaimTokenGenerator();const made=generator.generate(keys.activeVersion());expect(generator.parse(made.credential)).toEqual({version:made.version,lookupId:made.lookupId,secret:made.secret});const hash=keys.hash(made.version,made.lookupId,made.secret);expect(hash.ok&&keys.verify(made.version,made.lookupId,made.secret,hash.hash).matches).toBe(true);});
 it("keeps v1 usable while v2 is active and never falls back",()=>{const keys=new VersionedHmacClaimHashKeyProvider({activeVersion:"v2",keys:[{version:"v1",secret},{version:"v2",secret:secret+"-two"}]});const id="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" as ClaimLookupId,s="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" as RawClaimSecret;const old=keys.hash("v1" as ClaimHashKeyVersion,id,s);expect(keys.activeVersion()).toBe("v2");expect(old.ok&&keys.verify("v1" as ClaimHashKeyVersion,id,s,old.hash).matches).toBe(true);expect(old.ok&&keys.verify("v2" as ClaimHashKeyVersion,id,s,old.hash).matches).toBe(false);expect(keys.verify("missing" as ClaimHashKeyVersion,id,s,old.ok?old.hash:"" as never)).toEqual({ok:false,error:"hash_key_unavailable"});});
 it.each(["bad", "v1.short.secret", "V1.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB", "v1.A!.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"])("rejects malformed credential %s",token=>expect(new NodeClaimTokenGenerator().parse(token as RawClaimToken)).toBeNull());
 it("fails safely for missing, malformed, absent, and duplicate configuration",()=>{expect(()=>readClaimHashKeyConfig({})).toThrow(/missing/);expect(()=>readClaimHashKeyConfig({CLAIM_HASH_ACTIVE_VERSION:"v1",CLAIM_HASH_KEYS:"{"})).toThrow(/malformed/);expect(()=>new VersionedHmacClaimHashKeyProvider({activeVersion:"v2",keys:[{version:"v1",secret}]})).toThrow(/active version/);expect(()=>new VersionedHmacClaimHashKeyProvider({activeVersion:"v1",keys:[{version:"v1",secret},{version:"v1",secret:secret+"x"}]})).toThrow(/duplicate/);});
 it("does not leak secrets in errors",()=>{const distinctive="DISTINCTIVE-SECRET-MATERIAL-123456789";try{new VersionedHmacClaimHashKeyProvider({activeVersion:"v1",keys:[{version:"v1",secret:distinctive.slice(0,3)}]});}catch(error){expect(String(error)).not.toContain(distinctive.slice(0,3));}});
});
