import {describe,expect,it} from "vitest";
import {InMemoryAccountRepository,InMemoryOrganizationMembershipRepository,InMemoryOrganizationRepository,InMemoryPersonRepository} from "@adapters";
import {GetOrganizerContext,selectOrganizerMembership} from "@app/use-cases/get-organizer-context";
import {createAccount} from "@domain/auth/account";
import {createOrganization} from "@domain/organization/organization";
import {createOrganizationMembership} from "@domain/organization/organization-membership";
import {createPerson} from "@domain/identity/person";
import type {AuthSubject} from "@domain/auth/account";
import type {Id,ISODateString} from "@shared/kernel";
const now="2026-09-16T00:00:00.000Z" as ISODateString,id=<T extends string>(value:string)=>value as Id<T>;
async function setup(){const accounts=new InMemoryAccountRepository(),people=new InMemoryPersonRepository(),memberships=new InMemoryOrganizationMembershipRepository(),organizations=new InMemoryOrganizationRepository();const person=createPerson({personId:id<"Person">("person-real"),sportsIdValue:id<"SportsId">("SPORT-REAL"),displayName:"Organizer",now,personCreatedEventId:"e1",sportsIdIssuedEventId:"e2"});if(!person.ok)throw Error();await people.create(person.value.person);const account=createAccount({id:id<"Account">("account-real"),authSubject:id<"AuthSubject">("subject-real"),personId:person.value.person.id,now});if(!account.ok)throw Error();await accounts.create(account.value);for(const [n,name] of [["a","Alpha League"],["b","Bay Sports"]]){const organization=createOrganization({organizationId:id<"Organization">(`org-${n}`),name,slug:`org-${n}`,type:"league",countryCode:"PH",now,eventId:`eo-${n}`});if(!organization.ok)throw Error();await organizations.create(organization.value.organization);const membership=createOrganizationMembership({membershipId:id<"OrganizationMembership">(`membership-${n}`),organizationId:organization.value.organization.id,personId:person.value.person.id,now,eventId:`em-${n}`});if(!membership.ok)throw Error();await memberships.create(membership.value.membership);}return {accounts,people,memberships,organizations};}
describe("GetOrganizerContext",()=>{it("B-C resolves verified subject through Account and Person to active memberships",async()=>{const d=await setup(),useCase=new GetOrganizerContext({authIdentityProvider:{getCurrentIdentity:async()=>({kind:"authenticated",identity:{subject:"subject-real" as AuthSubject}})},accountRepository:d.accounts,personRepository:d.people,membershipRepository:d.memberships,organizationRepository:d.organizations});expect(await useCase.execute()).toMatchObject({ok:true,value:{personId:"person-real",organizations:[{organizationId:"org-a",membershipId:"membership-a"},{organizationId:"org-b",membershipId:"membership-b"}]}});});it("E-H cannot select another Person membership or an outside organization",async()=>{const d=await setup(),useCase=new GetOrganizerContext({authIdentityProvider:{getCurrentIdentity:async()=>({kind:"authenticated",identity:{subject:"subject-real" as AuthSubject}})},accountRepository:d.accounts,personRepository:d.people,membershipRepository:d.memberships,organizationRepository:d.organizations}),result=await useCase.execute();if(!result.ok)throw Error();expect(selectOrganizerMembership(result.value,"org-other")).toMatchObject({ok:false,error:{kind:"forbidden"}});expect(result.value.organizations).not.toContainEqual(expect.objectContaining({membershipId:"membership-other-person"}));});});
