import {describe,expect,it} from "vitest";
import {IssuePersonClaim} from "@app/use-cases/issue-person-claim";
import {NodeClaimTokenGenerator,VersionedHmacClaimHashKeyProvider} from "@adapters/auth/node-claim-token-crypto";
import {InMemoryAccountRepository} from "@adapters/persistence/in-memory-account-repository";import {InMemoryPersonClaimRepository} from "@adapters/persistence/in-memory-person-claim-repository";import {InMemoryPersonRepository} from "@adapters/persistence/in-memory-person-repository";import {FakeClock} from "@adapters/clock/fake-clock";import {FakeIdGenerator} from "@adapters/id/fake-id-generator";
import type {TrustedClaimIssuer} from "@app/contracts";import type {Person} from "@domain/identity/identity.types";import type {AggregateVersion} from "@domain/aggregate";import type {Id,ISODateString} from "@shared/kernel";
const NOW="2026-09-11T00:00:00.000Z" as ISODateString,PID="person-issue" as Id<"Person">,issuer={type:"system",subject:"trusted-onboarding"} as TrustedClaimIssuer;
function person():Person{return{id:PID,version:1 as AggregateVersion,updatedAt:NOW,displayName:"Existing",dateOfBirth:null,lifecycleStatus:"active",sportsId:{value:"SID-I" as Id<"SportsId">,issuedAt:NOW,status:"active"}};}
async function setup(state:"trusted"|"missing"|"untrusted"="trusted"){const people=new InMemoryPersonRepository();await people.create(person());const accounts=new InMemoryAccountRepository(),claims=new InMemoryPersonClaimRepository(accounts),hashKeys=new VersionedHmacClaimHashKeyProvider({activeVersion:"v2",keys:[{version:"v1",secret:"old-key-material-at-least-thirty-two-characters"},{version:"v2",secret:"new-key-material-at-least-thirty-two-characters"}]});const useCase=new IssuePersonClaim({personRepository:people,accountRepository:accounts,personClaimRepository:claims,tokenGenerator:new NodeClaimTokenGenerator(),hashKeys,issuerProvider:{current:()=>state==="trusted"?{kind:"trusted",issuer}:{kind:state}},idGenerator:new FakeIdGenerator("issue"),clock:new FakeClock(NOW),lifetimeMs:3600000});return{useCase,claims};}
describe("IssuePersonClaim trusted issuance",()=>{
 it.each(["missing","untrusted"] as const)("rejects a %s principal",async state=>expect(await(await setup(state)).useCase.execute({personId:PID})).toMatchObject({ok:false,error:{kind:"trusted_issuer_required"}}));
 it("uses the active key, captures audit identity, and never persists the raw secret",async()=>{const state=await setup(),result=await state.useCase.execute({personId:PID});expect(result).toMatchObject({ok:true,value:{claim:{hashKeyVersion:"v2",issuedBy:{type:"system",subject:"trusted-onboarding"}}}});if(result.ok){expect(result.value.rawToken).not.toContain(result.value.claim.tokenHash);expect(JSON.stringify(result.value.claim)).not.toContain(result.value.rawToken.split(".")[2]);expect(await state.claims.findByLookupId(result.value.claim.lookupId)).toMatchObject({kind:"found"});}});
 it("revokes the prior pending claim on reissue",async()=>{const state=await setup(),first=await state.useCase.execute({personId:PID});await state.useCase.execute({personId:PID});if(first.ok)expect(await state.claims.findByLookupId(first.value.claim.lookupId)).toMatchObject({kind:"found",claim:{status:"revoked",version:2}});});
});
