import {describe,expect,it} from "vitest";import {LinkAuthenticatedAccountToExistingPerson} from "@app/use-cases/link-authenticated-account-to-existing-person";import {NodeClaimTokenGenerator,VersionedHmacClaimHashKeyProvider} from "@adapters/auth/node-claim-token-crypto";import {InMemoryAccountRepository} from "@adapters/persistence/in-memory-account-repository";import {InMemoryPersonClaimRepository} from "@adapters/persistence/in-memory-person-claim-repository";import {InMemoryPersonRepository} from "@adapters/persistence/in-memory-person-repository";import {FakeClock} from "@adapters/clock/fake-clock";import {FakeIdGenerator} from "@adapters/id/fake-id-generator";import {createPersonClaim,revokePersonClaim} from "@domain/auth/person-claim";import type {AuthIdentityProvider,RawClaimToken} from "@app/contracts";import type {AuthSubject} from "@domain/auth/account";import type {Person} from "@domain/identity/identity.types";import type {AggregateVersion} from "@domain/aggregate";import type {Id,ISODateString} from "@shared/kernel";
const NOW="2026-09-11T00:00:00.000Z" as ISODateString,PERSON="person-owner" as Id<"Person">,generator=new NodeClaimTokenGenerator(),oldSecret="old-key-material-at-least-thirty-two-characters",newSecret="new-key-material-at-least-thirty-two-characters";const auth:AuthIdentityProvider={getCurrentIdentity:async()=>({kind:"authenticated",identity:{subject:"subject-1" as AuthSubject}})};
function person():Person{return{id:PERSON,version:1 as AggregateVersion,updatedAt:NOW,displayName:"Owner",dateOfBirth:null,lifecycleStatus:"active",sportsId:{value:"SID-X" as Id<"SportsId">,issuedAt:NOW,status:"active"}};}
async function setup(options:{version?:"v1"|"v2";expiresAt?:string;keys?:{version:string;secret:string}[];provider?:AuthIdentityProvider}={}){const version=options.version??"v1",keys=new VersionedHmacClaimHashKeyProvider({activeVersion:"v2",keys:options.keys??[{version:"v1",secret:oldSecret},{version:"v2",secret:newSecret}]});const madeToken=generator.generate(version as never),hashed=keys.hash(madeToken.version,madeToken.lookupId,madeToken.secret);if(!hashed.ok)throw new Error();const made=createPersonClaim({id:"claim-1" as Id<"PersonClaim">,personId:PERSON,tokenHash:hashed.hash,lookupId:madeToken.lookupId,hashKeyVersion:madeToken.version,issuedBy:{type:"system",subject:"seed"},now:NOW,expiresAt:(options.expiresAt??"2026-09-12T00:00:00.000Z") as ISODateString});if(!made.ok)throw new Error();const people=new InMemoryPersonRepository();await people.create(person());const accounts=new InMemoryAccountRepository(),claims=new InMemoryPersonClaimRepository(accounts);await claims.issueReplacingPending(made.value);const clock=new FakeClock(NOW),useCase=new LinkAuthenticatedAccountToExistingPerson({authIdentityProvider:options.provider??auth,tokenGenerator:generator,hashKeys:keys,personClaimRepository:claims,claimAccountLinkRepository:claims,accountRepository:accounts,personRepository:people,idGenerator:new FakeIdGenerator("link"),clock});return{useCase,claims,claim:made.value,token:madeToken.credential,clock};}
describe("claim-authorized Account linkage",()=>{
 it("verifies a v1 claim while v2 is active",async()=>{const s=await setup();expect(await s.useCase.execute({rawClaimToken:s.token})).toMatchObject({ok:true});});
 it("links, consumes, and rejects replay",async()=>{const s=await setup();expect(await s.useCase.execute({rawClaimToken:s.token})).toMatchObject({ok:true,value:{account:{personId:PERSON}}});expect(await s.useCase.execute({rawClaimToken:s.token})).toMatchObject({ok:false,error:{kind:"consumed_claim"}});});
 it("rejects malformed and invalid secrets",async()=>{const s=await setup();expect(await s.useCase.execute({rawClaimToken:"bad" as RawClaimToken})).toMatchObject({ok:false,error:{kind:"invalid_claim"}});const [v,l]=s.token.split(".");expect(await s.useCase.execute({rawClaimToken:`${v}.${l}.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB` as RawClaimToken})).toMatchObject({ok:false,error:{kind:"invalid_claim"}});});
 it("fails safely when the historical key is unavailable",async()=>{const seeded=await setup(),keys=new VersionedHmacClaimHashKeyProvider({activeVersion:"v2",keys:[{version:"v2",secret:newSecret}]});const useCase=new LinkAuthenticatedAccountToExistingPerson({...((seeded.useCase as unknown as {deps:object}).deps),hashKeys:keys} as never);expect(await useCase.execute({rawClaimToken:seeded.token})).toMatchObject({ok:false,error:{kind:"hash_key_unavailable"}});});
 it("preserves expiration and revocation",async()=>{const expired=await setup({expiresAt:"2026-09-11T00:00:01.000Z"});expired.clock.advance(1001);expect(await expired.useCase.execute({rawClaimToken:expired.token})).toMatchObject({ok:false,error:{kind:"expired_claim"}});const revoked=await setup(),r=revokePersonClaim(revoked.claim,NOW);if(!r.ok)throw new Error();await revoked.claims.issueReplacingPending({...revoked.claim,id:"replacement" as Id<"PersonClaim">,lookupId:"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" as never,tokenHash:"different" as never},{revokedClaim:r.value,expectedVersion:revoked.claim.version});expect(await revoked.useCase.execute({rawClaimToken:revoked.token})).toMatchObject({ok:false,error:{kind:"revoked_claim"}});});
 it("allows only one concurrent consumer",async()=>{const s=await setup(),results=await Promise.all([s.useCase.execute({rawClaimToken:s.token}),s.useCase.execute({rawClaimToken:s.token})]);expect(results.filter(x=>x.ok)).toHaveLength(1);});
});
