/* global Request */
import {describe,expect,it,vi} from "vitest";
import {createOrganizerContextHandler} from "@adapters/http/organizer-context-handler";
import {createTournamentOperationsHandler} from "@adapters/http/tournament-operations-handler";

const request=(path:string,authorization=true)=>new Request(`https://example.test${path}`,{headers:authorization?{Authorization:"Bearer verified-token"}:{}});
describe("authenticated organizer HTTP boundaries",()=>{
 it("A rejects unauthenticated organizer and tournament requests",async()=>{const factory=vi.fn();expect((await createOrganizerContextHandler(factory)(request("/context",false))).status).toBe(401);expect((await createTournamentOperationsHandler(factory)(request("/ops?competitionFormatId=f&organizationId=o",false))).status).toBe(401);expect(factory).not.toHaveBeenCalled();});
 it("returns only the provider-neutral OrganizerContext",async()=>{const close=vi.fn(async()=>{}),handler=createOrganizerContextHandler(()=>({close,organizerContext:{execute:vi.fn(async()=>({ok:true,value:{personId:"person-1",organizations:[{organizationId:"org-1",membershipId:"membership-real",organizationName:"Harbor League"}]}}))} as never}));const response=await handler(request("/context?accountId=fake&providerId=fake")),text=await response.text();expect(response.status).toBe(200);expect(JSON.parse(text)).toEqual({personId:"person-1",organizations:[{organizationId:"org-1",membershipId:"membership-real",organizationName:"Harbor League"}]});expect(text).not.toMatch(/token|session|provider|authSubject|accountId/i);expect(close).toHaveBeenCalledOnce();});
 it("F-G ignores browser identity and carries projected entrant identity",async()=>{const entrants=[{competitionEntryId:"entry-1",entrantType:"team",identityStatus:"resolved",displayName:"Harbor Lions"}],execute=vi.fn(async()=>({ok:true,value:{view:{competitionFormatId:"format-real",entrants}}})),handler=createTournamentOperationsHandler(()=>({close:async()=>{},tournamentOperations:{execute} as never}));const response=await handler(request("/ops?competitionFormatId=format-real&organizationId=org-real&actingMembershipId=membership-fake&personId=person-fake&accountId=account-fake&providerId=provider-fake"));expect(response.status).toBe(200);expect(await response.json()).toEqual({competitionFormatId:"format-real",entrants});expect(execute).toHaveBeenCalledWith({competitionFormatId:"format-real",organizationId:"org-real"});expect(execute.mock.calls[0]?.[0]).not.toHaveProperty("actingMembershipId");});
});
