/* global Request,Response */
import type {RetryOrganizerMatchProgression} from "@app/use-cases/retry-organizer-match-progression";
import type {FinalizeOrganizerCompetitionOutcome} from "@app/use-cases/finalize-organizer-competition-outcome";
const BEARER=/^Bearer [^\s]{1,4096}$/;
type Runtime={readonly retryProgression:RetryOrganizerMatchProgression;readonly finalizeOutcome:FinalizeOrganizerCompetitionOutcome;close():Promise<void>};
export function createRetryOrganizerProgressionHandler(create:(authorization:string)=>Runtime){return command(create,"retryProgression",["organizationId","contestResultId"]);}
export function createFinalizeOrganizerOutcomeHandler(create:(authorization:string)=>Runtime){return command(create,"finalizeOutcome",["organizationId","competitionFormatId"]);}
function command(create:(authorization:string)=>Runtime,operation:"retryProgression"|"finalizeOutcome",keys:readonly string[]){return async(request:Request):Promise<Response>=>{
 if(request.method!=="POST")return json(405,{message:"Only POST is allowed."},{Allow:"POST"});const authorization=request.headers.get("authorization");if(!authorization||!BEARER.test(authorization))return json(401,{message:"Authentication is required."});let body:unknown;try{body=await request.json();}catch{return json(400,{message:"Invalid operation request."});}if(!shape(body,keys))return json(400,{message:"Invalid operation request."});let runtime:Runtime|undefined;try{runtime=create(authorization);const result=await runtime[operation].execute(body as never);if(result.ok)return json(200,result.value);const kind=result.error.kind,status=kind==="unauthenticated"?401:kind==="forbidden"?403:kind==="competition_outcome_already_finalized"?409:kind==="persistence_unavailable"||kind==="identity_provider_unavailable"?503:422;return json(status,{message:status===401?"Authentication is required.":status===403?"Operation is not permitted.":status===409?"The competition outcome is already final.":status===503?"Operation is temporarily unavailable.":"Operation cannot be completed."});}catch{return json(503,{message:"Operation is temporarily unavailable."});}finally{if(runtime)try{await runtime.close();}catch{/* secret-free response */}}
};}
function shape(x:unknown,keys:readonly string[]):x is Record<string,string>{if(!x||typeof x!=="object"||Array.isArray(x))return false;const r=x as Record<string,unknown>,actual=Object.keys(r);return actual.length===keys.length&&actual.every(k=>keys.includes(k))&&keys.every(k=>typeof r[k]==="string"&&!!(r[k] as string).trim());}
function json(status:number,body:unknown,extra:Record<string,string>={}):Response{return Response.json(body,{status,headers:{"Cache-Control":"private, no-store","Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff",...extra}});}
