import type {CompetitionOutcomeFinalizer,CompetitionOutcomeRepository,CompetitionOutcomeLookup} from "@app/contracts";
import {competitionPlacement,finalizedCompetitionOutcome} from "@domain/competition/competition-outcome";
import type {Id} from "@shared/kernel";
export class InMemoryCompetitionOutcomeFinalizer implements CompetitionOutcomeFinalizer,CompetitionOutcomeRepository{
 readonly outcomes=new Map<string,{outcome:ReturnType<typeof finalizedCompetitionOutcome>;placements:ReturnType<typeof competitionPlacement>[]}>();
 readonly terminalAuthority=new Map<string,{competitionId:string;planRef:string;entrantCount:number;resultId:Id<"ContestResult">;winnerEntryId:Id<"CompetitionEntry">;loserEntryId:Id<"CompetitionEntry">;completed:boolean;finalized:boolean;progressionParticipantCount:number|null}>();
 async findByFormatId(id:Id<"CompetitionFormat">):Promise<CompetitionOutcomeLookup>{const x=this.outcomes.get(id);return x?{kind:"found",...x}:{kind:"not_found"};}
 async finalize(i:Parameters<CompetitionOutcomeFinalizer["finalize"]>[0]){if(this.outcomes.has(i.competitionFormatId))return{ok:false as const,error:{kind:"competition_outcome_already_finalized" as const}};const a=this.terminalAuthority.get(i.competitionFormatId);if(!a||a.planRef!==i.terminalPlanRef)return{ok:false as const,error:{kind:"terminal_contest_not_found" as const}};if(a.competitionId!==i.competitionId||a.entrantCount!==i.expectedEntrantCount)return{ok:false as const,error:{kind:"cross_format_authority" as const}};if(!a.completed||!a.finalized)return{ok:false as const,error:{kind:"terminal_result_not_finalized" as const}};if(a.progressionParticipantCount===null)return{ok:false as const,error:{kind:"terminal_result_not_progressed" as const}};if(a.progressionParticipantCount!==0)return{ok:false as const,error:{kind:"invalid_terminal_progression" as const}};if(a.winnerEntryId===a.loserEntryId)return{ok:false as const,error:{kind:"malformed_terminal_result" as const}};const outcome=finalizedCompetitionOutcome({id:i.outcomeId,competitionFormatId:i.competitionFormatId,now:i.finalizedAt}),placements=[competitionPlacement({id:i.firstPlacementId,competitionOutcomeId:i.outcomeId,competitionEntryId:a.winnerEntryId,position:1,sourceContestResultId:a.resultId,now:i.finalizedAt}),competitionPlacement({id:i.secondPlacementId,competitionOutcomeId:i.outcomeId,competitionEntryId:a.loserEntryId,position:2,sourceContestResultId:a.resultId,now:i.finalizedAt})];this.outcomes.set(i.competitionFormatId,{outcome,placements});return{ok:true as const,value:{outcome,placements}};
 }
}
