import { describe,expect,it } from "vitest";
import { createTeam,deactivateTeam,reactivateTeam } from "@domain/team/team";
import { InMemoryTeamRepository } from "@adapters/persistence/in-memory-team-repository";
import type { Id,ISODateString } from "@shared/kernel";
const now="2026-09-16T10:00:00.000Z" as ISODateString,later="2026-09-16T11:00:00.000Z" as ISODateString;
const id=(v:string)=>v as Id<"Team">,org=(v:string)=>v as Id<"Organization">,sport=(v:string)=>v as Id<"Sport">;
function make(overrides:Partial<Parameters<typeof createTeam>[0]>={}){return createTeam({teamId:id("team-1"),organizationId:org("org-1"),sportId:sport("basketball"),name:"  Bacolod   Eagles  ",key:" Bacolod_Eagles ",now,eventId:"event-1",...overrides});}
describe("Team aggregate",()=>{it("creates normalized active identity and a non-PII event",()=>{const r=make();expect(r.ok).toBe(true);if(!r.ok)return;expect(r.value.team).toMatchObject({name:"Bacolod Eagles",key:"bacolod-eagles",status:"active",version:1,createdAt:now,updatedAt:now});expect(r.value.event).toMatchObject({type:"team.team_created",teamId:"team-1",organizationId:"org-1",sportId:"basketball",version:1});expect(r.value.event).not.toHaveProperty("name");});it.each([["", "invalid_name"],["x".repeat(121),"invalid_name"]])("rejects bad name",(name,code)=>{const r=make({name});expect(r.ok?null:r.error.code).toBe(code);});it.each([["hello/world","invalid_key"],["éagles","invalid_key"],["x".repeat(65),"invalid_key"]])("rejects bad key",(key,code)=>{const r=make({key});expect(r.ok?null:r.error.code).toBe(code);});it("owns lifecycle and increments versions",()=>{const made=make();if(!made.ok)throw new Error();const off=deactivateTeam(made.value.team,{now:later,eventId:"event-2"});expect(off.ok).toBe(true);if(!off.ok)return;expect(off.value.team).toMatchObject({status:"inactive",version:2,updatedAt:later});expect(deactivateTeam(off.value.team,{now:later,eventId:"x"})).toMatchObject({ok:false,error:{code:"team_not_active"}});const on=reactivateTeam(off.value.team,{now:later,eventId:"event-3"});expect(on.ok).toBe(true);if(on.ok)expect(on.value.team).toMatchObject({status:"active",version:3});});});
describe("InMemoryTeamRepository",()=>{it("scopes key uniqueness to Organization and enforces optimistic saves",async()=>{const repo=new InMemoryTeamRepository(),a=make();if(!a.ok)throw new Error();expect((await repo.create(a.value.team)).ok).toBe(true);const duplicate=make({teamId:id("team-2")});expect(duplicate.ok&&await repo.create(duplicate.value.team)).toMatchObject({ok:false,error:{kind:"duplicate_team_key"}});const other=make({teamId:id("team-3"),organizationId:org("org-2")});expect(other.ok&&await repo.create(other.value.team)).toMatchObject({ok:true});expect(await repo.findByOrganizationAndKey(org("org-2"),"bacolod-eagles")).toMatchObject({kind:"found",team:{id:"team-3"}});const off=deactivateTeam(a.value.team,{now:later,eventId:"e"});if(!off.ok)throw new Error();expect(await repo.save(off.value.team,1)).toMatchObject({ok:true,value:{version:2}});expect(await repo.save(off.value.team,1)).toMatchObject({ok:false,error:{kind:"concurrency_conflict"}});});});
