/* global Request, Response */
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import postgres from "postgres";
import type {Sql} from "@adapters/persistence/pg/connection";
import {PgPersonRepository} from "@adapters/persistence/pg/pg-person-repository";
import {PgAccountRepository} from "@adapters/persistence/pg/pg-account-repository";
import {PgPersonClaimRepository} from "@adapters/persistence/pg/pg-person-claim-repository";
import {NodeClaimTokenGenerator,VersionedHmacClaimHashKeyProvider} from "@adapters/auth/node-claim-token-crypto";
import {createAccountLinkPersonHandler} from "@adapters/http/account-link-person-handler";
import {LinkAuthenticatedAccountToExistingPerson} from "@app/use-cases/link-authenticated-account-to-existing-person";
import {FakeClock} from "@adapters/clock/fake-clock";import {FakeIdGenerator} from "@adapters/id/fake-id-generator";
import {createPersonClaim} from "@domain/auth/person-claim";import type {AuthSubject} from "@domain/auth/account";import type {Id,ISODateString} from "@shared/kernel";
const URL=process.env.TEST_DATABASE_URL??"",RUN=URL.trim()!=="",PREFIX=`server_it_${Date.now()}`,NOW="2026-09-11T00:00:00.000Z" as ISODateString,PERSON=`${PREFIX}_person` as Id<"Person">,SUBJECT=`${PREFIX}_subject` as AuthSubject;
describe.skipIf(!RUN)("account-link server adapter with PostgreSQL",()=>{
 let sql:Sql,claims:PgPersonClaimRepository,accounts:PgAccountRepository,credential:string,handle:(request:Request)=>Promise<Response>;
 beforeAll(async()=>{sql=postgres(URL,{ssl:"require",max:4,onnotice:()=>{}}) as Sql;const people=new PgPersonRepository(sql);accounts=new PgAccountRepository(sql);claims=new PgPersonClaimRepository(sql);await sql`INSERT INTO persons(id,display_name,lifecycle_status,version,updated_at) VALUES(${PERSON},'Server Adapter Person','active',1,${NOW})`;await sql`INSERT INTO sports_ids(value,person_id,issued_at,status) VALUES(${`${PREFIX}_sports_id`},${PERSON},${NOW},'active')`;const keys=new VersionedHmacClaimHashKeyProvider({activeVersion:"v2",keys:[{version:"v2",secret:"server-adapter-test-key-at-least-thirty-two"}]}),generator=new NodeClaimTokenGenerator(),token=generator.generate(keys.activeVersion()),hash=keys.hash(token.version,token.lookupId,token.secret);if(!hash.ok)throw new Error();const made=createPersonClaim({id:`${PREFIX}_claim` as Id<"PersonClaim">,personId:PERSON,tokenHash:hash.hash,lookupId:token.lookupId,hashKeyVersion:token.version,issuedBy:{type:"system",subject:"integration"},now:NOW,expiresAt:"2026-09-12T00:00:00.000Z" as ISODateString});if(!made.ok)throw new Error();await claims.issueReplacingPending(made.value);credential=token.credential;handle=createAccountLinkPersonHandler(()=>({close:async()=>{},linkPerson:new LinkAuthenticatedAccountToExistingPerson({authIdentityProvider:{getCurrentIdentity:async()=>({kind:"authenticated",identity:{subject:SUBJECT}})},tokenGenerator:generator,hashKeys:keys,personClaimRepository:claims,claimAccountLinkRepository:claims,accountRepository:accounts,personRepository:people,idGenerator:new FakeIdGenerator(PREFIX),clock:new FakeClock(NOW)})}));});
 afterAll(async()=>{await sql`DELETE FROM accounts WHERE person_id=${PERSON}`;await sql`DELETE FROM person_claims WHERE person_id=${PERSON}`;await sql`DELETE FROM sports_ids WHERE person_id=${PERSON}`;await sql`DELETE FROM persons WHERE id=${PERSON}`;await sql.end({timeout:5});});
 const request=(body:unknown)=>new Request("https://example.test/account/link-person",{method:"POST",headers:{Authorization:"Bearer validated-by-stub","Content-Type":"application/json"},body:JSON.stringify(body)});
 it("links the claim-derived Person atomically and rejects replay",async()=>{const first=await handle(request({claimCredential:credential}));expect(first.status).toBe(200);expect(await accounts.findByAuthSubject(SUBJECT)).toMatchObject({kind:"found",account:{personId:PERSON}});const parsed=new NodeClaimTokenGenerator().parse(credential as never);if(parsed===null)throw new Error();expect(await claims.findByLookupId(parsed.lookupId)).toMatchObject({kind:"found",claim:{status:"consumed"}});expect((await handle(request({claimCredential:credential}))).status).toBe(409);});
 it("rejects a caller-supplied Person ID before application execution",async()=>expect((await handle(request({claimCredential:credential,personId:"attacker"}))).status).toBe(400));
});
