/* global Request */
import postgres from "postgres";
import {afterAll,beforeAll,describe,expect,it,vi} from "vitest";
import type {Sql} from "@adapters";
import {FakeClock,InMemoryEventPublisher,PgAccountRepository,PgCompetitionFormatRepository,PgCompetitionRepository,PgCompetitionStructureMaterializer,PgContestParticipantRepository,PgContestRepository,PgContestResultProgressor,PgContestResultRepository,PgDivisionRepository,PgEventRepository,PgOrganizationMembershipRepository,PgOrganizationRepository,PgOrganizationRoleAssignmentRepository,PgOrganizationRoleRepository,PgPersonRepository,PgStageRepository,PgTournamentOperationsReader,UuidIdGenerator} from "@adapters";
import {GetOrganizerContext} from "@app/use-cases/get-organizer-context";
import {GetAuthenticatedTournamentOperationsView} from "@app/use-cases/get-authenticated-tournament-operations-view";
import {GetTournamentOperationsView} from "@app/use-cases/get-tournament-operations-view";
import {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import type {AuthSubject} from "@domain/auth/account";
import {randomUUID} from "node:crypto";
import {RecordContestResult} from "@app/use-cases/record-contest-result";
import {ProgressFinalizedContestResult} from "@app/use-cases/progress-finalized-contest-result";
import {FinalizeOrganizerMatchResult} from "@app/use-cases/finalize-organizer-match-result";
import {createFinalizeOrganizerMatchHandler} from "@adapters/http/finalize-organizer-match-handler";
import {createCompetitionFormatEngineRegistry} from "@composition/competition-format-engines";

const URL=process.env.TEST_DATABASE_URL??"",RUN=URL.length>0,P=`auth-org-${Date.now()}-${Math.floor(Math.random()*1e6)}`,x=(name:string)=>`${P}-${name}`,NOW="2026-09-16T00:00:00.000Z";
const PARTICIPANT_1=randomUUID(),PARTICIPANT_2=randomUUID();
vi.setConfig({testTimeout:120_000,hookTimeout:120_000});
describe.skipIf(!RUN)("PostgreSQL authenticated Organizer Context",()=>{
 let sql:Sql,context:GetOrganizerContext,operations:GetAuthenticatedTournamentOperationsView;
 beforeAll(async()=>{
  sql=postgres(URL,{ssl:"require",max:5,onnotice:()=>{}}) as Sql;
  await sql`INSERT INTO persons(id,display_name,lifecycle_status,created_at,updated_at,version) VALUES(${x("person")},'Verified Organizer','active',${NOW},${NOW},1),(${x("outsider-person")},'Outsider','active',${NOW},${NOW},1)`;
  await sql`INSERT INTO sports_ids(value,person_id,issued_at,status) VALUES(${x("sports-id")},${x("person")},${NOW},'active'),(${x("outsider-sports-id")},${x("outsider-person")},${NOW},'active')`;
  await sql`INSERT INTO accounts(id,auth_subject,person_id,status,version,created_at,updated_at) VALUES(${x("account")},${x("subject")},${x("person")},'active',1,${NOW},${NOW}),(${x("outsider-account")},${x("outsider-subject")},${x("outsider-person")},'active',1,${NOW},${NOW})`;
  await sql`INSERT INTO organizations(id,name,slug,type,status,country_code,version,created_at,updated_at) VALUES(${x("org-a")},'Alpha Athletics',${x("org-a")},'league','active','PH',1,${NOW},${NOW}),(${x("org-b")},'Bay League',${x("org-b")},'league','active','PH',1,${NOW},${NOW}),(${x("org-inactive-member")},'Closed Membership',${x("org-inactive-member")},'league','active','PH',1,${NOW},${NOW}),(${x("org-outsider")},'Outsider League',${x("org-outsider")},'league','active','PH',1,${NOW},${NOW})`;
  await sql`INSERT INTO organization_memberships(id,organization_id,person_id,status,version,created_at,updated_at) VALUES(${x("member-a")},${x("org-a")},${x("person")},'active',1,${NOW},${NOW}),(${x("member-b")},${x("org-b")},${x("person")},'active',1,${NOW},${NOW}),(${x("member-inactive")},${x("org-inactive-member")},${x("person")},'inactive',1,${NOW},${NOW}),(${x("member-outsider")},${x("org-outsider")},${x("outsider-person")},'active',1,${NOW},${NOW})`;
  for(const n of ["a","b"]){
   await sql`INSERT INTO organization_roles(id,organization_id,name,key,permissions,status,version,created_at,updated_at) VALUES(${x(`role-${n}`)},${x(`org-${n}`)},'Event Operator',${x(`role-${n}`)},ARRAY['organization.events.read','organization.events.manage'],'active',1,${NOW},${NOW})`;
   await sql`INSERT INTO organization_role_assignments(id,organization_id,membership_id,role_id,status,version,created_at,updated_at) VALUES(${x(`assignment-${n}`)},${x(`org-${n}`)},${x(`member-${n}`)},${x(`role-${n}`)},'active',1,${NOW},${NOW})`;
   await sql`INSERT INTO events(id,organization_id,name,key,status,created_at,updated_at,version) VALUES(${x(`event-${n}`)},${x(`org-${n}`)},${`Event ${n}`},${x(`event-${n}`)},'active',${NOW},${NOW},1)`;
   await sql`INSERT INTO competitions(id,event_id,sport_id,name,key,status,created_at,updated_at,version) VALUES(${x(`competition-${n}`)},${x(`event-${n}`)},'sport-basketball',${`Competition ${n}`},${x(`competition-${n}`)},'active',${NOW},${NOW},1)`;
   await sql`INSERT INTO competition_formats(id,competition_id,kind,status,created_at,updated_at,version) VALUES(${x(`format-${n}`)},${x(`competition-${n}`)},'single_elimination','active',${NOW},${NOW},1)`;
  }
  await sql`INSERT INTO teams(id,organization_id,sport_id,name,key,status,created_at,updated_at,version) VALUES(${x("team-1")},${x("org-a")},'sport-basketball','Alpha One',${x("team-1")},'active',${NOW},${NOW},1),(${x("team-2")},${x("org-a")},'sport-basketball','Alpha Two',${x("team-2")},'active',${NOW},${NOW},1)`;
  await sql`INSERT INTO competition_entries(id,competition_id,entrant_type,team_id,status,created_at,updated_at,version) VALUES(${x("entry-1")},${x("competition-a")},'team',${x("team-1")},'active',${NOW},${NOW},1),(${x("entry-2")},${x("competition-a")},'team',${x("team-2")},'active',${NOW},${NOW},1)`;
  await sql`INSERT INTO competition_format_materializations(competition_format_id,entrant_count,created_at,seed_finalized_at,participants_materialized_at) VALUES(${x("format-a")},2,${NOW},${NOW},${NOW})`;
  await sql`INSERT INTO competition_stages(id,competition_id,competition_format_id,name,key,sequence,status,created_at,updated_at,version) VALUES(${x("stage-final")},${x("competition-a")},${x("format-a")},'Final','final',1,'active',${NOW},${NOW},1)`;
  await sql`INSERT INTO contests(id,stage_id,plan_ref,sequence,status,created_at,updated_at,version) VALUES(${x("contest-final")},${x("stage-final")},'contest:final',1,'completed',${NOW},${NOW},1)`;
  await sql`INSERT INTO contest_participants(id,contest_id,position,competition_entry_id,source_type,source_seed_number,version,created_at) VALUES(${PARTICIPANT_1},${x("contest-final")},1,${x("entry-1")},'seed',1,1,${NOW}),(${PARTICIPANT_2},${x("contest-final")},2,${x("entry-2")},'seed',2,1,${NOW})`;
  const memberships=new PgOrganizationMembershipRepository(sql),auth={getCurrentIdentity:async()=>({kind:"authenticated" as const,identity:{subject:x("subject") as AuthSubject}})};
  context=new GetOrganizerContext({authIdentityProvider:auth,accountRepository:new PgAccountRepository(sql),personRepository:new PgPersonRepository(sql),membershipRepository:memberships,organizationRepository:new PgOrganizationRepository(sql)});
  const authorization=new AuthorizeOrganizationPermission({membershipRepository:memberships,roleRepository:new PgOrganizationRoleRepository(sql),assignmentRepository:new PgOrganizationRoleAssignmentRepository(sql)});
  operations=new GetAuthenticatedTournamentOperationsView({organizerContext:context,tournamentOperations:new GetTournamentOperationsView({reader:new PgTournamentOperationsReader(sql),authorization})});
 });
 afterAll(async()=>{await sql`DELETE FROM contest_result_progressions WHERE contest_result_id IN (SELECT id FROM contest_results WHERE contest_id LIKE ${`${P}%`})`;await sql`DELETE FROM contest_result_outcomes WHERE contest_result_id IN (SELECT id FROM contest_results WHERE contest_id LIKE ${`${P}%`})`;await sql`DELETE FROM contest_results WHERE contest_id LIKE ${`${P}%`}`;await sql`DELETE FROM contest_participants WHERE contest_id LIKE ${`${P}%`}`;for(const table of ["contests","competition_stages","competition_entries","teams"])await sql.unsafe(`DELETE FROM ${table} WHERE id LIKE $1`,[`${P}%`]);await sql`DELETE FROM competition_format_materializations WHERE competition_format_id LIKE ${`${P}%`}`;for(const table of ["competition_formats","competitions","events","organization_role_assignments","organization_roles","organization_memberships","accounts","organizations"])await sql.unsafe(`DELETE FROM ${table} WHERE id LIKE $1`,[`${P}%`]);await sql`DELETE FROM sports_ids WHERE person_id LIKE ${`${P}%`}`;await sql`DELETE FROM persons WHERE id LIKE ${`${P}%`}`;await sql.end({timeout:5});});
 it("B-D resolves Account to Person and excludes inactive membership",async()=>expect(await context.execute()).toEqual({ok:true,value:{personId:x("person"),organizations:[{organizationId:x("org-a"),membershipId:x("member-a"),organizationName:"Alpha Athletics"},{organizationId:x("org-b"),membershipId:x("member-b"),organizationName:"Bay League"}]}}));
 it("I allows either active organization and K rejects a tournament owned by the other",async()=>{expect(await operations.execute({organizationId:x("org-a"),competitionFormatId:x("format-a")})).toMatchObject({ok:true});expect(await operations.execute({organizationId:x("org-b"),competitionFormatId:x("format-b")})).toMatchObject({ok:true});expect(await operations.execute({organizationId:x("org-a"),competitionFormatId:x("format-b")})).toMatchObject({ok:false,error:{kind:"forbidden"}});});
 it("E,H cannot select another Person's membership or organization",async()=>{expect(await operations.execute({organizationId:x("org-outsider"),competitionFormatId:x("format-a")})).toMatchObject({ok:false,error:{kind:"forbidden"}});expect(JSON.stringify(await context.execute())).not.toContain(x("member-outsider"));});
 it("crosses the authenticated HTTP boundary into real PostgreSQL result and terminal progression",async()=>{const authorization=new AuthorizeOrganizationPermission({membershipRepository:new PgOrganizationMembershipRepository(sql),roleRepository:new PgOrganizationRoleRepository(sql),assignmentRepository:new PgOrganizationRoleAssignmentRepository(sql)}),participants=new PgContestParticipantRepository(sql),results=new PgContestResultRepository(sql),record=new RecordContestResult({contestRepository:new PgContestRepository(sql),stageRepository:new PgStageRepository(sql),competitionRepository:new PgCompetitionRepository(sql),eventRepository:new PgEventRepository(sql),participantRepository:participants,recorder:results,authorization,clock:new FakeClock(NOW as never),idGenerator:new UuidIdGenerator(),domainEvents:new InMemoryEventPublisher()}),progress=new ProgressFinalizedContestResult({resultRepository:results,participantRepository:participants,contestRepository:new PgContestRepository(sql),stageRepository:new PgStageRepository(sql),competitionRepository:new PgCompetitionRepository(sql),eventRepository:new PgEventRepository(sql),divisionRepository:new PgDivisionRepository(sql),formatRepository:new PgCompetitionFormatRepository(sql),structure:new PgCompetitionStructureMaterializer(sql),progressor:new PgContestResultProgressor(sql),engines:createCompetitionFormatEngineRegistry(),authorization,clock:new FakeClock(NOW as never),idGenerator:new UuidIdGenerator(),domainEvents:new InMemoryEventPublisher()}),facade=new FinalizeOrganizerMatchResult({organizerContext:context,participants,record,progress}),response=await createFinalizeOrganizerMatchHandler(()=>({finalizeMatch:facade,close:async()=>undefined}))(new Request("https://sports.test/result",{method:"POST",headers:{authorization:"Bearer trusted-test-adapter","content-type":"application/json"},body:JSON.stringify({organizationId:x("org-a"),contestId:x("contest-final"),winnerContestParticipantId:PARTICIPANT_1})}));expect(response.status).toBe(200);expect(await response.json()).toMatchObject({progression:"progressed"});expect(await sql`SELECT status FROM contest_results WHERE contest_id=${x("contest-final")}`).toEqual([{status:"finalized"}]);expect(await sql`SELECT participant_count FROM contest_result_progressions WHERE contest_result_id=(SELECT id FROM contest_results WHERE contest_id=${x("contest-final")})`).toEqual([{participant_count:0}]);expect(await operations.execute({organizationId:x("org-a"),competitionFormatId:x("format-a")})).toMatchObject({ok:true,value:{view:{phase:"final_pending"}}});});
});
