import {afterAll,beforeAll,describe,expect,it} from "vitest";
import postgres from "postgres";
import {FakeClock,FakeIdGenerator,InMemoryEventPublisher,PgCompetitionEntryRepository,PgCompetitionFormatRepository,PgCompetitionRepository,PgCompetitionStructureMaterializer,PgDivisionRepository,PgEventRepository,PgContestRepository,PgStageRepository} from "@adapters";
import type {Sql} from "@adapters";
import {MaterializeCompetitionFormatPlan} from "@app/use-cases/materialize-competition-format-plan";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import {createCompetitionFormat} from "@domain/competition/competition-format";
import {createContest,createStage} from "@domain/competition/competition";
import {createCompetitionFormatEngineRegistry} from "@composition/competition-format-engines";
import type {CompetitionFormat} from "@domain/competition/competition-format";
import type {Contest,Stage} from "@domain/competition/competition.types";
import type {Id,ISODateString} from "@shared/kernel";

const URL=process.env.TEST_DATABASE_URL??"",RUN=URL.length>0,P=`mat-${Date.now()}-${Math.floor(Math.random()*1e6)}`,NOW="2026-09-21T10:00:00.000Z" as ISODateString;
const id=<T extends string>(x:string)=>`${P}-${x}` as Id<T>,meta={now:NOW,domainEventId:`${P}-event`};
describe.skipIf(!RUN)("PostgreSQL format materialization",()=>{
 let sql:Sql,materializer:PgCompetitionStructureMaterializer,format:CompetitionFormat;
 beforeAll(async()=>{sql=postgres(URL,{ssl:"require",max:8,onnotice:()=>{}}) as Sql;materializer=new PgCompetitionStructureMaterializer(sql);
  await sql`INSERT INTO organizations(id,name,slug,type,status,country_code,version,created_at,updated_at) VALUES(${id<"Organization">("org")},'Materialization Org',${P},'club','active','US',1,${NOW},${NOW})`;
  await sql`INSERT INTO events(id,organization_id,name,key,status,created_at,updated_at,version) VALUES(${id<"Event">("event")},${id<"Organization">("org")},'Event','event','draft',${NOW},${NOW},1)`;
  await sql`INSERT INTO competitions(id,event_id,sport_id,name,key,status,created_at,updated_at,version) VALUES(${id<"Competition">("competition")},${id<"Event">("event")},'sport-basketball','Competition','competition','draft',${NOW},${NOW},1)`;
  await sql`INSERT INTO competition_divisions(id,competition_id,name,key,status,created_at,updated_at,version) VALUES(${id<"Division">("division")},${id<"Competition">("competition")},'Open','open','active',${NOW},${NOW},1)`;
  for(let n=1;n<=6;n++)await sql`INSERT INTO teams(id,organization_id,sport_id,name,key,status,created_at,updated_at,version) VALUES(${id<"Team">(`team-${n}`)},${id<"Organization">("org")},'sport-basketball',${`Team ${n}`},${`team-${n}`},'active',${NOW},${NOW},1)`;
  const made=createCompetitionFormat({...meta,id:id<"CompetitionFormat">("format"),competitionId:id<"Competition">("competition"),kind:"single_elimination"});if(!made.ok)throw Error();format=made.value.format;await new PgCompetitionFormatRepository(sql).create(format);
  for(let n=1;n<=6;n++)await sql`INSERT INTO competition_entries(id,competition_id,entrant_type,team_id,status,created_at,updated_at,version) VALUES(${id<"CompetitionEntry">(`entry-${n}`)},${format.competitionId},'team',${id<"Team">(`team-${n}`)},'active',${NOW},${NOW},1)`;
 });
 afterAll(async()=>{await sql`DELETE FROM contests WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competition_stages WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competition_format_materializations WHERE competition_format_id LIKE ${`${P}%`}`;await sql`DELETE FROM competition_entries WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competition_formats WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competition_divisions WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competitions WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM events WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM teams WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM organizations WHERE id LIKE ${`${P}%`}`;await sql.end({timeout:5});});
 const auth={execute:async()=>({ok:true as const,value:{allowed:true}})} as unknown as AuthorizeOrganizationPermission;
 function useCase(prefix:string){return new MaterializeCompetitionFormatPlan({competitionFormatRepository:new PgCompetitionFormatRepository(sql),competitionRepository:new PgCompetitionRepository(sql),divisionRepository:new PgDivisionRepository(sql),eventRepository:new PgEventRepository(sql),competitionEntryRepository:new PgCompetitionEntryRepository(sql),materializer,engines:createCompetitionFormatEngineRegistry(),authorization:auth,clock:new FakeClock(NOW),idGenerator:new FakeIdGenerator(`${P}-${prefix}`),domainEvents:new InMemoryEventPublisher()});}
 it("materializes the six-entrant plan once with durable source linkage",async()=>{const result=await useCase("success").execute({actingMembershipId:"membership",competitionFormatId:format.id});expect(result).toMatchObject({ok:true,value:{stageCount:3,contestCount:5}});const stages=await sql<{id:string;competition_id:string;division_id:string|null;competition_format_id:string;version:number}[]>`SELECT id,competition_id,division_id,competition_format_id,version FROM competition_stages WHERE competition_format_id=${format.id}`;expect(stages).toHaveLength(3);expect(stages.every(x=>x.competition_id===format.competitionId&&x.division_id===null&&x.competition_format_id===format.id&&x.version===1)).toBe(true);const contests=await sql<{count:number}[]>`SELECT count(*)::int count FROM contests WHERE stage_id IN (SELECT id FROM competition_stages WHERE competition_format_id=${format.id})`;expect(contests[0]?.count).toBe(5);expect((await sql<{count:number}[]>`SELECT count(*)::int count FROM competition_format_materializations WHERE competition_format_id=${format.id}`)[0]?.count).toBe(1);expect(await useCase("duplicate").execute({actingMembershipId:"membership",competitionFormatId:format.id})).toMatchObject({ok:false,error:{kind:"already_materialized"}});});
 it("allows exactly one concurrent claim and one graph",async()=>{const f=await insertFormat("concurrent");const a=candidates(f,"a"),b=candidates(f,"b");const results=await Promise.all([materializer.materialize({...a,format:f,createdAt:NOW}),materializer.materialize({...b,format:f,createdAt:NOW})]);expect(results.filter(x=>x.ok)).toHaveLength(1);expect(results.filter(x=>!x.ok&&x.error.kind==="already_materialized")).toHaveLength(1);expect((await sql<{count:number}[]>`SELECT count(*)::int count FROM competition_stages WHERE competition_format_id=${f.id}`)[0]?.count).toBe(1);expect((await sql<{count:number}[]>`SELECT count(*)::int count FROM contests WHERE stage_id IN (SELECT id FROM competition_stages WHERE competition_format_id=${f.id})`)[0]?.count).toBe(1);});
 it("rolls back marker, Stage and Contest on a real Contest check failure",async()=>{const f=await insertFormat("rollback"),x=candidates(f,"rollback");const invalid={...x.contests[0]!,sequence:0};expect(await materializer.materialize({format:f,stages:x.stages,contests:[invalid],createdAt:NOW})).toMatchObject({ok:false,error:{kind:"unavailable"}});for(const table of ["competition_format_materializations","competition_stages"] as const)expect((await sql.unsafe<{count:number}[]>(`SELECT count(*)::int count FROM ${table} WHERE ${table==="competition_format_materializations"?"competition_format_id":"competition_format_id"}=$1`,[f.id]))[0]?.count).toBe(0);expect((await sql<{count:number}[]>`SELECT count(*)::int count FROM contests WHERE id=${invalid.id}`)[0]?.count).toBe(0);});
 it("preserves Division scope and database integrity posture",async()=>{const f=await insertFormat("division",id<"Division">("division")),x=candidates(f,"division");expect((await materializer.materialize({format:f,...x,createdAt:NOW})).ok).toBe(true);expect((await sql<{division_id:string|null}[]>`SELECT division_id FROM competition_stages WHERE competition_format_id=${f.id}`)[0]?.division_id).toBe(id<"Division">("division"));await expect(sql`INSERT INTO competition_stages(id,competition_id,name,key,sequence,status,created_at,updated_at,version,competition_format_id) VALUES(${id<"Stage">("bad-fk")},${format.competitionId},'Bad','bad-fk',1,'pending',${NOW},${NOW},1,${id<"CompetitionFormat">("missing")})`).rejects.toMatchObject({code:"23503"});const posture=await sql<{relname:string;relrowsecurity:boolean;policies:number}[]>`SELECT c.relname,c.relrowsecurity,(SELECT count(*)::int FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=c.relname) policies FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('competition_format_materializations','competition_stages') ORDER BY c.relname`;expect(posture).toEqual([{relname:"competition_format_materializations",relrowsecurity:true,policies:0},{relname:"competition_stages",relrowsecurity:true,policies:0}]);});
 it("retains manual Stage and existing Contest persistence",async()=>{const stageMade=createStage({...meta,id:id<"Stage">("manual"),competitionId:format.competitionId,name:"Manual",key:"manual",sequence:99});if(!stageMade.ok)throw Error();expect(await new PgStageRepository(sql).create(stageMade.value.value)).toMatchObject({ok:true});expect((await sql<{competition_format_id:string|null}[]>`SELECT competition_format_id FROM competition_stages WHERE id=${stageMade.value.value.id}`)[0]?.competition_format_id).toBeNull();const contestMade=createContest({...meta,id:id<"Contest">("manual-contest"),stageId:stageMade.value.value.id,sequence:1});if(!contestMade.ok)throw Error();expect(await new PgContestRepository(sql).create(contestMade.value.value)).toMatchObject({ok:true});});
  async function insertFormat(suffix:string,divisionId:Id<"Division">|null=null){const made=createCompetitionFormat({...meta,id:id<"CompetitionFormat">(`format-${suffix}`),competitionId:format.competitionId,divisionId,kind:"single_elimination"});if(!made.ok)throw Error();await sql`INSERT INTO competition_formats(id,competition_id,division_id,kind,status,created_at,updated_at,version) VALUES(${made.value.format.id},${made.value.format.competitionId},${made.value.format.divisionId},${made.value.format.kind},'retired',${NOW},${NOW},1)`;return made.value.format;}
 function candidates(f:CompetitionFormat,suffix:string):{stages:Stage[];contests:Contest[]}{const sm=createStage({...meta,id:id<"Stage">(`${suffix}-stage`),competitionId:f.competitionId,divisionId:f.divisionId,competitionFormatId:f.id,name:"Generated",key:`${suffix}-generated`,sequence:1});if(!sm.ok)throw Error();const cm=createContest({...meta,id:id<"Contest">(`${suffix}-contest`),stageId:sm.value.value.id,sequence:1});if(!cm.ok)throw Error();return{stages:[sm.value.value],contests:[cm.value.value]};}
});
