import { afterAll,afterEach,beforeAll,describe,expect,it } from "vitest";
import postgres from "postgres";
import type { Sql } from "@adapters/persistence/pg/connection";
import { PgOrganizationMembershipRepository } from "@adapters/persistence/pg/pg-organization-membership-repository";
import { createOrganizationMembership,deactivateOrganizationMembership } from "@domain/organization/organization-membership";
import type { Id,ISODateString } from "@shared/kernel";
const URL=process.env.TEST_DATABASE_URL??"",RUN=URL.trim().length>0,PREFIX=`membership_it_${Date.now()}_${Math.floor(Math.random()*1e6)}`,SLUG=PREFIX.replaceAll("_","-"),NOW="2026-09-12T00:00:00Z" as ISODateString;
describe.skipIf(!RUN)("PostgreSQL OrganizationMembership persistence",()=>{let sql:Sql,repo:PgOrganizationMembershipRepository;const oid=`${PREFIX}-org`,pid=`${PREFIX}-person`;function value(id:string,person=pid){const r=createOrganizationMembership({membershipId:`${PREFIX}-${id}` as Id<"OrganizationMembership">,organizationId:oid as Id<"Organization">,personId:person as Id<"Person">,now:NOW,eventId:"e"});if(!r.ok)throw Error();return r.value.membership;}
beforeAll(async()=>{sql=postgres(URL,{max:2,ssl:"require",onnotice:()=>{}}) as Sql;repo=new PgOrganizationMembershipRepository(sql);await sql`INSERT INTO persons (id,display_name,lifecycle_status,version,updated_at) VALUES (${pid},'Fixture','active',1,${NOW})`;await sql`INSERT INTO sports_ids (value,person_id,issued_at,status) VALUES (${`${PREFIX}-sports`},${pid},${NOW},'active')`;await sql`INSERT INTO organizations (id,name,slug,type,status,country_code,version,created_at,updated_at) VALUES (${oid},'Fixture',${SLUG},'club','active','US',1,${NOW},${NOW})`;});afterAll(async()=>{await sql`DELETE FROM organization_memberships WHERE id LIKE ${`${PREFIX}%`}`;await sql`DELETE FROM sports_ids WHERE person_id=${pid}`;await sql`DELETE FROM persons WHERE id LIKE ${`${PREFIX}%`}`;await sql`DELETE FROM organizations WHERE id LIKE ${`${PREFIX}%`}`;await sql.end({timeout:5});});
afterEach(async()=>{await sql`DELETE FROM organization_memberships WHERE id LIKE ${`${PREFIX}%`}`;});
it("round trips and enforces unique pair",async()=>{const m=value("one");expect((await repo.create(m)).ok).toBe(true);expect(await repo.findById(m.id)).toMatchObject({kind:"found",membership:{...m,createdAt:"2026-09-12T00:00:00.000Z",updatedAt:"2026-09-12T00:00:00.000Z"}});expect(await repo.findByOrganizationAndPerson(m.organizationId,m.personId)).toMatchObject({kind:"found",membership:{id:m.id}});expect(await repo.create(value("two"))).toMatchObject({ok:false,error:{kind:"duplicate_membership"}});});
it("enforces Person and Organization foreign keys",async()=>{expect(await repo.create(value("bad-person",`${PREFIX}-missing`))).toMatchObject({ok:false,error:{kind:"unavailable"}});const m=value("bad-org");expect(await repo.create({...m,organizationId:`${PREFIX}-missing` as Id<"Organization">})).toMatchObject({ok:false,error:{kind:"unavailable"}});});
it.each([["status","pending"],["version",0]])("enforces %s constraint",async(column,v)=>{await expect(sql.unsafe(`INSERT INTO organization_memberships (id,organization_id,person_id,status,version,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$6)`,[`${PREFIX}-bad-${column}`,oid,pid,column==="status"?v:"active",column==="version"?v:1,NOW])).rejects.toMatchObject({code:"23514"});});
it("persists supplied N+1 and rejects stale expected version",async()=>{const m=value("save");await repo.create(m);const d=deactivateOrganizationMembership(m,{now:"2026-09-12T01:00:00Z" as ISODateString,eventId:"e2"});if(!d.ok)throw Error();expect(await repo.save(d.value.membership,m.version)).toMatchObject({ok:true,value:{version:2,status:"inactive"}});expect(await repo.save(d.value.membership,m.version)).toMatchObject({ok:false,error:{kind:"concurrency_conflict"}});});
it("maps malformed persisted state",async()=>{const m=value("mapping");await repo.create(m);await sql`ALTER TABLE organization_memberships DROP CONSTRAINT organization_memberships_status_valid`;try{await sql`UPDATE organization_memberships SET status='bad' WHERE id=${m.id}`;expect(await repo.findById(m.id)).toMatchObject({kind:"invalid_persistence_state"});}finally{await sql`DELETE FROM organization_memberships WHERE id=${m.id}`;await sql`ALTER TABLE organization_memberships ADD CONSTRAINT organization_memberships_status_valid CHECK (status IN ('active','inactive'))`;}});
it("has RLS enabled and zero policies",async()=>{const rows=await sql<{rowsecurity:boolean;policies:number}[]>`SELECT c.relrowsecurity AS rowsecurity,(SELECT count(*)::int FROM pg_policies p WHERE p.schemaname='public' AND p.tablename='organization_memberships') AS policies FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='organization_memberships'`;expect(rows[0]).toEqual({rowsecurity:true,policies:0});});});
