import { afterAll, beforeAll, describe, expect, it } from "vitest";
import postgres from "postgres";
import type { Sql } from "@adapters/persistence/pg/connection";
import { PgPersonClaimRepository } from "@adapters/persistence/pg/pg-person-claim-repository";
import { consumePersonClaim } from "@domain/auth/person-claim";
import type { Account, AuthSubject } from "@domain/auth/account";
import type { AggregateVersion } from "@domain/aggregate";
import type { ClaimTokenHash, PersonClaim } from "@domain/auth/person-claim";
import type { Id, ISODateString } from "@shared/kernel";

const URL=process.env.TEST_DATABASE_URL??"";const RUN=URL.trim().length>0;const PREFIX=`claim_it_${Date.now()}_${Math.floor(Math.random()*1e6)}`;const NOW="2026-09-11T00:00:00.000Z" as ISODateString;const LATER="2026-09-11T01:00:00.000Z" as ISODateString;const key=(s:string)=>`${PREFIX}_${s}`;
function claim(id:string,person:string,hash:string):PersonClaim{return{id:key(id) as Id<"PersonClaim">,personId:key(person) as Id<"Person">,tokenHash:key(hash) as ClaimTokenHash,status:"pending",expiresAt:"2026-09-12T00:00:00.000Z" as ISODateString,consumedAt:null,createdAt:NOW,updatedAt:NOW,version:1 as AggregateVersion};}
function account(id:string,subject:string,person:string):Account{return{id:key(id) as Id<"Account">,authSubject:key(subject) as AuthSubject,personId:key(person) as Id<"Person">,status:"active",createdAt:LATER,updatedAt:LATER,version:1 as AggregateVersion};}
describe.skipIf(!RUN)("PostgreSQL PersonClaim persistence",()=>{
 let sql:Sql;let repository:PgPersonClaimRepository;
 beforeAll(async()=>{sql=postgres(URL,{ssl:"require",max:6,onnotice:()=>{}}) as Sql;repository=new PgPersonClaimRepository(sql);await sql`INSERT INTO persons(id,display_name,lifecycle_status,version,updated_at) VALUES(${key("p1")},'Claim One','active',1,${NOW}),(${key("p2")},'Claim Two','active',1,${NOW}),(${key("p3")},'Claim Three','active',1,${NOW}),(${key("p4")},'Claim Four','active',1,${NOW}),(${key("p5")},'Claim Five','active',1,${NOW}),(${key("p6")},'Claim Six','active',1,${NOW})`;});
 afterAll(async()=>{await sql`DELETE FROM person_claims WHERE id LIKE ${`${PREFIX}_%`}`;await sql`DELETE FROM accounts WHERE id LIKE ${`${PREFIX}_%`}`;await sql`DELETE FROM persons WHERE id LIKE ${`${PREFIX}_%`}`;await sql.end({timeout:5});});
 it("persists and rehydrates without a raw token",async()=>{expect((await repository.issueReplacingPending(claim("c1","p1","h1"))).ok).toBe(true);expect(await repository.findByTokenHash(key("h1") as ClaimTokenHash)).toMatchObject({kind:"found",claim:{id:key("c1"),personId:key("p1"),status:"pending",version:1}});});
 it("enforces the Person foreign key",async()=>{expect(await repository.issueReplacingPending(claim("cfk","missing","hfk"))).toMatchObject({ok:false,error:{kind:"person_not_found"}});});
 it("enforces unique token hashes",async()=>{expect(await repository.issueReplacingPending({...claim("c2","p2","h1"),tokenHash:key("h1") as ClaimTokenHash})).toMatchObject({ok:false,error:{kind:"duplicate_token_hash"}});});
 it("enforces positive version",async()=>{await expect(sql`INSERT INTO person_claims(id,person_id,token_hash,status,expires_at,created_at,updated_at,version) VALUES(${key("bad-version")},${key("p2")},${key("bad-version-hash")},'pending',${"2026-09-12T00:00:00.000Z"},${NOW},${NOW},0)`).rejects.toMatchObject({code:"23514"});});
 it("enforces one pending claim per Person",async()=>{await repository.issueReplacingPending(claim("pending","p2","pending-h"));await expect(sql`INSERT INTO person_claims(id,person_id,token_hash,status,expires_at,created_at,updated_at,version) VALUES(${key("pending-2")},${key("p2")},${key("pending-h2")},'pending',${"2026-09-12T00:00:00.000Z"},${NOW},${NOW},1)`).rejects.toMatchObject({code:"23505"});});
 it("atomically creates Account and consumes claim, then rejects replay",async()=>{const original=claim("atomic","p3","atomic-h");await repository.issueReplacingPending(original);const consumed=consumePersonClaim(original,LATER);if(!consumed.ok)throw new Error();expect((await repository.createAccountAndConsumeClaim(account("atomic-a","atomic-s","p3"),consumed.value,original.version)).ok).toBe(true);expect(await repository.createAccountAndConsumeClaim(account("replay-a","replay-s","p3"),consumed.value,original.version)).toMatchObject({ok:false,error:{kind:"consumed_claim"}});},15000);
 it("permits only one concurrent consumer",async()=>{const original=claim("race","p4","race-h");await repository.issueReplacingPending(original);const consumed=consumePersonClaim(original,LATER);if(!consumed.ok)throw new Error();const results=await Promise.all([repository.createAccountAndConsumeClaim(account("race-a1","race-s1","p4"),consumed.value,original.version),repository.createAccountAndConsumeClaim(account("race-a2","race-s2","p4"),consumed.value,original.version)]);expect(results.filter(x=>x.ok)).toHaveLength(1);expect(results.filter(x=>!x.ok)).toHaveLength(1);});
 it("rolls claim consumption back when Account insertion fails",async()=>{await sql`INSERT INTO accounts(id,auth_subject,person_id,status,version,created_at,updated_at) VALUES(${key("existing-a")},${key("duplicate-subject")},${key("p5")},'active',1,${NOW},${NOW})`;const original=claim("rollback","p6","rollback-h");await repository.issueReplacingPending(original);const consumed=consumePersonClaim(original,LATER);if(!consumed.ok)throw new Error();expect(await repository.createAccountAndConsumeClaim(account("rollback-a","duplicate-subject","p6"),consumed.value,original.version)).toMatchObject({ok:false,error:{kind:"auth_subject_already_linked"}});expect(await repository.findByTokenHash(original.tokenHash)).toMatchObject({kind:"found",claim:{status:"pending",version:1}});});
});
