import { afterAll, beforeAll, describe, expect, it } from "vitest";
import postgres from "postgres";
import type { Sql } from "@adapters/persistence/pg/connection";
import { PgPersonClaimRepository } from "@adapters/persistence/pg/pg-person-claim-repository";
import { consumePersonClaim } from "@domain/auth/person-claim";
import { NodeClaimTokenGenerator, VersionedHmacClaimHashKeyProvider } from "@adapters/auth/node-claim-token-crypto";
import type { Account, AuthSubject } from "@domain/auth/account";
import type { AggregateVersion } from "@domain/aggregate";
import type { ClaimLookupId, ClaimTokenHash, PersonClaim } from "@domain/auth/person-claim";
import type { Id, ISODateString } from "@shared/kernel";

const URL=process.env.TEST_DATABASE_URL??"";const RUN=URL.trim().length>0;const PREFIX=`claim_it_${Date.now()}_${Math.floor(Math.random()*1e6)}`;const NOW="2026-09-11T00:00:00.000Z" as ISODateString;const LATER="2026-09-11T01:00:00.000Z" as ISODateString;const key=(s:string)=>`${PREFIX}_${s}`;
function claim(id:string,person:string,hash:string):PersonClaim{return{id:key(id) as Id<"PersonClaim">,personId:key(person) as Id<"Person">,tokenHash:key(hash) as ClaimTokenHash,lookupId:key(`lookup_${id}`) as ClaimLookupId,hashKeyVersion:"v1" as never,issuedBy:{type:"system",subject:"integration-test"},status:"pending",expiresAt:"2026-09-12T00:00:00.000Z" as ISODateString,consumedAt:null,createdAt:NOW,updatedAt:NOW,version:1 as AggregateVersion};}
function account(id:string,subject:string,person:string):Account{return{id:key(id) as Id<"Account">,authSubject:key(subject) as AuthSubject,personId:key(person) as Id<"Person">,status:"active",createdAt:LATER,updatedAt:LATER,version:1 as AggregateVersion};}
describe.skipIf(!RUN)("PostgreSQL PersonClaim persistence",()=>{
 let sql:Sql;let repository:PgPersonClaimRepository;
 beforeAll(async()=>{sql=postgres(URL,{ssl:"require",max:6,onnotice:()=>{}}) as Sql;repository=new PgPersonClaimRepository(sql);await sql`INSERT INTO persons(id,display_name,lifecycle_status,version,updated_at) VALUES(${key("p1")},'Claim One','active',1,${NOW}),(${key("p2")},'Claim Two','active',1,${NOW}),(${key("p3")},'Claim Three','active',1,${NOW}),(${key("p4")},'Claim Four','active',1,${NOW}),(${key("p5")},'Claim Five','active',1,${NOW}),(${key("p6")},'Claim Six','active',1,${NOW})`;});
 afterAll(async()=>{await sql`DELETE FROM person_claims WHERE id LIKE ${`${PREFIX}_%`}`;await sql`DELETE FROM accounts WHERE id LIKE ${`${PREFIX}_%`}`;await sql`DELETE FROM persons WHERE id LIKE ${`${PREFIX}_%`}`;await sql.end({timeout:5});});
 it("persists and rehydrates key version and audit metadata without a raw token",async()=>{const original=claim("c1","p1","h1");expect((await repository.issueReplacingPending(original)).ok).toBe(true);expect(await repository.findByLookupId(original.lookupId)).toMatchObject({kind:"found",claim:{id:key("c1"),personId:key("p1"),hashKeyVersion:"v1",issuedBy:{subject:"integration-test"},status:"pending",version:1}});});
 it("verifies an old-version persisted claim while new claims use the active version",async()=>{await sql`INSERT INTO persons(id,display_name,lifecycle_status,version,updated_at) VALUES(${key("p7")},'Rotation Old','active',1,${NOW}),(${key("p8")},'Rotation New','active',1,${NOW})`;const keys=new VersionedHmacClaimHashKeyProvider({activeVersion:"v2",keys:[{version:"v1",secret:"old-integration-key-at-least-thirty-two"},{version:"v2",secret:"new-integration-key-at-least-thirty-two"}]}),generator=new NodeClaimTokenGenerator(),oldToken=generator.generate("v1" as never),oldHash=keys.hash(oldToken.version,oldToken.lookupId,oldToken.secret);if(!oldHash.ok)throw new Error();const old={...claim("rotation-old","p7","unused"),lookupId:oldToken.lookupId,hashKeyVersion:oldToken.version,tokenHash:oldHash.hash};await repository.issueReplacingPending(old);const loaded=await repository.findByLookupId(old.lookupId);expect(loaded).toMatchObject({kind:"found",claim:{hashKeyVersion:"v1"}});if(loaded.kind!=="found")throw new Error();expect(keys.verify(loaded.claim.hashKeyVersion,loaded.claim.lookupId,oldToken.secret,loaded.claim.tokenHash)).toEqual({ok:true,matches:true});const current=generator.generate(keys.activeVersion());expect(current.version).toBe("v2");});
 it("enforces the Person foreign key",async()=>{expect(await repository.issueReplacingPending(claim("cfk","missing","hfk"))).toMatchObject({ok:false,error:{kind:"person_not_found"}});});
 it("enforces unique token hashes",async()=>{expect(await repository.issueReplacingPending({...claim("c2","p2","h1"),tokenHash:key("h1") as ClaimTokenHash})).toMatchObject({ok:false,error:{kind:"duplicate_token_hash"}});});
 it("enforces positive version",async()=>{const c=claim("bad-version","p2","bad-version-hash");await expect(repository.issueReplacingPending({...c,version:0 as AggregateVersion})).resolves.toMatchObject({ok:false,error:{kind:"invalid_persistence_state"}});});
 it("enforces one pending claim per Person",async()=>{await repository.issueReplacingPending(claim("pending","p2","pending-h"));expect(await repository.issueReplacingPending(claim("pending-2","p2","pending-h2"))).toMatchObject({ok:false,error:{kind:"concurrency_conflict"}});});
 it("atomically creates Account and consumes claim, then rejects replay",async()=>{const original=claim("atomic","p3","atomic-h");await repository.issueReplacingPending(original);const consumed=consumePersonClaim(original,LATER);if(!consumed.ok)throw new Error();expect((await repository.createAccountAndConsumeClaim(account("atomic-a","atomic-s","p3"),consumed.value,original.version)).ok).toBe(true);expect(await repository.createAccountAndConsumeClaim(account("replay-a","replay-s","p3"),consumed.value,original.version)).toMatchObject({ok:false,error:{kind:"consumed_claim"}});},15000);
 it("permits only one concurrent consumer",async()=>{const original=claim("race","p4","race-h");await repository.issueReplacingPending(original);const consumed=consumePersonClaim(original,LATER);if(!consumed.ok)throw new Error();const results=await Promise.all([repository.createAccountAndConsumeClaim(account("race-a1","race-s1","p4"),consumed.value,original.version),repository.createAccountAndConsumeClaim(account("race-a2","race-s2","p4"),consumed.value,original.version)]);expect(results.filter(x=>x.ok)).toHaveLength(1);expect(results.filter(x=>!x.ok)).toHaveLength(1);});
 it("rolls claim consumption back when Account insertion fails",async()=>{await sql`INSERT INTO accounts(id,auth_subject,person_id,status,version,created_at,updated_at) VALUES(${key("existing-a")},${key("duplicate-subject")},${key("p5")},'active',1,${NOW},${NOW})`;const original=claim("rollback","p6","rollback-h");await repository.issueReplacingPending(original);const consumed=consumePersonClaim(original,LATER);if(!consumed.ok)throw new Error();expect(await repository.createAccountAndConsumeClaim(account("rollback-a","duplicate-subject","p6"),consumed.value,original.version)).toMatchObject({ok:false,error:{kind:"auth_subject_already_linked"}});expect(await repository.findByLookupId(original.lookupId)).toMatchObject({kind:"found",claim:{status:"pending",version:1}});});
});
