import {randomUUID} from "node:crypto";
import postgres from "postgres";
import {afterAll,beforeAll,describe,expect,it,vi} from "vitest";
import type {Sql} from "@adapters";
import {PgOrganizationMembershipRepository,PgOrganizationRoleAssignmentRepository,PgOrganizationRoleRepository,PgTournamentOperationsReader} from "@adapters";
import {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import {GetTournamentOperationsView} from "@app/use-cases/get-tournament-operations-view";

const URL=process.env.TEST_DATABASE_URL??"",RUN=URL.length>0,P=`ops-${Date.now()}-${Math.floor(Math.random()*1e6)}`,NOW="2026-09-28T00:00:00.000Z";
const x=(name:string)=>`${P}-${name}`;
const uuids=new Map<string,string>(),u=(name:string)=>{const found=uuids.get(name);if(found)return found;const made=randomUUID();uuids.set(name,made);return made;};
vi.setConfig({testTimeout:120_000,hookTimeout:120_000});

describe.skipIf(!RUN)("PostgreSQL Tournament Operations A-J",()=>{
 let sql:Sql,query:GetTournamentOperationsView;
 const read=(membership="reader",format="format")=>query.execute({actingMembershipId:x(membership),competitionFormatId:x(format)});
 beforeAll(async()=>{
  sql=postgres(URL,{ssl:"require",max:10,onnotice:()=>{}}) as Sql;
  await sql`INSERT INTO persons(id,display_name,lifecycle_status,created_at,version) VALUES(${x("person-reader")},'Reader','active',${NOW},1),(${x("person-wrong")},'Wrong','active',${NOW},1),(${x("person-inactive")},'Inactive','active',${NOW},1),(${x("person-manage")},'Manager','active',${NOW},1)`;
  await sql`INSERT INTO organizations(id,name,slug,type,status,country_code,version,created_at,updated_at) VALUES(${x("org")},'Ops Org',${x("org")},'club','active','US',1,${NOW},${NOW}),(${x("wrong-org")},'Wrong Org',${x("wrong-org")},'club','active','US',1,${NOW},${NOW})`;
  await sql`INSERT INTO organization_memberships(id,organization_id,person_id,status,version,created_at,updated_at) VALUES(${x("reader")},${x("org")},${x("person-reader")},'active',1,${NOW},${NOW}),(${x("wrong")},${x("wrong-org")},${x("person-wrong")},'active',1,${NOW},${NOW}),(${x("inactive")},${x("org")},${x("person-inactive")},'inactive',1,${NOW},${NOW}),(${x("manage")},${x("org")},${x("person-manage")},'active',1,${NOW},${NOW})`;
  await sql`INSERT INTO organization_roles(id,organization_id,name,key,permissions,status,version,created_at,updated_at) VALUES(${x("read-role")},${x("org")},'Reader',${x("read-role")},ARRAY['organization.events.read'],'active',1,${NOW},${NOW}),(${x("manage-role")},${x("org")},'Manager',${x("manage-role")},ARRAY['organization.events.manage'],'active',1,${NOW},${NOW})`;
  await sql`INSERT INTO organization_role_assignments(id,organization_id,membership_id,role_id,status,version,created_at,updated_at) VALUES(${x("read-assignment")},${x("org")},${x("reader")},${x("read-role")},'active',1,${NOW},${NOW}),(${x("manage-assignment")},${x("org")},${x("manage")},${x("manage-role")},'active',1,${NOW},${NOW})`;
  await sql`INSERT INTO events(id,organization_id,name,key,status,created_at,updated_at,version) VALUES(${x("event")},${x("org")},'Ops Event',${x("event")},'active',${NOW},${NOW},1)`;
  await sql`INSERT INTO competitions(id,event_id,sport_id,name,key,status,created_at,updated_at,version) VALUES(${x("competition")},${x("event")},'sport-basketball','Ops Competition',${x("competition")},'active',${NOW},${NOW},1)`;
  for(let n=1;n<=6;n++){await sql`INSERT INTO teams(id,organization_id,sport_id,name,key,status,created_at,updated_at,version) VALUES(${x(`team-${n}`)},${x("org")},'sport-basketball',${`Team ${n}`},${x(`team-${n}`)},'active',${NOW},${NOW},1)`;await sql`INSERT INTO competition_entries(id,competition_id,entrant_type,team_id,status,created_at,updated_at,version) VALUES(${x(`entry-${n}`)},${x("competition")},'team',${x(`team-${n}`)},'active',${NOW},${NOW},1)`;}
  await sql`INSERT INTO competition_formats(id,competition_id,kind,status,created_at,updated_at,version) VALUES(${x("format")},${x("competition")},'single_elimination','active',${NOW},${NOW},1)`;
  const authorization=new AuthorizeOrganizationPermission({membershipRepository:new PgOrganizationMembershipRepository(sql),roleRepository:new PgOrganizationRoleRepository(sql),assignmentRepository:new PgOrganizationRoleAssignmentRepository(sql)});query=new GetTournamentOperationsView({reader:new PgTournamentOperationsReader(sql),authorization});
 });
 afterAll(async()=>{
  await sql`DELETE FROM competition_placements WHERE competition_outcome_id IN(SELECT id FROM competition_outcomes WHERE competition_format_id=${x("format")})`;await sql`DELETE FROM competition_outcomes WHERE competition_format_id=${x("format")}`;
  await sql`DELETE FROM contest_result_progressions WHERE competition_format_id=${x("format")}`;
  await sql`DELETE FROM contest_result_outcomes WHERE contest_result_id IN(SELECT r.id FROM contest_results r JOIN contests c ON c.id=r.contest_id JOIN competition_stages s ON s.id=c.stage_id WHERE s.competition_id=${x("competition")})`;await sql`DELETE FROM contest_participants WHERE contest_id IN(SELECT c.id FROM contests c JOIN competition_stages s ON s.id=c.stage_id WHERE s.competition_id=${x("competition")})`;await sql`DELETE FROM contest_results WHERE contest_id IN(SELECT c.id FROM contests c JOIN competition_stages s ON s.id=c.stage_id WHERE s.competition_id=${x("competition")})`;
  await sql`DELETE FROM competition_placements WHERE competition_outcome_id IN(SELECT id FROM competition_outcomes WHERE competition_format_id=${x("format")})`;await sql`DELETE FROM competition_outcomes WHERE competition_format_id=${x("format")}`;await sql`DELETE FROM contest_result_progressions WHERE competition_format_id=${x("format")}`;await sql`DELETE FROM contest_result_outcomes WHERE contest_result_id::text LIKE ${`${P}%`}`;await sql`DELETE FROM contest_participants WHERE id::text LIKE ${`${P}%`}`;await sql`DELETE FROM contest_results WHERE id::text LIKE ${`${P}%`}`;await sql`DELETE FROM competition_seed_assignments WHERE competition_format_id=${x("format")}`;await sql`DELETE FROM contests WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competition_stages WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competition_format_materializations WHERE competition_format_id=${x("format")}`;await sql`DELETE FROM competition_formats WHERE id=${x("format")}`;await sql`DELETE FROM competition_entries WHERE competition_id=${x("competition")}`;await sql`DELETE FROM teams WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM competitions WHERE id=${x("competition")}`;await sql`DELETE FROM events WHERE id=${x("event")}`;await sql`DELETE FROM organization_role_assignments WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM organization_roles WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM organization_memberships WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM organizations WHERE id LIKE ${`${P}%`}`;await sql`DELETE FROM persons WHERE id LIKE ${`${P}%`}`;await sql.end({timeout:5});
 });
 it("A projects setup and I enforces exact PostgreSQL authorization",async()=>{
  expect(await read()).toMatchObject({ok:true,value:{view:{phase:"setup",stages:[]}}});for(const member of ["wrong","inactive","manage"])expect(await read(member)).toMatchObject({ok:false,error:{kind:"forbidden"}});
 });
 it("B-D projects six entries, partial seeds, ready state, byes, and manual isolation",async()=>{
  await sql`INSERT INTO competition_format_materializations(competition_format_id,created_at,entrant_count) VALUES(${x("format")},${NOW},6)`;
  await sql`INSERT INTO competition_stages(id,competition_id,competition_format_id,name,key,sequence,status,created_at,updated_at,version) VALUES(${x("s1")},${x("competition")},${x("format")},'R1',${x("s1")},1,'pending',${NOW},${NOW},1),(${x("s2")},${x("competition")},${x("format")},'R2',${x("s2")},2,'pending',${NOW},${NOW},1),(${x("s3")},${x("competition")},${x("format")},'Final',${x("s3")},3,'pending',${NOW},${NOW},1),(${x("manual-stage")},${x("competition")},NULL,'Manual',${x("manual")},99,'pending',${NOW},${NOW},1)`;
  await sql`INSERT INTO contests(id,stage_id,plan_ref,sequence,status,created_at,updated_at,version) VALUES(${x("c1")},${x("s1")},'contest:r1:c1',1,'pending',${NOW},${NOW},1),(${x("c2")},${x("s1")},'contest:r1:c2',2,'pending',${NOW},${NOW},1),(${x("c3")},${x("s2")},'contest:r2:c1',1,'pending',${NOW},${NOW},1),(${x("c4")},${x("s2")},'contest:r2:c2',2,'pending',${NOW},${NOW},1),(${x("c5")},${x("s3")},'contest:final',1,'pending',${NOW},${NOW},1),(${x("manual-contest")},${x("manual-stage")},NULL,1,'pending',${NOW},${NOW},1)`;
  for(const n of [2,1])await sql`INSERT INTO competition_seed_assignments(id,competition_format_id,competition_entry_id,seed_number,version,created_at) VALUES(${randomUUID()},${x("format")},${x(`entry-${n}`)},${n},1,${NOW})`;
  let r=await read();expect(r).toMatchObject({ok:true,value:{view:{phase:"seeding",entrantCount:6,seeding:{assignedCount:2,assignments:[{seedNumber:1},{seedNumber:2}]}}}});if(!r.ok)throw Error();expect(r.value.view.entrants).toEqual(expect.arrayContaining([{competitionEntryId:x("entry-1"),entrantType:"team",identityStatus:"resolved",displayName:"Team 1"}]));expect(r.value.view.stages).toHaveLength(3);expect(r.value.view.contests).toHaveLength(5);expect(r.value.view.contests.map(c=>c.planRef)).toContain("contest:final");expect(r.value.view.stages.some(s=>s.stageId===x("manual-stage"))).toBe(false);
  for(let n=3;n<=6;n++)await sql`INSERT INTO competition_seed_assignments(id,competition_format_id,competition_entry_id,seed_number,version,created_at) VALUES(${randomUUID()},${x("format")},${x(`entry-${n}`)},${n},1,${NOW})`;await sql`UPDATE competition_format_materializations SET seed_finalized_at=${NOW},participants_materialized_at=${NOW} WHERE competition_format_id=${x("format")}`;
  const ps=[["p1","c1",1,4],["p2","c1",2,5],["p3","c2",1,3],["p4","c2",2,6],["p5","c3",1,1],["p6","c4",1,2]] as const;for(const [p,c,pos,seed] of ps)await sql`INSERT INTO contest_participants(id,contest_id,position,competition_entry_id,source_type,source_seed_number,version,created_at) VALUES(${u(p)},${x(c)},${pos},${x(`entry-${seed}`)},'seed',${seed},1,${NOW})`;
  r=await read();expect(r).toMatchObject({ok:true,value:{view:{phase:"ready"}}});if(!r.ok)throw Error();const bye=r.value.view.contests.find(c=>c.contestId===x("c3"))!;expect(bye.participants).toHaveLength(1);expect(bye.participants[0]).toMatchObject({competitionEntryId:x("entry-1"),sourceSeedNumber:1});expect(bye.result).toBeUndefined();
 });
 it("E-J projects progression, protects terminal authority, outcome, and withdrawn history",async()=>{
  const finalize=async(c:string,w:string,l:string,result:string,count:number)=>{await sql`UPDATE contests SET status='completed',version=version+1,updated_at=${NOW} WHERE id=${x(c)}`;await sql`INSERT INTO contest_results(id,contest_id,status,created_at,finalized_at,version) VALUES(${u(result)},${x(c)},'finalized',${NOW},${NOW},1)`;await sql`INSERT INTO contest_result_outcomes(id,contest_result_id,contest_participant_id,outcome,created_at) VALUES(${randomUUID()},${u(result)},${u(w)},'winner',${NOW}),(${randomUUID()},${u(result)},${u(l)},'loser',${NOW})`;await sql`INSERT INTO contest_result_progressions(contest_result_id,competition_format_id,progressed_at,participant_count) VALUES(${u(result)},${x("format")},${NOW},${count})`;};
  await finalize("c1","p1","p2","r1",1);await sql`INSERT INTO contest_participants(id,contest_id,position,competition_entry_id,source_type,source_contest_result_id,source_outcome,version,created_at) VALUES(${u("p7")},${x("c3")},2,${x("entry-4")},'contest_outcome',${u("r1")},'winner',1,${NOW})`;
  let r=await read();expect(r).toMatchObject({ok:true,value:{view:{phase:"in_progress"}}});if(!r.ok)throw Error();expect(r.value.view.contests.find(c=>c.contestId===x("c1"))).toMatchObject({progressionState:"progressed",result:{winnerCompetitionEntryId:x("entry-4"),loserCompetitionEntryId:x("entry-5")}});expect(r.value.view.contests.find(c=>c.contestId===x("c3"))?.participants[1]).toMatchObject({sourceContestResultId:u("r1"),sourceOutcome:"winner"});
  await sql`UPDATE contest_result_progressions SET participant_count=0 WHERE contest_result_id=${u("r1")}`;r=await read();expect(r).toMatchObject({ok:true,value:{view:{phase:"ready"}}});if(!r.ok)throw Error();expect(r.value.view.contests.find(c=>c.contestId===x("c1"))?.progressionState).toBe("awaiting_progression");
  await sql`UPDATE contest_result_progressions SET participant_count=1 WHERE contest_result_id=${u("r1")}`;
  await sql`INSERT INTO contest_participants(id,contest_id,position,competition_entry_id,source_type,source_seed_number,version,created_at) VALUES(${u("p8")},${x("c5")},1,${x("entry-1")},'seed',1,1,${NOW}),(${u("p9")},${x("c5")},2,${x("entry-2")},'seed',2,1,${NOW})`;await finalize("c5","p8","p9","final-result",0);
  r=await read();expect(r).toMatchObject({ok:true,value:{view:{phase:"final_pending"}}});if(!r.ok)throw Error();const final=r.value.view.contests.find(c=>c.planRef==="contest:final")!;expect(final).toMatchObject({progressionState:"terminal_progressed",result:{contestResultId:u("final-result")}});expect(r.value.view.outcome).toBeUndefined();
  await sql`UPDATE competition_entries SET status='withdrawn',version=version+1,updated_at=${NOW} WHERE id=${x("entry-1")}`;r=await read();if(!r.ok)throw Error();expect(r.value.view.contests.find(c=>c.planRef==="contest:final")?.result).toMatchObject({winnerCompetitionEntryId:x("entry-1"),loserCompetitionEntryId:x("entry-2")});expect(r.value.view.entrants.find(e=>e.competitionEntryId===x("entry-1"))).toMatchObject({identityStatus:"resolved",displayName:"Team 1"});
  await sql`INSERT INTO competition_outcomes(id,competition_format_id,status,finalized_at,created_at,version) VALUES(${u("outcome")},${x("format")},'finalized',${NOW},${NOW},1)`;await sql`INSERT INTO competition_placements(id,competition_outcome_id,competition_entry_id,position,source_contest_result_id,created_at,version) VALUES(${randomUUID()},${u("outcome")},${x("entry-1")},1,${u("final-result")},${NOW},1),(${randomUUID()},${u("outcome")},${x("entry-2")},2,${u("final-result")},${NOW},1)`;
  r=await read();expect(r).toMatchObject({ok:true,value:{view:{phase:"completed",outcome:{placements:[{position:1,competitionEntryId:x("entry-1"),sourceContestResultId:u("final-result")},{position:2,competitionEntryId:x("entry-2"),sourceContestResultId:u("final-result")}]}}}});if(!r.ok)throw Error();expect(r.value.view.outcome?.placements).toHaveLength(2);expect(r.value.view.outcome?.placements.some(p=>p.position===3)).toBe(false);
 });
});
