import { describe,expect,it } from "vitest";
import { BootstrapOrganizationAdministrator } from "@app/use-cases/bootstrap-organization-administrator";
import type { OrganizationBootstrapRepository,TrustedOrganizationBootstrapper } from "@app/contracts";
import { FakeClock } from "@adapters/clock/fake-clock";import { FakeIdGenerator } from "@adapters/id/fake-id-generator";import { InMemoryEventPublisher } from "@adapters/events/in-memory-event-publisher";import type { IntegrationEvent } from "@app/contracts/events";
const principal={type:"system",subject:"bootstrap-test"} as TrustedOrganizationBootstrapper;
function setup(repository:OrganizationBootstrapRepository,valid=true){const events=new InMemoryEventPublisher<IntegrationEvent>();return {events,useCase:new BootstrapOrganizationAdministrator({repository,principalValidator:{isValid:()=>valid},idGenerator:new FakeIdGenerator("bootstrap"),clock:new FakeClock("2026-09-13T00:00:00Z"),integrationEvents:events})};}
describe("BootstrapOrganizationAdministrator",()=>{
  it("passes only internally generated graph identifiers and emits one non-PII completion event",async()=>{let calls=0;const repository:OrganizationBootstrapRepository={bootstrap:async command=>{calls++;expect(command).toMatchObject({organizationId:"o",personId:"p"});return {ok:true,value:{membershipId:command.membershipId,roleId:command.roleId,assignmentId:command.assignmentId,membershipVersion:1,roleVersion:1,assignmentVersion:1,established:calls===1}};}};const s=setup(repository);expect((await s.useCase.execute({organizationId:"o",personId:"p",principal})).ok).toBe(true);expect((await s.useCase.execute({organizationId:"o",personId:"p",principal})).ok).toBe(true);expect(s.events.events).toHaveLength(1);expect(JSON.stringify(s.events.events[0])).not.toContain("displayName");});
  it("rejects an invalid trusted principal without persistence",async()=>{let called=false;const s=setup({bootstrap:async()=>{called=true;throw Error();}},false);expect(await s.useCase.execute({organizationId:"o",personId:"p",principal})).toMatchObject({ok:false,error:{kind:"invalid_trusted_principal"}});expect(called).toBe(false);});
  it.each(["organization_not_found","person_not_found","bootstrap_already_established","invalid_persistence_state","concurrency_conflict","unavailable"] as const)("maps %s as a typed outcome",async kind=>{const s=setup({bootstrap:async()=>({ok:false,error:{kind}})});const result=await s.useCase.execute({organizationId:"o",personId:"p",principal});expect(result.ok).toBe(false);if(!result.ok)expect(result.error.kind).toBe(kind==="unavailable"?"persistence_unavailable":kind);});
});
