import { describe,expect,it } from "vitest";
import { FakeClock } from "@adapters/clock/fake-clock";
import { FakeIdGenerator } from "@adapters/id/fake-id-generator";
import { InMemoryEventPublisher } from "@adapters/events/in-memory-event-publisher";
import type { IntegrationEvent,OrganizationOnboardingRepository,TrustedOrganizationOnboarder } from "@app/contracts";
import { OnboardOrganization } from "@app/use-cases/onboard-organization";
import { issueTrustedOrganizationOnboardingCapability } from "@composition/trusted-organization-onboarding";

const input={onboardingRequestKey:"admission-42",name:"Trusted Club",slug:"trusted-club",type:"club",countryCode:"PH",initialAdministratorPersonId:"person-1"};
function setup(repository:OrganizationOnboardingRepository){const capability=issueTrustedOrganizationOnboardingCapability({type:"system",subject:"provisioner"}),events=new InMemoryEventPublisher<IntegrationEvent>();return {capability,events,useCase:new OnboardOrganization({repository,principalValidator:capability.principalValidator,idGenerator:new FakeIdGenerator("onboard"),clock:new FakeClock("2026-09-14T00:00:00Z"),integrationEvents:events})};}
describe("OnboardOrganization",()=>{
  it("generates all authority graph IDs, returns success, and emits one non-PII event",async()=>{const repository:OrganizationOnboardingRepository={onboard:async c=>({ok:true,value:{organization:c.organization,bootstrap:{membershipId:c.membershipId,roleId:c.roleId,assignmentId:c.assignmentId,membershipVersion:1,roleVersion:1,assignmentVersion:1,established:true},replayed:false}})};const s=setup(repository);const result=await s.useCase.execute({...input,principal:s.capability.principal});expect(result).toMatchObject({ok:true,value:{organization:{slug:"trusted-club"},replayed:false}});expect(s.events.events).toHaveLength(1);expect(JSON.stringify(s.events.events[0])).not.toContain("Trusted Club");});
  it("does not emit again on idempotent replay",async()=>{const repository:OrganizationOnboardingRepository={onboard:async c=>({ok:true,value:{organization:c.organization,bootstrap:{membershipId:c.membershipId,roleId:c.roleId,assignmentId:c.assignmentId,membershipVersion:1,roleVersion:1,assignmentVersion:1,established:false},replayed:true}})};const s=setup(repository);expect(await s.useCase.execute({...input,principal:s.capability.principal})).toMatchObject({ok:true,value:{replayed:true}});expect(s.events.events).toHaveLength(0);});
  it("rejects plain-object and JSON capability impersonation without writes",async()=>{let writes=0;const s=setup({onboard:async()=>{writes++;throw Error();}});for(const principal of [{type:"system",subject:"provisioner"},JSON.parse(JSON.stringify(s.capability.principal))])expect(await s.useCase.execute({...input,principal:principal as TrustedOrganizationOnboarder})).toMatchObject({ok:false,error:{kind:"invalid_trusted_principal"}});expect(writes).toBe(0);});
  it.each(["person_not_found","organization_slug_conflict","bootstrap_conflict","invalid_persistence_state","concurrency_conflict","unavailable"] as const)("maps %s without leaking persistence detail",async kind=>{const s=setup({onboard:async()=>({ok:false,error:{kind,detail:"database secret"}})});const result=await s.useCase.execute({...input,principal:s.capability.principal});expect(result).toMatchObject({ok:false,error:{kind:kind==="unavailable"?"persistence_unavailable":kind}});expect(JSON.stringify(result)).not.toContain("database secret");});
});
