import { describe,expect,it } from "vitest";
import { FakeClock,FakeIdGenerator,InMemoryEventPublisher,InMemoryOrganizationTrustRepository } from "@adapters";
import { EvaluateOrganizationTrust,IssueOrganizationTrust,RevokeOrganizationTrust } from "@app/use-cases/organization-trust";
import type { DomainEvent } from "@app/contracts";
import { createOrganizationTrust } from "@domain/organization/organization-trust";
import type { Id,ISODateString } from "@shared/kernel";
const NOW="2026-09-15T10:00:00.000Z" as ISODateString,A="a" as Id<"Organization">,B="b" as Id<"Organization">,R="r" as Id<"Organization">;
function setup(allow=true){const trustRepository=new InMemoryOrganizationTrustRepository(),clock=new FakeClock(NOW),idGenerator=new FakeIdGenerator("trust"),domainEvents=new InMemoryEventPublisher<DomainEvent>();const organizationRepository={findById:async(id:Id<"Organization">)=>[A,B,R].includes(id)?{kind:"found",organization:{}}:{kind:"not_found"}};const authorization={execute:async(i:{organizationId:string;membershipId:string})=>({ok:true,value:{allowed:allow&&i.organizationId===A&&i.membershipId==="active-a"}})};return {trustRepository,clock,idGenerator,domainEvents,organizationRepository,authorization};}
function issue(d:ReturnType<typeof setup>){return new IssueOrganizationTrust({...d,organizationRepository:d.organizationRepository as never,authorization:d.authorization as never});}
describe("Organization trust application boundary",()=>{
 it("denies inactive, wrong-Organization, or unauthorized acting membership",async()=>{const d=setup();expect(await issue(d).execute({actingMembershipId:"inactive",issuerOrganizationId:A,subjectOrganizationId:B,scope:"organizer.verified"})).toMatchObject({ok:false,error:{kind:"forbidden"}});expect(await issue(setup(false)).execute({actingMembershipId:"active-a",issuerOrganizationId:A,subjectOrganizationId:B,scope:"organizer.verified"})).toMatchObject({ok:false,error:{kind:"forbidden"}});});
 it("allows organizer recognition but restricts authority scopes to a directly recognized issuer",async()=>{const d=setup();expect(await issue(d).execute({actingMembershipId:"active-a",issuerOrganizationId:A,subjectOrganizationId:B,scope:"organizer.verified"})).toMatchObject({ok:true});expect(await issue(d).execute({actingMembershipId:"active-a",issuerOrganizationId:A,subjectOrganizationId:B,scope:"competition.sanctioning"})).toMatchObject({ok:false,error:{kind:"issuer_not_governing_authority"}});const root=createOrganizationTrust({trustId:"root" as Id<"OrganizationTrust">,issuerOrganizationId:R,subjectOrganizationId:A,scope:"governing.authority",now:NOW,eventId:"root-event"});if(!root.ok)throw Error();await d.trustRepository.create(root.value.trust);expect(await issue(d).execute({actingMembershipId:"active-a",issuerOrganizationId:A,subjectOrganizationId:B,scope:"competition.sanctioning"})).toMatchObject({ok:true});});
 it("evaluates only the requested direct edge and issuer-only revocation",async()=>{const d=setup(),issued=await issue(d).execute({actingMembershipId:"active-a",issuerOrganizationId:A,subjectOrganizationId:B,scope:"organizer.verified"});if(!issued.ok)throw Error();const evaluate=new EvaluateOrganizationTrust(d);expect(await evaluate.execute({issuerOrganizationId:A,subjectOrganizationId:B,scope:"organizer.verified"})).toMatchObject({ok:true,value:{effective:true}});expect(await evaluate.execute({issuerOrganizationId:R,subjectOrganizationId:B,scope:"organizer.verified"})).toEqual({ok:true,value:{effective:false}});const revoke=new RevokeOrganizationTrust({...d,authorization:d.authorization as never});expect(await revoke.execute({actingMembershipId:"active-a",issuerOrganizationId:R,trustId:issued.value.trust.id})).toMatchObject({ok:false,error:{kind:"forbidden"}});expect(await revoke.execute({actingMembershipId:"active-a",issuerOrganizationId:A,trustId:issued.value.trust.id})).toMatchObject({ok:true,value:{trust:{status:"revoked",version:2}}});expect(d.domainEvents.events.map(e=>e.type)).toEqual(["organization.trust_issued","organization.trust_revoked"]);});
});
