import {describe,expect,it} from "vitest";
import {FakeClock,FakeIdGenerator,InMemoryCompetitionEntryRepository,InMemoryCompetitionFormatRepository,InMemoryCompetitionRepository,InMemoryCompetitionSeedAssignmentRepository,InMemoryCompetitionStructureMaterializer,InMemoryDivisionRepository,InMemoryEventPublisher,InMemoryEventRepository} from "@adapters";
import {AssignCompetitionEntrySeed} from "@app/use-cases/assign-competition-entry-seed";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import {createCompetitionFormat} from "@domain/competition/competition-format";
import {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import {SingleEliminationEngine} from "@domain/competition/single-elimination-engine";
import type {CompetitionEntry} from "@domain/competition/competition-entry.types";
import type {Competition,Division,Event} from "@domain/competition/competition.types";
import type {Id,ISODateString} from "@shared/kernel";
const NOW="2026-09-22T10:00:00.000Z" as ISODateString,id=<T extends string>(x:string)=>x as Id<T>;
async function setup(o:{materialized?:boolean;status?:Competition["status"];retired?:boolean;division?:boolean;divisionStatus?:Division["status"];allowed?:boolean;entryStatus?:CompetitionEntry["status"];active?:number;engine?:boolean}={}){const formats=new InMemoryCompetitionFormatRepository(),competitions=new InMemoryCompetitionRepository(),divisions=new InMemoryDivisionRepository(),events=new InMemoryEventRepository(),entries=new InMemoryCompetitionEntryRepository(),assignments=new InMemoryCompetitionSeedAssignmentRepository(),materializer=new InMemoryCompetitionStructureMaterializer(),published=new InMemoryEventPublisher();const event:Event={id:id<"Event">("event"),organizationId:id<"Organization">("org"),name:"Event",key:"event",status:"draft",startsAt:null,endsAt:null,createdAt:NOW,updatedAt:NOW,version:1 as Event["version"]};const competition:Competition={id:id<"Competition">("competition"),eventId:event.id,sportId:id<"Sport">("sport"),name:"Competition",key:"competition",status:o.status??"draft",createdAt:NOW,updatedAt:NOW,version:1 as Competition["version"]};const division:Division={id:id<"Division">("division"),competitionId:competition.id,name:"Open",key:"open",status:o.divisionStatus??"active",createdAt:NOW,updatedAt:NOW,version:1 as Division["version"]};await events.create(event);await competitions.create(competition);await divisions.create(division);const made=createCompetitionFormat({id:id<"CompetitionFormat">("format"),competitionId:competition.id,divisionId:o.division?division.id:null,kind:"single_elimination",now:NOW,domainEventId:"e"});if(!made.ok)throw Error();await formats.create(made.value.format);if(o.retired)await formats.save({...made.value.format,status:"retired",version:2 as typeof made.value.format.version},1);for(let n=1;n<=(o.active??2);n++){await entries.create({id:id<"CompetitionEntry">(`entry-${n}`),competitionId:competition.id,divisionId:o.division?division.id:null,entrantType:"team",athleteProfileId:null,teamId:id<"Team">(`team-${n}`),status:n===1?(o.entryStatus??"active"):"active",createdAt:NOW,updatedAt:NOW,version:1 as CompetitionEntry["version"]});}if(o.materialized!==false)await materializer.materialize({format:made.value.format,entrantCount:2,stages:[],contests:[],createdAt:NOW});const engines=new CompetitionFormatEngineRegistry();if(o.engine!==false)engines.register(new SingleEliminationEngine());const authorization={execute:async()=>({ok:true as const,value:{allowed:o.allowed??true}})} as unknown as AuthorizeOrganizationPermission;return{useCase:new AssignCompetitionEntrySeed({competitionFormatRepository:formats,competitionRepository:competitions,divisionRepository:divisions,eventRepository:events,competitionEntryRepository:entries,assignmentRepository:assignments,materializer,engines,authorization,clock:new FakeClock(NOW),idGenerator:new FakeIdGenerator("seed"),domainEvents:published}),assignments,published,entries};}
const run=(x:Awaited<ReturnType<typeof setup>>,entry="entry-1",seed=1)=>x.useCase.execute({actingMembershipId:"membership",competitionFormatId:"format",competitionEntryId:entry,seedNumber:seed});
describe("AssignCompetitionEntrySeed",()=>{
 it("requires an active materialized format",async()=>{let x=await setup({materialized:false});expect(await run(x)).toMatchObject({ok:false,error:{kind:"format_not_materialized"}});x=await setup({retired:true});expect(await run(x)).toMatchObject({ok:false,error:{kind:"format_inactive"}});});
 it.each(["draft","active"] as const)("allows %s competitions",async status=>expect((await run(await setup({status}))).ok).toBe(true));
 it.each(["completed","cancelled"] as const)("rejects %s competitions",async status=>expect(await run(await setup({status}))).toMatchObject({ok:false,error:{kind:"competition_closed"}}));
 it("enforces authorization and Division lifecycle",async()=>{expect(await run(await setup({allowed:false}))).toMatchObject({ok:false,error:{kind:"forbidden"}});expect(await run(await setup({division:true,divisionStatus:"inactive"}))).toMatchObject({ok:false,error:{kind:"invalid_scope"}});});
 it("rejects missing and withdrawn entries",async()=>{let x=await setup();expect(await run(x,"missing")).toMatchObject({ok:false,error:{kind:"not_found"}});x=await setup({entryStatus:"withdrawn",active:3});expect(await run(x)).toMatchObject({ok:false,error:{kind:"entry_inactive"}});});
 it("rejects unsupported engines, invalid seeds, and entrant count drift",async()=>{expect(await run(await setup({engine:false}))).toMatchObject({ok:false,error:{kind:"unsupported_format"}});expect(await run(await setup(),"entry-1",3)).toMatchObject({ok:false,error:{kind:"invalid_seed"}});expect(await run(await setup({active:3}))).toMatchObject({ok:false,error:{kind:"entrant_set_changed"}});});
 it("persists a durable partial assignment and emits one non-PII event",async()=>{const x=await setup();const result=await run(x);expect(result).toMatchObject({ok:true,value:{competitionFormatId:"format",competitionEntryId:"entry-1",seedNumber:1,version:1}});expect((await x.assignments.listByFormat(id<"CompetitionFormat">("format")))).toMatchObject({ok:true,value:[{seedNumber:1}]});expect(x.published.events).toHaveLength(1);});
 it("rejects duplicate seed and duplicate entry",async()=>{const x=await setup();expect((await run(x)).ok).toBe(true);expect(await run(x,"entry-2",1)).toMatchObject({ok:false,error:{kind:"seed_already_assigned"}});expect(await run(x,"entry-1",2)).toMatchObject({ok:false,error:{kind:"entry_already_assigned"}});});
});
