import {describe,expect,it} from "vitest";import {ActivateCompetition,ActivateEvent,ActivateStage,CancelCompetition,CancelContest,CancelEvent,CancelStage,CompleteCompetition,CompleteContest,CompleteEvent,CompleteStage,DeactivateDivision,ReactivateDivision,ScheduleContest,StartContest} from "@app/use-cases/manage-competition-lifecycle";import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";import {FakeClock,FakeIdGenerator,InMemoryCompetitionRepository,InMemoryContestRepository,InMemoryDivisionRepository,InMemoryEventPublisher,InMemoryEventRepository,InMemoryStageRepository} from "@adapters";import type {Competition,Contest,Division,Event,Stage} from "@domain/competition/competition.types";import type {Id,ISODateString} from "@shared/kernel";
const NOW="2026-09-12T10:00:00.000Z" as ISODateString,id=<T extends string>(x:string)=>x as Id<T>;type Options={allowed?:boolean,eventStatus?:Event["status"];competitionStatus?:Competition["status"];divisionStatus?:Division["status"];stageStatus?:Stage["status"];contestStatus?:Contest["status"]};
async function setup(o:Options={}){const eventRepository=new InMemoryEventRepository(),competitionRepository=new InMemoryCompetitionRepository(),divisionRepository=new InMemoryDivisionRepository(),stageRepository=new InMemoryStageRepository(),contestRepository=new InMemoryContestRepository(),domainEvents=new InMemoryEventPublisher(),calls:string[]=[];const authorization={execute:async(i:{organizationId:string})=>{calls.push(i.organizationId);return{ok:true as const,value:{allowed:o.allowed??true}};}} as unknown as AuthorizeOrganizationPermission;const event:Event={id:id<"Event">("event"),organizationId:id<"Organization">("owning-org"),name:"Games",key:"games",status:o.eventStatus??"draft",startsAt:null,endsAt:null,createdAt:NOW,updatedAt:NOW,version:1 as Event["version"]};const competition:Competition={id:id<"Competition">("competition"),eventId:event.id,sportId:id<"Sport">("sport"),name:"Open",key:"open",status:o.competitionStatus??"draft",createdAt:NOW,updatedAt:NOW,version:1 as Competition["version"]};const division:Division={id:id<"Division">("division"),competitionId:competition.id,name:"U18",key:"u18",status:o.divisionStatus??"active",createdAt:NOW,updatedAt:NOW,version:1 as Division["version"]};const stage:Stage={id:id<"Stage">("stage"),competitionId:competition.id,divisionId:division.id,name:"Final",key:"final",sequence:1,status:o.stageStatus??"pending",createdAt:NOW,updatedAt:NOW,version:1 as Stage["version"]};const contest:Contest={id:id<"Contest">("contest"),stageId:stage.id,sequence:1,status:o.contestStatus??"pending",scheduledAt:o.contestStatus==="scheduled"?NOW:null,createdAt:NOW,updatedAt:NOW,version:1 as Contest["version"]};await eventRepository.create(event);await competitionRepository.create(competition);await divisionRepository.create(division);await stageRepository.create(stage);await contestRepository.create(contest);return{deps:{eventRepository,competitionRepository,divisionRepository,stageRepository,contestRepository,authorization,clock:new FakeClock(NOW),idGenerator:new FakeIdGenerator(Array(40).fill(0).map((_,i)=>`domain-${i}`)),domainEvents},domainEvents,calls};}
const cases=[
 ["ActivateEvent",ActivateEvent,{},"event","active"],["CompleteEvent",CompleteEvent,{eventStatus:"active"},"event","completed"],["CancelEvent",CancelEvent,{},"event","cancelled"],
 ["ActivateCompetition",ActivateCompetition,{},"competition","active"],["CompleteCompetition",CompleteCompetition,{competitionStatus:"active"},"competition","completed"],["CancelCompetition",CancelCompetition,{},"competition","cancelled"],
 ["DeactivateDivision",DeactivateDivision,{},"division","inactive"],["ReactivateDivision",ReactivateDivision,{divisionStatus:"inactive"},"division","active"],
 ["ActivateStage",ActivateStage,{},"stage","active"],["CompleteStage",CompleteStage,{stageStatus:"active"},"stage","completed"],["CancelStage",CancelStage,{},"stage","cancelled"],
 ["ScheduleContest",ScheduleContest,{},"contest","scheduled"],["StartContest",StartContest,{contestStatus:"scheduled"},"contest","in_progress"],["CompleteContest",CompleteContest,{contestStatus:"in_progress"},"contest","completed"],["CancelContest",CancelContest,{},"contest","cancelled"],
] as const;
describe("authorized competition lifecycle commands",()=>{for(const [name,Command,options,aggregate,status] of cases)it(`${name} authorizes, persists, and then emits`,async()=>{const x=await setup(options);const command=new Command(x.deps);const input={actingMembershipId:"membership",aggregateId:aggregate,expectedVersion:1,...(name==="ScheduleContest"?{scheduledAt:NOW}:{})};const result=await command.execute(input);expect(result).toMatchObject({ok:true,value:{[aggregate]:{status,version:2}}});expect(x.calls).toEqual(["owning-org"]);expect(x.domainEvents.events).toHaveLength(1);});
it("derives Contest → Stage → Competition → Event ownership and denies cross-Organization, inactive, or unprivileged actors",async()=>{for(const actor of ["cross-org","inactive","missing-permission"]){const x=await setup({allowed:false});const result=await new CancelContest(x.deps).execute({actingMembershipId:actor,aggregateId:"contest",expectedVersion:1});expect(result).toMatchObject({ok:false,error:{kind:"forbidden"}});expect(x.calls).toEqual(["owning-org"]);expect(x.domainEvents.events).toHaveLength(0);}});
it("returns typed not_found, invalid_transition, schedule validation, and concurrency errors without events",async()=>{const x=await setup({eventStatus:"completed"});expect(await new ActivateEvent(x.deps).execute({actingMembershipId:"m",aggregateId:"missing",expectedVersion:1})).toMatchObject({ok:false,error:{kind:"not_found"}});expect(await new ActivateEvent(x.deps).execute({actingMembershipId:"m",aggregateId:"event",expectedVersion:1})).toMatchObject({ok:false,error:{kind:"invalid_transition"}});expect(await new CancelContest(x.deps).execute({actingMembershipId:"m",aggregateId:"contest",expectedVersion:2})).toMatchObject({ok:false,error:{kind:"concurrency_conflict"}});expect(await new ScheduleContest(x.deps).execute({actingMembershipId:"m",aggregateId:"contest",expectedVersion:1,scheduledAt:"invalid"})).toMatchObject({ok:false,error:{kind:"invalid_schedule_input"}});expect(x.domainEvents.events).toHaveLength(0);});});
