import {describe,expect,it} from "vitest";
import {FakeClock,FakeIdGenerator,InMemoryCompetitionEntryRepository,InMemoryCompetitionFormatRepository,InMemoryCompetitionRepository,InMemoryCompetitionSeedAssignmentRepository,InMemoryCompetitionSeedFinalizer,InMemoryCompetitionStructureMaterializer,InMemoryDivisionRepository,InMemoryEventPublisher,InMemoryEventRepository} from "@adapters";
import {FinalizeCompetitionSeedAssignments} from "@app/use-cases/finalize-competition-seed-assignments";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import {createCompetitionFormat} from "@domain/competition/competition-format";
import {createCompetitionSeedAssignment} from "@domain/competition/competition-seed-assignment";
import {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import {SingleEliminationEngine} from "@domain/competition/single-elimination-engine";
import type {CompetitionEntry} from "@domain/competition/competition-entry.types";
import type {Competition,Event} from "@domain/competition/competition.types";
import type {Id,ISODateString} from "@shared/kernel";
const NOW="2026-09-23T10:00:00.000Z" as ISODateString,id=<T extends string>(x:string)=>x as Id<T>;
async function setup(){const formats=new InMemoryCompetitionFormatRepository(),competitions=new InMemoryCompetitionRepository(),divisions=new InMemoryDivisionRepository(),events=new InMemoryEventRepository(),entries=new InMemoryCompetitionEntryRepository(),materializer=new InMemoryCompetitionStructureMaterializer(),assignments=new InMemoryCompetitionSeedAssignmentRepository(materializer),published=new InMemoryEventPublisher();const event:Event={id:id<"Event">("event"),organizationId:id<"Organization">("org"),name:"Event",key:"event",status:"draft",startsAt:null,endsAt:null,createdAt:NOW,updatedAt:NOW,version:1 as Event["version"]};const competition:Competition={id:id<"Competition">("competition"),eventId:event.id,sportId:id<"Sport">("sport"),name:"Competition",key:"competition",status:"draft",createdAt:NOW,updatedAt:NOW,version:1 as Competition["version"]};await events.create(event);await competitions.create(competition);const made=createCompetitionFormat({id:id<"CompetitionFormat">("format"),competitionId:competition.id,divisionId:null,kind:"single_elimination",now:NOW,domainEventId:"e"});if(!made.ok)throw Error();await formats.create(made.value.format);for(let n=1;n<=2;n++)await entries.create({id:id<"CompetitionEntry">(`entry-${n}`),competitionId:competition.id,divisionId:null,entrantType:"team",athleteProfileId:null,teamId:id<"Team">(`team-${n}`),status:"active",createdAt:NOW,updatedAt:NOW,version:1 as CompetitionEntry["version"]});await materializer.materialize({format:made.value.format,entrantCount:2,stages:[],contests:[],createdAt:NOW});const engines=new CompetitionFormatEngineRegistry();engines.register(new SingleEliminationEngine());const authorization={execute:async()=>({ok:true as const,value:{allowed:true}})} as unknown as AuthorizeOrganizationPermission;const useCase=new FinalizeCompetitionSeedAssignments({competitionFormatRepository:formats,competitionRepository:competitions,divisionRepository:divisions,eventRepository:events,competitionEntryRepository:entries,assignmentRepository:assignments,materializer,finalizer:new InMemoryCompetitionSeedFinalizer(materializer,assignments),engines,authorization,clock:new FakeClock(NOW),idGenerator:new FakeIdGenerator("final"),domainEvents:published});return{useCase,assignments,materializer,entries,published};}
async function assign(x:Awaited<ReturnType<typeof setup>>,entry:number,seed:number){const made=createCompetitionSeedAssignment({id:id<"CompetitionSeedAssignment">(`a-${entry}`),competitionFormatId:id<"CompetitionFormat">("format"),competitionEntryId:id<"CompetitionEntry">(`entry-${entry}`),seedNumber:seed,now:NOW});if(!made.ok)throw Error();return x.assignments.create(made.value);}
const run=(x:Awaited<ReturnType<typeof setup>>)=>x.useCase.execute({actingMembershipId:"membership",competitionFormatId:"format"});
describe("FinalizeCompetitionSeedAssignments",()=>{
 it("rejects zero and partial assignments",async()=>{let x=await setup();expect(await run(x)).toMatchObject({ok:false,error:{kind:"seeding_incomplete"}});x=await setup();await assign(x,1,1);expect(await run(x)).toMatchObject({ok:false,error:{kind:"seeding_incomplete"}});});
 it("finalizes an exact complete seed and entrant set once",async()=>{const x=await setup();await assign(x,1,1);await assign(x,2,2);expect(await run(x)).toMatchObject({ok:true,value:{entrantCount:2,seedCount:2,finalizedAt:NOW}});expect((await x.materializer.findState(id<"CompetitionFormat">("format"))).value).toMatchObject({seedFinalizedAt:NOW});expect(x.published.events).toHaveLength(1);expect(await run(x)).toMatchObject({ok:false,error:{kind:"already_finalized"}});expect((await x.materializer.findState(id<"CompetitionFormat">("format"))).value).toMatchObject({seedFinalizedAt:NOW});});
 it("detects same-count entrant identity drift",async()=>{const x=await setup();await assign(x,1,1);await assign(x,2,2);const old=await x.entries.findById(id<"CompetitionEntry">("entry-2"));if(old.kind!=="found")throw Error();await x.entries.save({...old.competitionEntry,status:"withdrawn",updatedAt:NOW,version:2 as CompetitionEntry["version"]},1);await x.entries.create({...old.competitionEntry,id:id<"CompetitionEntry">("entry-3"),teamId:id<"Team">("team-3"),version:1 as CompetitionEntry["version"]});expect(await run(x)).toMatchObject({ok:false,error:{kind:"entrant_set_changed"}});});
 it("closes assignment persistence after finalization",async()=>{const x=await setup();await assign(x,1,1);await assign(x,2,2);expect((await run(x)).ok).toBe(true);const made=createCompetitionSeedAssignment({id:id<"CompetitionSeedAssignment">("late"),competitionFormatId:id<"CompetitionFormat">("format"),competitionEntryId:id<"CompetitionEntry">("late"),seedNumber:3,now:NOW});if(!made.ok)throw Error();expect(await x.assignments.create(made.value)).toMatchObject({ok:false,error:{kind:"seeding_finalized"}});});
});
