import {describe,expect,it} from "vitest";
import {FakeClock,FakeIdGenerator,InMemoryCompetitionOutcomeFinalizer,InMemoryEventPublisher} from "@adapters";
import {FinalizeCompetitionOutcome} from "@app/use-cases/finalize-competition-outcome";
import {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import {SingleEliminationEngine} from "@domain/competition/single-elimination-engine";
import type {Id} from "@shared/kernel";
const now="2026-09-16T00:00:00.000Z" as const;
function setup(overrides:{authorized?:boolean;formatStatus?:string;kind?:string;competitionStatus?:string;materialized?:boolean;seeded?:boolean;participants?:boolean;divisionValid?:boolean;progression?:number|null}={}){
 const finalizer=new InMemoryCompetitionOutcomeFinalizer(),events=new InMemoryEventPublisher<Record<string,unknown>>(),engines=new CompetitionFormatEngineRegistry();engines.register(new SingleEliminationEngine());
 const format={id:"format-1",competitionId:"competition-1",divisionId:null,kind:overrides.kind??"single_elimination",status:overrides.formatStatus??"active",createdAt:now,updatedAt:now,version:1};
 finalizer.terminalAuthority.set(format.id,{competitionId:format.competitionId,planRef:"contest:final",entrantCount:6,resultId:"11111111-1111-4111-8111-111111111111" as Id<"ContestResult">,winnerEntryId:"winner-entry" as Id<"CompetitionEntry">,loserEntryId:"loser-entry" as Id<"CompetitionEntry">,completed:true,finalized:true,progressionParticipantCount:overrides.progression===undefined?0:overrides.progression});
 const d={formatRepository:{findById:async()=>({kind:"found" as const,competitionFormat:format as never})},competitionRepository:{findById:async()=>({kind:"found" as const,competition:{id:"competition-1",eventId:"event-1",status:overrides.competitionStatus??"active"} as never})},eventRepository:{findById:async()=>({kind:"found" as const,event:{organizationId:"org-1"} as never})},divisionRepository:{findById:async()=>overrides.divisionValid===false?({kind:"not_found" as const}):({kind:"found" as const,division:{id:"division-1",competitionId:"competition-1",status:"active"} as never})},structure:{findState:async()=>({ok:true as const,value:overrides.materialized===false?null:{competitionFormatId:"format-1",entrantCount:6,seedFinalizedAt:overrides.seeded===false?null:now,participantsMaterializedAt:overrides.participants===false?null:now}})},finalizer,engines,authorization:{execute:async()=>({ok:true as const,value:{allowed:overrides.authorized!==false}})},clock:new FakeClock(now),domainEvents:events};
 return{useCase:new FinalizeCompetitionOutcome({...d,idGenerator:new FakeIdGenerator("outcome-test")} as never),finalizer,events,format};
}
describe("FinalizeCompetitionOutcome",()=>{
 it("derives only winner first and loser second from the terminal snapshot",async()=>{const x=setup(),r=await x.useCase.execute({actingMembershipId:"membership-1",competitionFormatId:"format-1"});expect(r.ok).toBe(true);if(!r.ok)return;expect(r.value.placements.map(p=>[p.position,p.competitionEntryId])).toEqual([[1,"winner-entry"],[2,"loser-entry"]]);expect(r.value.placements).toHaveLength(2);expect(r.value.outcome).not.toHaveProperty("athleteProfileId");expect(r.value.placements[0]).not.toHaveProperty("teamId");expect(x.events.events).toHaveLength(1);expect(x.events.events[0]).toMatchObject({type:"competition.outcome_finalized",placementCount:2});});
 it("rejects inactive membership or missing permission",async()=>expect(await setup({authorized:false}).useCase.execute({actingMembershipId:"inactive",competitionFormatId:"format-1"})).toMatchObject({ok:false,error:{kind:"forbidden"}}));
 it.each([{o:{formatStatus:"retired"},kind:"format_inactive"},{o:{kind:"round_robin"},kind:"unsupported_outcome_format"},{o:{materialized:false},kind:"format_not_materialized"},{o:{seeded:false},kind:"seeding_not_finalized"},{o:{participants:false},kind:"participants_not_materialized"},{o:{competitionStatus:"cancelled"},kind:"competition_cancelled"}])("enforces $kind",async({o,kind})=>expect(await setup(o).useCase.execute({actingMembershipId:"membership-1",competitionFormatId:"format-1"})).toMatchObject({ok:false,error:{kind}}));
 it("requires terminal progression and its zero-participant marker",async()=>{expect(await setup({progression:null}).useCase.execute({actingMembershipId:"m",competitionFormatId:"format-1"})).toMatchObject({ok:false,error:{kind:"terminal_result_not_progressed"}});expect(await setup({progression:1}).useCase.execute({actingMembershipId:"m",competitionFormatId:"format-1"})).toMatchObject({ok:false,error:{kind:"invalid_terminal_progression"}});});
 it("is immutable and rejects a second finalization",async()=>{const x=setup();expect((await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format-1"})).ok).toBe(true);expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format-1"})).toMatchObject({ok:false,error:{kind:"competition_outcome_already_finalized"}});expect(x.finalizer.outcomes.get("format-1")?.placements).toHaveLength(2);});
 it("uses captured entry identity without consulting current entry status",async()=>{const x=setup();const r=await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format-1"});expect(r).toMatchObject({ok:true,value:{placements:[{competitionEntryId:"winner-entry"},{competitionEntryId:"loser-entry"}]}});});
});
