import {describe,expect,it} from "vitest";
import {FakeClock,FakeIdGenerator,InMemoryCompetitionEntryRepository,InMemoryCompetitionFormatRepository,InMemoryCompetitionRepository,InMemoryCompetitionStructureMaterializer,InMemoryDivisionRepository,InMemoryEventPublisher,InMemoryEventRepository} from "@adapters";
import {MaterializeCompetitionFormatPlan} from "@app/use-cases/materialize-competition-format-plan";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import {createCompetitionFormat} from "@domain/competition/competition-format";
import {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import type {CompetitionFormatEngine,CompetitionFormatPlanningInput} from "@domain/competition/competition-format-engine";
import {SingleEliminationEngine} from "@domain/competition/single-elimination-engine";
import type {CompetitionEntry} from "@domain/competition/competition-entry.types";
import type {Competition,Division,Event} from "@domain/competition/competition.types";
import type {Id,ISODateString} from "@shared/kernel";
const NOW="2026-09-21T10:00:00.000Z" as ISODateString,id=<T extends string>(x:string)=>x as Id<T>;
async function setup(o:{competitionStatus?:Competition["status"];divisionStatus?:Division["status"];allowed?:boolean;division?:boolean;kind?:"single_elimination"|"round_robin";active?:number;withdrawn?:number;retired?:boolean;engine?:CompetitionFormatEngine}={}){
 const competitionFormatRepository=new InMemoryCompetitionFormatRepository(),competitionRepository=new InMemoryCompetitionRepository(),divisionRepository=new InMemoryDivisionRepository(),eventRepository=new InMemoryEventRepository(),competitionEntryRepository=new InMemoryCompetitionEntryRepository(),materializer=new InMemoryCompetitionStructureMaterializer(),domainEvents=new InMemoryEventPublisher();
 const event:Event={id:id<"Event">("event"),organizationId:id<"Organization">("org"),name:"Event",key:"event",status:"draft",startsAt:null,endsAt:null,createdAt:NOW,updatedAt:NOW,version:1 as Event["version"]};const competition:Competition={id:id<"Competition">("competition"),eventId:event.id,sportId:id<"Sport">("sport"),name:"Competition",key:"competition",status:o.competitionStatus??"draft",createdAt:NOW,updatedAt:NOW,version:1 as Competition["version"]};const division:Division={id:id<"Division">("division"),competitionId:competition.id,name:"Open",key:"open",status:o.divisionStatus??"active",createdAt:NOW,updatedAt:NOW,version:1 as Division["version"]};await eventRepository.create(event);await competitionRepository.create(competition);await divisionRepository.create(division);
 const made=createCompetitionFormat({id:id<"CompetitionFormat">("format"),competitionId:competition.id,divisionId:o.division?division.id:null,kind:o.kind??"single_elimination",now:NOW,domainEventId:"event"});if(!made.ok)throw Error();await competitionFormatRepository.create(made.value.format);if(o.retired)await competitionFormatRepository.save({...made.value.format,status:"retired",version:2 as typeof made.value.format.version},1);
 const total=(o.active??2)+(o.withdrawn??0);for(let n=1;n<=total;n++){const entry:CompetitionEntry={id:id<"CompetitionEntry">(`entry-${n}`),competitionId:competition.id,divisionId:o.division?division.id:null,entrantType:"team",athleteProfileId:null,teamId:id<"Team">(`team-${n}`),status:n<=(o.active??2)?"active":"withdrawn",createdAt:NOW,updatedAt:NOW,version:1 as CompetitionEntry["version"]};await competitionEntryRepository.create(entry);}
 const engines=new CompetitionFormatEngineRegistry();if(o.engine)engines.register(o.engine);else if((o.kind??"single_elimination")==="single_elimination")engines.register(new SingleEliminationEngine());const authorization={execute:async()=>({ok:true as const,value:{allowed:o.allowed??true}})} as unknown as AuthorizeOrganizationPermission;const deps={competitionFormatRepository,competitionRepository,divisionRepository,eventRepository,competitionEntryRepository,materializer,engines,authorization,clock:new FakeClock(NOW),idGenerator:new FakeIdGenerator("mat"),domainEvents};return{useCase:new MaterializeCompetitionFormatPlan(deps),materializer,competitionEntryRepository};
}
describe("MaterializeCompetitionFormatPlan",()=>{
 it.each(["completed","cancelled"] as const)("denies a %s Competition",async status=>{const x=await setup({competitionStatus:status});expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).toMatchObject({ok:false,error:{kind:"competition_closed"}});});
 it("denies retired formats, inactive Divisions, and authorization failures",async()=>{let x=await setup({retired:true});expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).toMatchObject({ok:false,error:{kind:"format_inactive"}});x=await setup({division:true,divisionStatus:"inactive"});expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).toMatchObject({ok:false,error:{kind:"invalid_scope"}});x=await setup({allowed:false});expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).toMatchObject({ok:false,error:{kind:"forbidden"}});});
 it("returns unsupported_format without persistence",async()=>{const x=await setup({kind:"round_robin"});expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).toMatchObject({ok:false,error:{kind:"unsupported_format"}});expect(x.materializer.stages.size).toBe(0);});
 it.each([0,1])("leaves %s active entrants to engine validation",async active=>{const x=await setup({active});expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).toMatchObject({ok:false,error:{kind:"invalid_planning_input"}});});
 it("excludes withdrawn entries and returns mapped durable counts",async()=>{const x=await setup({active:6,withdrawn:3});const result=await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"});expect(result).toMatchObject({ok:true,value:{stageCount:3,contestCount:5}});expect(x.materializer.stages.size).toBe(3);expect(x.materializer.contests.size).toBe(5);expect(new Set([...x.materializer.contests.values()].map(c=>c.stageId).filter(stageId=>!x.materializer.stages.has(stageId))).size).toBe(0);expect(await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).toMatchObject({ok:false,error:{kind:"already_materialized"}});});
 it.each([false,true])("derives the %s scoped count without entrant identities",async division=>{let seen:CompetitionFormatPlanningInput|undefined;const engine:CompetitionFormatEngine={supportedKind:"single_elimination",validate:()=>({ok:true,value:undefined}),plan(input){seen=input;return{ok:true,value:{stages:[{ref:"s",sequence:1,key:"stage"}],contests:[],progressionRules:[]}};}};const x=await setup({division,active:4,engine});expect((await x.useCase.execute({actingMembershipId:"m",competitionFormatId:"format"})).ok).toBe(true);expect(seen).toEqual({formatKind:"single_elimination",entrantCount:4,scope:{competitionRef:"competition",divisionRef:division?"division":null}});expect(Object.keys(seen??{}).sort()).toEqual(["entrantCount","formatKind","scope"]);});
});
