import type {ContestParticipantRepository,ContestParticipantPersistenceError} from "@app/contracts/contest-participant-repository";
import type {Sql} from "@adapters/persistence/pg/connection";
import {neutralDetail,pgErrorInfo} from "@adapters/persistence/pg/errors";
import type {ContestParticipant} from "@domain/competition/contest-participant";
import type {Result} from "@shared/kernel";
type Row={id:string;contest_id:string;position:number;competition_entry_id:string;source_type:string;source_seed_number:number;version:number;created_at:string|Date};
const map=(r:Row):ContestParticipant=>({id:r.id as never,contestId:r.contest_id as never,position:Number(r.position),competitionEntryId:r.competition_entry_id as never,sourceType:"seed",sourceSeedNumber:Number(r.source_seed_number),version:Number(r.version) as never,createdAt:new Date(r.created_at).toISOString() as never});
const bad=(kind:ContestParticipantPersistenceError["kind"],detail?:string):Result<never,ContestParticipantPersistenceError>=>({ok:false,error:{kind,...(detail?{detail}:{})}});
export class PgContestParticipantRepository implements ContestParticipantRepository{constructor(private readonly sql:Sql){}private async one(q:Promise<Row[]>){try{const r=(await q)[0];return r?{kind:"found" as const,participant:map(r)}:{kind:"not_found" as const};}catch(e){return{kind:"unavailable" as const,detail:neutralDetail(e)};}}async findById(id:string){return this.one(this.sql<Row[]>`SELECT * FROM contest_participants WHERE id=${id}`);}async findByContestAndPosition(id:string,p:number){return this.one(this.sql<Row[]>`SELECT * FROM contest_participants WHERE contest_id=${id} AND position=${p}`);}async listByContest(id:string){try{return{ok:true as const,value:(await this.sql<Row[]>`SELECT * FROM contest_participants WHERE contest_id=${id} ORDER BY position`).map(map)};}catch(e){return bad("unavailable",neutralDetail(e));}}async listByCompetitionFormat(id:string){try{return{ok:true as const,value:(await this.sql<Row[]>`SELECT cp.* FROM contest_participants cp JOIN contests c ON c.id=cp.contest_id JOIN competition_stages s ON s.id=c.stage_id WHERE s.competition_format_id=${id} ORDER BY c.id,cp.position`).map(map)};}catch(e){return bad("unavailable",neutralDetail(e));}}async create(x:ContestParticipant){try{await this.sql`INSERT INTO contest_participants(id,contest_id,position,competition_entry_id,source_type,source_seed_number,version,created_at) VALUES(${x.id},${x.contestId},${x.position},${x.competitionEntryId},${x.sourceType},${x.sourceSeedNumber},${x.version},${x.createdAt})`;return{ok:true as const,value:x};}catch(e){const p=pgErrorInfo(e);if(p?.constraint==="contest_participants_pkey")return bad("duplicate_id");if(p?.constraint==="contest_participants_contest_position_unique")return bad("position_occupied");if(p?.constraint==="contest_participants_contest_entry_unique")return bad("entry_already_present");if(p?.code==="23503")return bad("parent_not_found");return bad("unavailable",neutralDetail(e));}}}
