import type {CompetitionOutcomeFinalizer,CompetitionOutcomeFinalizationError,CompetitionOutcomeLookup,CompetitionOutcomeRepository} from "@app/contracts";
import type {Sql} from "@adapters/persistence/pg/connection";
import {neutralDetail,pgErrorInfo} from "@adapters/persistence/pg/errors";
import type {CompetitionOutcome,CompetitionPlacement} from "@domain/competition/competition-outcome";
import type {AggregateVersion} from "@domain/aggregate";
import type {Id,ISODateString,Result} from "@shared/kernel";
type Row=Record<string,unknown>;const iso=(x:unknown)=>(x instanceof Date?x.toISOString():new Date(String(x)).toISOString()) as ISODateString;
const outcome=(r:Row):CompetitionOutcome=>({id:r.id as Id<"CompetitionOutcome">,competitionFormatId:r.competition_format_id as Id<"CompetitionFormat">,status:"finalized",finalizedAt:iso(r.finalized_at),createdAt:iso(r.created_at),version:r.version as AggregateVersion});
const placement=(r:Row):CompetitionPlacement=>({id:r.id as Id<"CompetitionPlacement">,competitionOutcomeId:r.competition_outcome_id as Id<"CompetitionOutcome">,competitionEntryId:r.competition_entry_id as Id<"CompetitionEntry">,position:Number(r.position),sourceContestResultId:r.source_contest_result_id as Id<"ContestResult">,createdAt:iso(r.created_at),version:r.version as AggregateVersion});
const bad=(kind:CompetitionOutcomeFinalizationError["kind"],detail?:string):Result<never,CompetitionOutcomeFinalizationError>=>({ok:false,error:{kind,...(detail?{detail}:{})}});class Expected extends Error{constructor(readonly kind:CompetitionOutcomeFinalizationError["kind"]){super(kind);}}
export class PgCompetitionOutcomeFinalizer implements CompetitionOutcomeFinalizer,CompetitionOutcomeRepository{constructor(private readonly sql:Sql){}
 async findByFormatId(id:Id<"CompetitionFormat">):Promise<CompetitionOutcomeLookup>{try{const rows=await this.sql<Row[]>`SELECT * FROM competition_outcomes WHERE competition_format_id=${id}`;if(!rows[0])return{kind:"not_found"};const outcomeId=String(rows[0].id);const ps=await this.sql<Row[]>`SELECT * FROM competition_placements WHERE competition_outcome_id=${outcomeId}`;return{kind:"found",outcome:outcome(rows[0]),placements:ps.map(placement).sort((a,b)=>a.position-b.position)};}catch(e){return{kind:"unavailable",detail:neutralDetail(e)};}}
 async finalize(i:Parameters<CompetitionOutcomeFinalizer["finalize"]>[0]){try{return await this.sql.begin(async tx=>{
  const [format]=await tx<Row[]>`SELECT f.id,f.competition_id,f.division_id,f.status,f.kind,m.entrant_count,m.seed_finalized_at,m.participants_materialized_at FROM competition_formats f LEFT JOIN competition_format_materializations m ON m.competition_format_id=f.id WHERE f.id=${i.competitionFormatId} FOR UPDATE OF f`;
  if(!format||format.competition_id!==i.competitionId||Number(format.entrant_count)!==i.expectedEntrantCount)throw new Expected("cross_format_authority");
  if((await tx<Row[]>`SELECT id FROM competition_outcomes WHERE competition_format_id=${i.competitionFormatId}`)[0])throw new Expected("competition_outcome_already_finalized");
  const divisionId=format.division_id===null?null:String(format.division_id);const contests=await tx<Row[]>`SELECT c.id,c.status,c.plan_ref FROM contests c JOIN competition_stages s ON s.id=c.stage_id WHERE s.competition_format_id=${i.competitionFormatId} AND s.competition_id=${i.competitionId} AND s.division_id IS NOT DISTINCT FROM ${divisionId} AND c.plan_ref=${i.terminalPlanRef} FOR UPDATE OF c`;
  if(contests.length!==1)throw new Expected("terminal_contest_not_found");const contest=contests[0]!;
  const contestId=String(contest.id);const results=await tx<Row[]>`SELECT id,status,finalized_at FROM contest_results WHERE contest_id=${contestId} FOR UPDATE`;
  if(contest.status!=="completed"||results.length!==1||results[0]!.status!=="finalized"||!results[0]!.finalized_at)throw new Expected("terminal_result_not_finalized");const result=results[0]!;
  const resultId=String(result.id);const outcomes=await tx<Row[]>`SELECT o.outcome,p.contest_id,p.competition_entry_id,e.competition_id,e.division_id FROM contest_result_outcomes o JOIN contest_participants p ON p.id=o.contest_participant_id JOIN competition_entries e ON e.id=p.competition_entry_id WHERE o.contest_result_id=${resultId} FOR SHARE OF o,p,e`;
  const winner=outcomes.find(x=>x.outcome==="winner"),loser=outcomes.find(x=>x.outcome==="loser");if(outcomes.length!==2||!winner||!loser||winner.contest_id!==contest.id||loser.contest_id!==contest.id||winner.competition_entry_id===loser.competition_entry_id)throw new Expected("malformed_terminal_result");if(outcomes.some(x=>x.competition_id!==i.competitionId||x.division_id!==format.division_id))throw new Expected("cross_format_authority");
  const progressions=await tx<Row[]>`SELECT competition_format_id,participant_count FROM contest_result_progressions WHERE contest_result_id=${resultId} FOR SHARE`;if(!progressions[0])throw new Expected("terminal_result_not_progressed");if(progressions[0].competition_format_id!==i.competitionFormatId)throw new Expected("cross_format_authority");if(Number(progressions[0].participant_count)!==0)throw new Expected("invalid_terminal_progression");
  const [orow]=await tx<Row[]>`INSERT INTO competition_outcomes(id,competition_format_id,status,finalized_at,created_at,version) VALUES(${i.outcomeId},${i.competitionFormatId},'finalized',${i.finalizedAt},${i.finalizedAt},1) RETURNING *`;
  const winnerEntryId=String(winner.competition_entry_id),loserEntryId=String(loser.competition_entry_id);const ps=await tx<Row[]>`INSERT INTO competition_placements(id,competition_outcome_id,competition_entry_id,position,source_contest_result_id,created_at,version) VALUES (${i.firstPlacementId},${i.outcomeId},${winnerEntryId},1,${resultId},${i.finalizedAt},1),(${i.secondPlacementId},${i.outcomeId},${loserEntryId},2,${resultId},${i.finalizedAt},1) RETURNING *`;
  return{ok:true as const,value:{outcome:outcome(orow!),placements:ps.map(placement).sort((a,b)=>a.position-b.position)}};
 });}catch(e){if(e instanceof Expected)return bad(e.kind);const p=pgErrorInfo(e);if(p?.constraint==="competition_outcomes_competition_format_id_key")return bad("competition_outcome_already_finalized");return bad("unavailable",neutralDetail(e));}}
}
