import type {CompetitionSeedAssignmentLookup,CompetitionSeedAssignmentPersistenceError,CompetitionSeedAssignmentRepository} from "@app/contracts";
import type {Sql} from "@adapters/persistence/pg/connection";
import {isForeignKeyViolation,isUniqueViolation,neutralDetail,pgErrorInfo} from "@adapters/persistence/pg/errors";
import type {CompetitionSeedAssignment} from "@domain/competition/competition-seed-assignment";
import type {AggregateVersion} from "@domain/aggregate";
import type {Id,ISODateString,Result} from "@shared/kernel";
type Row=Record<string,unknown>;const map=(r:Row|undefined):CompetitionSeedAssignment=>({id:r?.id as Id<"CompetitionSeedAssignment">,competitionFormatId:r?.competition_format_id as Id<"CompetitionFormat">,competitionEntryId:r?.competition_entry_id as Id<"CompetitionEntry">,seedNumber:Number(r?.seed_number),version:Number(r?.version) as AggregateVersion,createdAt:new Date(String(r?.created_at)).toISOString() as ISODateString});
const bad=(kind:CompetitionSeedAssignmentPersistenceError["kind"],detail?:string):Result<never,CompetitionSeedAssignmentPersistenceError>=>({ok:false,error:{kind,...(detail?{detail}:{})}});const lookup=(r:Row[]):CompetitionSeedAssignmentLookup=>r[0]?{kind:"found",assignment:map(r[0])}:{kind:"not_found"};
export class PgCompetitionSeedAssignmentRepository implements CompetitionSeedAssignmentRepository{constructor(private readonly sql:Sql){}async findById(id:Id<"CompetitionSeedAssignment">){try{return lookup(await this.sql<Row[]>`SELECT * FROM competition_seed_assignments WHERE id=${id}`);}catch(e){return{kind:"unavailable" as const,detail:neutralDetail(e)};}}async findByFormatAndSeed(f:Id<"CompetitionFormat">,s:number){try{return lookup(await this.sql<Row[]>`SELECT * FROM competition_seed_assignments WHERE competition_format_id=${f} AND seed_number=${s}`);}catch(e){return{kind:"unavailable" as const,detail:neutralDetail(e)};}}async findByFormatAndEntry(f:Id<"CompetitionFormat">,e:Id<"CompetitionEntry">){try{return lookup(await this.sql<Row[]>`SELECT * FROM competition_seed_assignments WHERE competition_format_id=${f} AND competition_entry_id=${e}`);}catch(x){return{kind:"unavailable" as const,detail:neutralDetail(x)};}}async listByFormat(f:Id<"CompetitionFormat">){try{return{ok:true as const,value:(await this.sql<Row[]>`SELECT * FROM competition_seed_assignments WHERE competition_format_id=${f} ORDER BY seed_number`).map(map)};}catch(e){return bad("unavailable",neutralDetail(e));}}async create(x:CompetitionSeedAssignment){try{const r=await this.sql<Row[]>`INSERT INTO competition_seed_assignments(id,competition_format_id,competition_entry_id,seed_number,version,created_at) VALUES(${x.id},${x.competitionFormatId},${x.competitionEntryId},${x.seedNumber},${x.version},${x.createdAt}) RETURNING *`;return{ok:true as const,value:map(r[0])};}catch(e){const i=pgErrorInfo(e);if(isUniqueViolation(i)){if(i?.constraint==="competition_seed_assignments_format_seed_unique")return bad("seed_already_assigned");if(i?.constraint==="competition_seed_assignments_format_entry_unique")return bad("entry_already_assigned");return bad("duplicate_id");}if(isForeignKeyViolation(i))return bad("parent_not_found");return bad("unavailable",neutralDetail(e));}}}
