import type {InitialContestParticipantMaterializer,InitialParticipantMaterializationError} from "@app/contracts/initial-contest-participant-materializer";
import type {Sql} from "@adapters/persistence/pg/connection";
import {neutralDetail} from "@adapters/persistence/pg/errors";
import type {ContestParticipant} from "@domain/competition/contest-participant";
import type {Result} from "@shared/kernel";
const bad=(kind:InitialParticipantMaterializationError["kind"],detail?:string):Result<never,InitialParticipantMaterializationError>=>({ok:false,error:{kind,...(detail?{detail}:{})}});
class Expected extends Error{constructor(readonly kind:InitialParticipantMaterializationError["kind"]){super(kind);}}
export class PgInitialContestParticipantMaterializer implements InitialContestParticipantMaterializer{constructor(private readonly sql:Sql){}async materialize(i:Parameters<InitialContestParticipantMaterializer["materialize"]>[0]){try{const value=await this.sql.begin(async tx=>{
 const states=await tx<{seed_finalized_at:string|null;participants_materialized_at:string|null;entrant_count:number}[]>`SELECT seed_finalized_at,participants_materialized_at,entrant_count FROM competition_format_materializations WHERE competition_format_id=${i.competitionFormatId} FOR UPDATE`;const state=states[0];if(!state?.seed_finalized_at)throw new Expected("seeding_not_finalized");if(state.participants_materialized_at)throw new Expected("participants_already_materialized");if(Number(state.entrant_count)!==i.expectedEntrantCount)throw new Expected("invalid_finalized_seed_map");
 const assignments=await tx<{seed_number:number;competition_entry_id:string}[]>`SELECT seed_number,competition_entry_id FROM competition_seed_assignments WHERE competition_format_id=${i.competitionFormatId}`;if(assignments.length!==i.expectedEntrantCount||i.placements.length!==i.expectedEntrantCount)throw new Expected("invalid_finalized_seed_map");const seeds=new Map(assignments.map(x=>[Number(x.seed_number),x.competition_entry_id]));if(new Set(i.placements.map(x=>x.participant.sourceSeedNumber)).size!==i.placements.length||i.placements.some(x=>seeds.get(x.participant.sourceSeedNumber)!==x.participant.competitionEntryId))throw new Expected("invalid_finalized_seed_map");
 const refs=[...new Set(i.placements.map(x=>x.contestPlanRef))];const contests=refs.length?await tx<{id:string;plan_ref:string;status:string}[]>`SELECT c.id,c.plan_ref,c.status FROM contests c JOIN competition_stages s ON s.id=c.stage_id WHERE s.competition_format_id=${i.competitionFormatId} AND c.plan_ref IN ${tx(refs)}`:[];const mapped=new Map(contests.map(x=>[x.plan_ref,x]));if(mapped.size!==refs.length)throw new Expected("invalid_contest_mapping");if(contests.some(x=>x.status!=="pending"&&x.status!=="scheduled"))throw new Expected("invalid_contest_state");
 const made:ContestParticipant[]=[];for(const x of i.placements){const contest=mapped.get(x.contestPlanRef)!;await tx`INSERT INTO contest_participants(id,contest_id,position,competition_entry_id,source_type,source_seed_number,version,created_at) VALUES(${x.participant.id},${contest.id},${x.participant.position},${x.participant.competitionEntryId},${x.participant.sourceType},${x.participant.sourceSeedNumber},${x.participant.version},${x.participant.createdAt})`;made.push({...x.participant,contestId:contest.id as never});}await tx`UPDATE competition_format_materializations SET participants_materialized_at=${i.materializedAt} WHERE competition_format_id=${i.competitionFormatId}`;return made;
 });return{ok:true as const,value};}catch(e){return e instanceof Expected?bad(e.kind):bad("unavailable",neutralDetail(e));}}}
