import type { OrganizationMembershipLookupResult, OrganizationMembershipPersistenceError, OrganizationMembershipRepository } from "@app/contracts/organization-membership-repository";
import type { Sql } from "@adapters/persistence/pg/connection";
import { isUniqueViolation, neutralDetail, pgErrorInfo } from "@adapters/persistence/pg/errors";
import type { AggregateVersion } from "@domain/aggregate";
import { isValidOrganizationMembershipState } from "@domain/organization/organization-membership";
import type { OrganizationMembership } from "@domain/organization/organization-membership.types";
import type { Id, ISODateString, Result } from "@shared/kernel";
interface Row { id:string; organization_id:string; person_id:string; status:string; version:number; created_at:Date; updated_at:Date; }
const columns="id,organization_id,person_id,status,version,created_at,updated_at";
export class PgOrganizationMembershipRepository implements OrganizationMembershipRepository {
  constructor(private readonly sql:Sql){}
  async create(value:OrganizationMembership):Promise<Result<OrganizationMembership,OrganizationMembershipPersistenceError>> { if(value.version!==1||!isValidOrganizationMembershipState(value))return bad("A new membership must be valid at version 1."); try{await this.sql`INSERT INTO organization_memberships (id,organization_id,person_id,status,version,created_at,updated_at) VALUES (${value.id},${value.organizationId},${value.personId},${value.status},${value.version},${value.createdAt},${value.updatedAt})`;return {ok:true,value:{...value}};}catch(error){const info=pgErrorInfo(error);if(isUniqueViolation(info)&&info)return {ok:false,error:{kind:info.constraint.includes("pkey")?"duplicate_membership_id":"duplicate_membership"}};return {ok:false,error:{kind:"unavailable",detail:neutralDetail(error)}};}}
  async save(value:OrganizationMembership,expectedVersion:AggregateVersion):Promise<Result<OrganizationMembership,OrganizationMembershipPersistenceError>> { if(!isValidOrganizationMembershipState(value)||value.version!==expectedVersion+1)return bad("A save must persist the domain-supplied N+1 version."); try{const rows=await this.sql<Row[]>`UPDATE organization_memberships SET status=${value.status},version=${value.version},updated_at=${value.updatedAt} WHERE id=${value.id} AND version=${expectedVersion} AND organization_id=${value.organizationId} AND person_id=${value.personId} AND created_at=${value.createdAt} RETURNING id,organization_id,person_id,status,version,created_at,updated_at`;if(rows[0]){const mapped=map(rows[0]);return mapped?{ok:true,value:mapped}:bad("Updated membership is malformed.");}const exists=await this.sql<{version:number}[]>`SELECT version FROM organization_memberships WHERE id=${value.id}`;return {ok:false,error:{kind:exists[0]?"concurrency_conflict":"not_found"}};}catch(error){return {ok:false,error:{kind:"unavailable",detail:neutralDetail(error)}};}}
  findById(id:Id<"OrganizationMembership">):Promise<OrganizationMembershipLookupResult>{return this.read(()=>this.sql.unsafe<Row[]>(`SELECT ${columns} FROM organization_memberships WHERE id=$1 LIMIT 1`,[id]));}
  findByOrganizationAndPerson(organizationId:Id<"Organization">,personId:Id<"Person">):Promise<OrganizationMembershipLookupResult>{return this.read(()=>this.sql.unsafe<Row[]>(`SELECT ${columns} FROM organization_memberships WHERE organization_id=$1 AND person_id=$2 LIMIT 1`,[organizationId,personId]));}
  async findActiveByPerson(personId:Id<"Person">){try{const rows=await this.sql.unsafe<Row[]>(`SELECT ${columns} FROM organization_memberships WHERE person_id=$1 AND status='active' ORDER BY organization_id,id`,[personId]);const memberships=[];for(const row of rows){const membership=map(row);if(!membership)return {kind:"invalid_persistence_state" as const,detail:"Stored membership violates persistence invariants."};memberships.push(membership);}return {kind:"found" as const,memberships};}catch(error){return {kind:"unavailable" as const,detail:neutralDetail(error)};}}
  private async read(run:()=>Promise<Row[]>):Promise<OrganizationMembershipLookupResult>{try{const row=(await run())[0];if(!row)return {kind:"not_found"};const membership=map(row);return membership?{kind:"found",membership}:{kind:"invalid_persistence_state",detail:"Stored membership violates persistence invariants."};}catch(error){return {kind:"unavailable",detail:neutralDetail(error)};}}
}
function map(row:Row):OrganizationMembership|null{if(!(row.created_at instanceof Date)||!(row.updated_at instanceof Date))return null;const value={id:row.id as Id<"OrganizationMembership">,organizationId:row.organization_id as Id<"Organization">,personId:row.person_id as Id<"Person">,status:row.status as OrganizationMembership["status"],version:row.version as AggregateVersion,createdAt:row.created_at.toISOString() as ISODateString,updatedAt:row.updated_at.toISOString() as ISODateString};return isValidOrganizationMembershipState(value)?value:null;}
function bad(detail:string):Result<never,OrganizationMembershipPersistenceError>{return {ok:false,error:{kind:"invalid_persistence_state",detail}};}
