import type { OrganizationTrustLookup,OrganizationTrustPersistenceError,OrganizationTrustRepository } from "@app/contracts";
import type { Sql } from "@adapters/persistence/pg/connection";
import { isUniqueViolation,neutralDetail,pgErrorInfo } from "@adapters/persistence/pg/errors";
import type { AggregateVersion } from "@domain/aggregate";
import { isValidOrganizationTrustState } from "@domain/organization/organization-trust";
import type { OrganizationTrust,OrganizationTrustScope } from "@domain/organization/organization-trust.types";
import type { Id,ISODateString,Result } from "@shared/kernel";
interface Row{id:string;issuer_organization_id:string;subject_organization_id:string;scope:string;status:string;issued_at:Date;revoked_at:Date|null;expires_at:Date|null;created_at:Date;updated_at:Date;version:number;}
export class PgOrganizationTrustRepository implements OrganizationTrustRepository{
 constructor(private sql:Sql){}
 async create(v:OrganizationTrust){if(v.version!==1||!isValidOrganizationTrustState(v))return fail("invalid_persistence_state");try{return await this.sql.begin(async raw=>{const tx=raw as unknown as Sql;const key=JSON.stringify([v.issuerOrganizationId,v.subjectOrganizationId,v.scope]);await tx`SELECT pg_advisory_xact_lock(hashtextextended(${key},0))`;const existing=await tx<{id:string}[]>`SELECT id FROM organization_trusts WHERE issuer_organization_id=${v.issuerOrganizationId} AND subject_organization_id=${v.subjectOrganizationId} AND scope=${v.scope} AND status='active' AND issued_at<=${v.issuedAt} AND (expires_at IS NULL OR expires_at>${v.issuedAt}) LIMIT 1`;if(existing[0])return fail("duplicate_effective_trust");try{await tx`INSERT INTO organization_trusts(id,issuer_organization_id,subject_organization_id,scope,status,issued_at,revoked_at,expires_at,created_at,updated_at,version) VALUES(${v.id},${v.issuerOrganizationId},${v.subjectOrganizationId},${v.scope},${v.status},${v.issuedAt},${v.revokedAt??null},${v.expiresAt??null},${v.createdAt},${v.updatedAt},${v.version})`;return ok(v);}catch(e){return isUniqueViolation(pgErrorInfo(e))?fail("duplicate_id"):unavailable(e);}});}catch(e){return unavailable(e);}}
 async save(v:OrganizationTrust,e:AggregateVersion){if(!isValidOrganizationTrustState(v)||v.version!==e+1)return fail("invalid_persistence_state");try{const rows=await this.sql<Row[]>`UPDATE organization_trusts SET status=${v.status},revoked_at=${v.revokedAt??null},updated_at=${v.updatedAt},version=${v.version} WHERE id=${v.id} AND version=${e} AND issuer_organization_id=${v.issuerOrganizationId} AND subject_organization_id=${v.subjectOrganizationId} AND scope=${v.scope} AND issued_at=${v.issuedAt} AND created_at=${v.createdAt} RETURNING *`;if(rows[0]){const x=map(rows[0]);return x?ok(x):fail("invalid_persistence_state");}const found=await this.sql<{id:string}[]>`SELECT id FROM organization_trusts WHERE id=${v.id}`;return fail(found[0]?"concurrency_conflict":"not_found");}catch(error){return unavailable(error);}}
 findById(id:Id<"OrganizationTrust">){return this.read(()=>this.sql<Row[]>`SELECT * FROM organization_trusts WHERE id=${id} LIMIT 1`);}
 findEffectiveDirectTrust(i:Id<"Organization">,s:Id<"Organization">,scope:OrganizationTrustScope,at:ISODateString){return this.read(()=>this.sql<Row[]>`SELECT * FROM organization_trusts WHERE issuer_organization_id=${i} AND subject_organization_id=${s} AND scope=${scope} AND status='active' AND issued_at<=${at} AND (expires_at IS NULL OR expires_at>${at}) ORDER BY issued_at DESC LIMIT 1`);}
 findEffectiveIncomingTrust(s:Id<"Organization">,scope:OrganizationTrustScope,at:ISODateString){return this.read(()=>this.sql<Row[]>`SELECT * FROM organization_trusts WHERE subject_organization_id=${s} AND scope=${scope} AND status='active' AND issued_at<=${at} AND (expires_at IS NULL OR expires_at>${at}) ORDER BY issued_at DESC LIMIT 1`);}
 private async read(run:()=>Promise<Row[]>):Promise<OrganizationTrustLookup>{try{const r=(await run())[0];if(!r)return {kind:"not_found"};const trust=map(r);return trust?{kind:"found",trust}:{kind:"invalid_persistence_state"};}catch(e){return {kind:"unavailable",detail:neutralDetail(e)};}}
}
function map(r:Row):OrganizationTrust|null{if(![r.issued_at,r.created_at,r.updated_at].every(x=>x instanceof Date)||r.revoked_at!==null&&!(r.revoked_at instanceof Date)||r.expires_at!==null&&!(r.expires_at instanceof Date))return null;const x:OrganizationTrust={id:r.id as Id<"OrganizationTrust">,issuerOrganizationId:r.issuer_organization_id as Id<"Organization">,subjectOrganizationId:r.subject_organization_id as Id<"Organization">,scope:r.scope as OrganizationTrustScope,status:r.status as OrganizationTrust["status"],issuedAt:r.issued_at.toISOString() as ISODateString,...(r.revoked_at?{revokedAt:r.revoked_at.toISOString() as ISODateString}:{}),...(r.expires_at?{expiresAt:r.expires_at.toISOString() as ISODateString}:{}),createdAt:r.created_at.toISOString() as ISODateString,updatedAt:r.updated_at.toISOString() as ISODateString,version:r.version as AggregateVersion};return isValidOrganizationTrustState(x)?x:null;}
function ok(v:OrganizationTrust):Result<OrganizationTrust,OrganizationTrustPersistenceError>{return {ok:true,value:v};}function fail(kind:OrganizationTrustPersistenceError["kind"]):Result<never,OrganizationTrustPersistenceError>{return {ok:false,error:{kind}};}function unavailable(e:unknown):Result<never,OrganizationTrustPersistenceError>{return {ok:false,error:{kind:"unavailable",detail:neutralDetail(e)}};}
