import type {TournamentContestView,TournamentOperationsReader,TournamentOperationsSnapshot,TournamentParticipantView,TournamentResultView} from "@app/contracts/tournament-operations-reader";
import type {Sql} from "@adapters/persistence/pg/connection";
import {SingleEliminationEngine} from "@domain/competition/single-elimination-engine";

type Head={format_id:string;competition_id:string;division_id:string|null;kind:string;format_status:string;event_id:string;sport_id:string;competition_status:string;organization_id:string;entrant_count:number|null;seed_finalized_at:Date|null};
type Seed={seed_number:number;competition_entry_id:string};
type Structure={stage_id:string;stage_sequence:number;stage_status:string;stage_division_id:string|null;contest_id:string|null;plan_ref:string|null;contest_sequence:number|null;contest_status:string|null;scheduled_at:Date|null};
type Participant={id:string;contest_id:string;position:number;competition_entry_id:string;source_type:"seed"|"contest_outcome";source_seed_number:number|null;source_contest_result_id:string|null;source_outcome:"winner"|"loser"|null};
type ResultRow={id:string;contest_id:string;status:string;finalized_at:Date|null;winner_entry_id:string|null;loser_entry_id:string|null;participant_count:number|null};
type OutcomeRow={outcome_id:string;finalized_at:Date;position:number;competition_entry_id:string;source_contest_result_id:string};
const iso=(d:Date)=>d.toISOString();

export class PgTournamentOperationsReader implements TournamentOperationsReader{
 constructor(private readonly sql:Sql){}
 async read(id:string){
  if(!id)return{kind:"not_found" as const};
  try{return await this.sql.begin("isolation level repeatable read read only",async transaction=>{
   const tx=transaction as unknown as Sql;
   const heads=await tx<Head[]>`SELECT f.id format_id,f.competition_id,f.division_id,f.kind,f.status format_status,c.event_id,c.sport_id,c.status competition_status,e.organization_id,m.entrant_count,m.seed_finalized_at FROM competition_formats f JOIN competitions c ON c.id=f.competition_id JOIN events e ON e.id=c.event_id LEFT JOIN competition_format_materializations m ON m.competition_format_id=f.id WHERE f.id=${id}`;
   const h=heads[0];if(!h)return{kind:"not_found" as const};if(h.kind!=="single_elimination")return{kind:"unsupported_operations_format" as const};
   const seeds=await tx<Seed[]>`SELECT seed_number,competition_entry_id FROM competition_seed_assignments WHERE competition_format_id=${id} ORDER BY seed_number`;
   const structures=await tx<Structure[]>`SELECT s.id stage_id,s.sequence stage_sequence,s.status stage_status,s.division_id stage_division_id,c.id contest_id,c.plan_ref,c.sequence contest_sequence,c.status contest_status,c.scheduled_at FROM competition_stages s LEFT JOIN contests c ON c.stage_id=s.id WHERE s.competition_format_id=${id} ORDER BY s.sequence,c.sequence`;
   const participants=await tx<Participant[]>`SELECT p.id,p.contest_id,p.position,p.competition_entry_id,p.source_type,p.source_seed_number,p.source_contest_result_id,p.source_outcome FROM contest_participants p JOIN contests c ON c.id=p.contest_id JOIN competition_stages s ON s.id=c.stage_id WHERE s.competition_format_id=${id} ORDER BY p.contest_id,p.position`;
   const results=await tx<ResultRow[]>`SELECT r.id,r.contest_id,r.status,r.finalized_at,w.competition_entry_id winner_entry_id,l.competition_entry_id loser_entry_id,g.participant_count FROM contest_results r JOIN contests c ON c.id=r.contest_id JOIN competition_stages s ON s.id=c.stage_id LEFT JOIN contest_result_outcomes wo ON wo.contest_result_id=r.id AND wo.outcome='winner' LEFT JOIN contest_participants w ON w.id=wo.contest_participant_id LEFT JOIN contest_result_outcomes lo ON lo.contest_result_id=r.id AND lo.outcome='loser' LEFT JOIN contest_participants l ON l.id=lo.contest_participant_id LEFT JOIN contest_result_progressions g ON g.contest_result_id=r.id AND g.competition_format_id=${id} WHERE s.competition_format_id=${id}`;
   const outcomes=await tx<OutcomeRow[]>`SELECT o.id outcome_id,o.finalized_at,p.position,p.competition_entry_id,p.source_contest_result_id FROM competition_outcomes o JOIN competition_placements p ON p.competition_outcome_id=o.id WHERE o.competition_format_id=${id} ORDER BY p.position`;
   const planned=h.entrant_count===null?null:new SingleEliminationEngine().plan({formatKind:"single_elimination",entrantCount:h.entrant_count,scope:{competitionRef:h.competition_id,divisionRef:h.division_id}});
   const terminalPlanRef=planned?.ok?planned.value.contests.find(contest=>!planned.value.progressionRules.some(rule=>rule.source.type==="contest_outcome"&&rule.source.contestRef===contest.ref))?.ref:undefined;
   return{kind:"found" as const,snapshot:assemble(h,seeds,structures,participants,results,outcomes,terminalPlanRef)};
  });}catch(error){return{kind:"unavailable" as const,detail:error instanceof Error?error.message:"unknown"};}
 }
}

function assemble(h:Head,seeds:Seed[],rows:Structure[],participantRows:Participant[],resultRows:ResultRow[],outcomeRows:OutcomeRow[],terminalPlanRef?:string):TournamentOperationsSnapshot{
 const participantMap=new Map<string,TournamentParticipantView[]>();for(const p of participantRows){const value:TournamentParticipantView={contestParticipantId:p.id,position:p.position,competitionEntryId:p.competition_entry_id,sourceType:p.source_type,...p.source_type==="seed"?{sourceSeedNumber:p.source_seed_number!}:{sourceContestResultId:p.source_contest_result_id!,sourceOutcome:p.source_outcome!}};(participantMap.get(p.contest_id)??participantMap.set(p.contest_id,[]).get(p.contest_id)!).push(value);}
 const resultMap=new Map<string,ResultRow>(resultRows.map(r=>[r.contest_id,r]));const contestMap=new Map<string,TournamentContestView>();
 for(const r of rows){if(!r.contest_id)continue;const raw=resultMap.get(r.contest_id);let result:TournamentResultView|undefined;if(raw?.status==="finalized"&&raw.finalized_at&&raw.winner_entry_id&&raw.loser_entry_id)result={contestResultId:raw.id,status:"finalized",finalizedAt:iso(raw.finalized_at),winnerCompetitionEntryId:raw.winner_entry_id,loserCompetitionEntryId:raw.loser_entry_id,progressionConsumed:raw.participant_count!==null};const progressionState=r.contest_status==="cancelled"?"not_applicable":!result?"awaiting_result":raw!.participant_count===null?"awaiting_progression":raw!.participant_count>0?"progressed":r.plan_ref===terminalPlanRef?"terminal_progressed":"awaiting_progression";contestMap.set(r.contest_id,{contestId:r.contest_id,planRef:r.plan_ref!,stageId:r.stage_id,sequence:r.contest_sequence!,status:r.contest_status as TournamentContestView["status"],...(r.scheduled_at?{scheduledAt:iso(r.scheduled_at)}:{}),capacity:2,participants:participantMap.get(r.contest_id)??[],...(result?{result}:{}),progressionState});}
 const stages=[...new Map(rows.map(r=>[r.stage_id,r])).values()].map(r=>({stageId:r.stage_id,sequence:r.stage_sequence,status:r.stage_status as "pending"|"active"|"completed"|"cancelled",...(r.stage_division_id?{divisionId:r.stage_division_id}:{}),contests:rows.filter(x=>x.stage_id===r.stage_id&&x.contest_id).map(x=>contestMap.get(x.contest_id!)!)}));const contests=stages.flatMap(s=>s.contests);
 const outcome=outcomeRows[0]?{competitionOutcomeId:outcomeRows[0].outcome_id,finalizedAt:iso(outcomeRows[0].finalized_at),placements:outcomeRows.map(o=>({position:o.position,competitionEntryId:o.competition_entry_id,sourceContestResultId:o.source_contest_result_id}))}:undefined;
 return{competitionFormatId:h.format_id,competitionId:h.competition_id,eventId:h.event_id,organizationId:h.organization_id,...(h.division_id?{divisionId:h.division_id}:{}),sportId:h.sport_id,formatKind:h.kind as "single_elimination",competitionStatus:h.competition_status as TournamentOperationsSnapshot["competitionStatus"],formatStatus:h.format_status as TournamentOperationsSnapshot["formatStatus"],...(h.entrant_count!==null?{entrantCount:h.entrant_count}:{}),seeding:{...(h.entrant_count!==null?{frozenEntrantCount:h.entrant_count}:{}),finalized:h.seed_finalized_at!==null,...(h.seed_finalized_at?{finalizedAt:iso(h.seed_finalized_at)}:{}),assignedCount:seeds.length,assignments:seeds.map(s=>({seedNumber:s.seed_number,competitionEntryId:s.competition_entry_id}))},stages,contests,...(outcome?{outcome}:{})};
}
