import type { TeamRosterMembershipLookup, TeamRosterMembershipPersistenceError, TeamRosterMembershipRepository } from "@app/contracts/team-roster-membership-repository";
import type { Sql } from "@adapters/persistence/pg/connection";
import { isForeignKeyViolation,isUniqueViolation,neutralDetail,pgErrorInfo } from "@adapters/persistence/pg/errors";
import { isValidTeamRosterMembership } from "@domain/team/team-roster-membership";
import type { TeamRosterMembership } from "@domain/team/team-roster-membership.types";
import type { AggregateVersion } from "@domain/aggregate";
import type { Id,ISODateString,Result } from "@shared/kernel";
interface Row{id:string;team_id:string;athlete_profile_id:string;status:"active"|"inactive";joined_at:Date|string;left_at:Date|string|null;created_at:Date|string;updated_at:Date|string;version:number}
const SELECT="id,team_id,athlete_profile_id,status,joined_at,left_at,created_at,updated_at,version";
export class PgTeamRosterMembershipRepository implements TeamRosterMembershipRepository{
  constructor(private sql:Sql){}
  async create(m:TeamRosterMembership):Promise<Result<TeamRosterMembership,TeamRosterMembershipPersistenceError>>{try{await this.sql`INSERT INTO team_roster_memberships(id,team_id,athlete_profile_id,status,joined_at,left_at,created_at,updated_at,version) VALUES(${m.id},${m.teamId},${m.athleteProfileId},${m.status},${m.joinedAt},${m.leftAt},${m.createdAt},${m.updatedAt},${m.version})`;return {ok:true,value:m};}catch(e){const i=pgErrorInfo(e);if(isUniqueViolation(i))return bad(i?.constraint.includes("active_team_athlete")?"already_active":"duplicate_roster_membership_id");if(isForeignKeyViolation(i))return bad(i?.constraint.includes("team_id")?"team_not_found":"athlete_profile_not_found");return bad("unavailable",neutralDetail(e));}}
  async save(m:TeamRosterMembership,expectedVersion:number):Promise<Result<TeamRosterMembership,TeamRosterMembershipPersistenceError>>{try{const rows=await this.sql<Row[]>`UPDATE team_roster_memberships SET status=${m.status},left_at=${m.leftAt},updated_at=${m.updatedAt},version=${m.version} WHERE id=${m.id} AND version=${expectedVersion} AND ${m.version}=${expectedVersion}+1 RETURNING id,team_id,athlete_profile_id,status,joined_at,left_at,created_at,updated_at,version`;return rows[0]?{ok:true,value:map(rows[0])}:bad("concurrency_conflict");}catch(e){return bad("unavailable",neutralDetail(e));}}
  async findById(id:Id<"TeamRosterMembership">):Promise<TeamRosterMembershipLookup>{return this.find(this.sql.unsafe<Row[]>(`SELECT ${SELECT} FROM team_roster_memberships WHERE id=$1 LIMIT 1`,[id]));}
  async findActiveByTeamAndAthlete(t:Id<"Team">,a:Id<"AthleteProfile">):Promise<TeamRosterMembershipLookup>{return this.find(this.sql.unsafe<Row[]>(`SELECT ${SELECT} FROM team_roster_memberships WHERE team_id=$1 AND athlete_profile_id=$2 AND status='active' LIMIT 1`,[t,a]));}
  async listByTeam(t:Id<"Team">):Promise<readonly TeamRosterMembership[]>{try{const rows=await this.sql.unsafe<Row[]>(`SELECT ${SELECT} FROM team_roster_memberships WHERE team_id=$1 ORDER BY joined_at`,[t]);return rows.map(map).filter(isValidTeamRosterMembership);}catch{return [];}}
  private async find(q:Promise<Row[]>):Promise<TeamRosterMembershipLookup>{try{const row=(await q)[0];if(!row)return {kind:"not_found"};const membership=map(row);return isValidTeamRosterMembership(membership)?{kind:"found",membership}:{kind:"invalid_persistence_state"};}catch(e){return {kind:"unavailable",detail:neutralDetail(e)};}}
}
function iso(v:Date|string):ISODateString{return (v instanceof Date?v.toISOString():new Date(v).toISOString()) as ISODateString;}function map(r:Row):TeamRosterMembership{return {id:r.id as Id<"TeamRosterMembership">,teamId:r.team_id as Id<"Team">,athleteProfileId:r.athlete_profile_id as Id<"AthleteProfile">,status:r.status,joinedAt:iso(r.joined_at),leftAt:r.left_at===null?null:iso(r.left_at),createdAt:iso(r.created_at),updatedAt:iso(r.updated_at),version:r.version as AggregateVersion};}function bad(kind:TeamRosterMembershipPersistenceError["kind"],detail?:string):Result<never,TeamRosterMembershipPersistenceError>{return {ok:false,error:{kind,...(detail?{detail}:{})}};}
