import type {Clock,CompetitionEntryRepository,CompetitionFormatRepository,CompetitionRepository,CompetitionSeedAssignmentRepository,CompetitionStructureMaterializer,DivisionRepository,DomainEventPublisher,EventRepository,IdGenerator} from "@app/contracts";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import {createCompetitionSeedAssignment} from "@domain/competition/competition-seed-assignment";
import type {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import {validateCompetitionFormatPlan} from "@domain/competition/competition-format-plan-validation";
import type {Id,Result} from "@shared/kernel";
export type AssignCompetitionEntrySeedError={kind:"not_found"|"format_inactive"|"format_not_materialized"|"seeding_finalized"|"forbidden"|"competition_closed"|"invalid_scope"|"entry_inactive"|"entrant_set_changed"|"unsupported_format"|"invalid_format_plan"|"invalid_seed"|"seed_already_assigned"|"entry_already_assigned"|"persistence_unavailable";code:string;message:string};
const fail=(kind:AssignCompetitionEntrySeedError["kind"],message:string):Result<never,AssignCompetitionEntrySeedError>=>({ok:false,error:{kind,code:kind,message}});
type Deps={competitionFormatRepository:CompetitionFormatRepository;competitionRepository:CompetitionRepository;divisionRepository:DivisionRepository;eventRepository:EventRepository;competitionEntryRepository:CompetitionEntryRepository;assignmentRepository:CompetitionSeedAssignmentRepository;materializer:CompetitionStructureMaterializer;engines:CompetitionFormatEngineRegistry;authorization:AuthorizeOrganizationPermission;clock:Clock;idGenerator:IdGenerator;domainEvents:DomainEventPublisher};
export class AssignCompetitionEntrySeed{constructor(private readonly d:Deps){}async execute(i:{actingMembershipId:string;competitionFormatId:string;competitionEntryId:string;seedNumber:number}){
 const foundFormat=await this.d.competitionFormatRepository.findById(i.competitionFormatId as Id<"CompetitionFormat">);if(foundFormat.kind!=="found")return fail("not_found","CompetitionFormat does not exist.");const format=foundFormat.competitionFormat;if(format.status!=="active")return fail("format_inactive","CompetitionFormat must be active.");
 const state=await this.d.materializer.findState(format.id);if(!state.ok)return fail("persistence_unavailable","Materialization state could not be read.");if(!state.value)return fail("format_not_materialized","CompetitionFormat has not been materialized.");if(state.value.seedFinalizedAt)return fail("seeding_finalized","Seed assignments are finalized.");const frozen={value:state.value.entrantCount};
 const foundCompetition=await this.d.competitionRepository.findById(format.competitionId);if(foundCompetition.kind!=="found")return fail("not_found","Competition does not exist.");const competition=foundCompetition.competition;if(competition.status==="completed"||competition.status==="cancelled")return fail("competition_closed","Competition is closed.");const event=await this.d.eventRepository.findById(competition.eventId);if(event.kind!=="found")return fail("not_found","Owning Event does not exist.");const auth=await this.d.authorization.execute({organizationId:event.event.organizationId,membershipId:i.actingMembershipId,permission:"organization.events.manage"});if(!auth.ok||!auth.value.allowed)return fail("forbidden","Seed assignment is not permitted.");
 if(format.divisionId){const division=await this.d.divisionRepository.findById(format.divisionId);if(division.kind!=="found"||division.division.competitionId!==format.competitionId||division.division.status!=="active")return fail("invalid_scope","Format Division must be active and belong to the Competition.");}
 const foundEntry=await this.d.competitionEntryRepository.findById(i.competitionEntryId as Id<"CompetitionEntry">);if(foundEntry.kind!=="found")return fail("not_found","CompetitionEntry does not exist.");const entry=foundEntry.competitionEntry;if(entry.status!=="active")return fail("entry_inactive","CompetitionEntry must be active.");if(entry.competitionId!==format.competitionId||entry.divisionId!==format.divisionId)return fail("invalid_scope","CompetitionEntry must belong to the exact CompetitionFormat scope.");
 const count=format.divisionId?await this.d.competitionEntryRepository.countActiveForDivision(format.competitionId,format.divisionId):await this.d.competitionEntryRepository.countActiveForCompetition(format.competitionId);if(!count.ok)return fail("persistence_unavailable","Entrant count could not be derived.");if(count.value!==frozen.value)return fail("entrant_set_changed","The active entrant count differs from the materialized structure.");
 const resolved=this.d.engines.resolve(format.kind);if(!resolved.ok)return fail("unsupported_format",resolved.error.message);const planned=resolved.value.plan({formatKind:format.kind,entrantCount:frozen.value,scope:{competitionRef:format.competitionId,divisionRef:format.divisionId}});if(!planned.ok)return fail("invalid_format_plan",planned.error.message);const validation=validateCompetitionFormatPlan(planned.value);if(!validation.ok)return fail("invalid_format_plan",validation.error.message);const occurrences=planned.value.progressionRules.filter(r=>r.source.type==="seed"&&r.source.seedNumber===i.seedNumber).length;if(occurrences!==1)return fail("invalid_seed","Requested seed is not represented exactly once in the materialized format plan.");
 const seedExisting=await this.d.assignmentRepository.findByFormatAndSeed(format.id,i.seedNumber);if(seedExisting.kind==="found")return fail("seed_already_assigned","Seed is already assigned.");if(seedExisting.kind!=="not_found")return fail("persistence_unavailable","Seed assignment state could not be read.");const entryExisting=await this.d.assignmentRepository.findByFormatAndEntry(format.id,entry.id);if(entryExisting.kind==="found")return fail("entry_already_assigned","CompetitionEntry is already assigned.");if(entryExisting.kind!=="not_found")return fail("persistence_unavailable","Entry assignment state could not be read.");
 const now=this.d.clock.now();const made=createCompetitionSeedAssignment({id:this.d.idGenerator.next("CompetitionSeedAssignment"),competitionFormatId:format.id,competitionEntryId:entry.id,seedNumber:i.seedNumber,now});if(!made.ok)return fail("invalid_seed",made.error.message);const saved=await this.d.assignmentRepository.create(made.value);if(!saved.ok){if(saved.error.kind==="seeding_finalized")return fail("seeding_finalized","Seed assignments are finalized.");if(saved.error.kind==="seed_already_assigned"||saved.error.kind==="entry_already_assigned")return fail(saved.error.kind,saved.error.kind==="seed_already_assigned"?"Seed is already assigned.":"CompetitionEntry is already assigned.");return fail("persistence_unavailable","Assignment could not be persisted.");}const seedEvent={type:"competition.seed_assigned",eventId:this.d.idGenerator.next("DomainEvent"),occurredAt:now,aggregateId:saved.value.id,aggregateType:"CompetitionSeedAssignment",competitionFormatId:format.id,competitionEntryId:entry.id,seedNumber:i.seedNumber,timestamp:now};await this.d.domainEvents.publish(seedEvent);return{ok:true as const,value:saved.value};
}}
