import type { AppError, Clock, DomainEventPublisher, IdGenerator, OrganizationMembershipRepository, UseCase } from "@app/contracts";
import { deactivateOrganizationMembership, reactivateOrganizationMembership } from "@domain/organization/organization-membership";
import type { OrganizationMembership } from "@domain/organization/organization-membership.types";
import type { Id, Result } from "@shared/kernel";
export interface ChangeOrganizationMembershipStatusInput { membershipId:string; }
export interface ChangeOrganizationMembershipStatusError extends AppError {kind:"invalid_input"|"membership_not_found"|"invalid_transition"|"concurrency_conflict"|"persistence_unavailable"|"invalid_persistence_state";}
interface Deps{clock:Clock;idGenerator:IdGenerator;membershipRepository:OrganizationMembershipRepository;domainEvents:DomainEventPublisher;}
type Operation=typeof deactivateOrganizationMembership;
class ChangeStatus implements UseCase<ChangeOrganizationMembershipStatusInput,{membership:OrganizationMembership}>{constructor(private readonly deps:Deps,private readonly operation:Operation){}async execute(input:ChangeOrganizationMembershipStatusInput):Promise<Result<{membership:OrganizationMembership},ChangeOrganizationMembershipStatusError>>{const id=input.membershipId.trim() as Id<"OrganizationMembership">;if(!id)return fail("invalid_input","Membership identifier is required.");const found=await this.deps.membershipRepository.findById(id);if(found.kind==="not_found")return fail("membership_not_found","Membership does not exist.");if(found.kind!=="found")return fail(found.kind==="invalid_persistence_state"?"invalid_persistence_state":"persistence_unavailable","Membership lookup failed.");const expected=found.membership.version;const changed=this.operation(found.membership,{now:this.deps.clock.now(),eventId:this.deps.idGenerator.next("DomainEvent")});if(!changed.ok)return fail("invalid_transition",changed.error.message);const saved=await this.deps.membershipRepository.save(changed.value.membership,expected);if(!saved.ok){if(saved.error.kind==="not_found")return fail("membership_not_found","Membership no longer exists.");if(saved.error.kind==="concurrency_conflict")return fail("concurrency_conflict","Membership changed after it was loaded.");return fail(saved.error.kind==="invalid_persistence_state"?"invalid_persistence_state":"persistence_unavailable","Membership could not be saved.");}await this.deps.domainEvents.publish(changed.value.event);return {ok:true,value:{membership:saved.value}};}}
export class DeactivateOrganizationMembership extends ChangeStatus{constructor(deps:Deps){super(deps,deactivateOrganizationMembership);}}
export class ReactivateOrganizationMembership extends ChangeStatus{constructor(deps:Deps){super(deps,reactivateOrganizationMembership);}}
function fail(kind:ChangeOrganizationMembershipStatusError["kind"],message:string):Result<never,ChangeOrganizationMembershipStatusError>{return {ok:false,error:{kind,code:kind,message}};}
