import type { AppError, Clock, DomainEventPublisher, IdGenerator, OrganizationMembershipRepository, OrganizationRepository, PersonRepository, UseCase } from "@app/contracts";
import { createOrganizationMembership } from "@domain/organization/organization-membership";
import type { OrganizationMembership } from "@domain/organization/organization-membership.types";
import type { Id, Result } from "@shared/kernel";
export interface CreateOrganizationMembershipInput { organizationId:string; personId:string; }
export interface CreateOrganizationMembershipError extends AppError { kind:"invalid_input"|"person_not_found"|"organization_not_found"|"duplicate_membership"|"duplicate_membership_id"|"persistence_unavailable"|"invalid_persistence_state"; }
interface Deps {clock:Clock;idGenerator:IdGenerator;membershipRepository:OrganizationMembershipRepository;personRepository:PersonRepository;organizationRepository:OrganizationRepository;domainEvents:DomainEventPublisher;}
export class CreateOrganizationMembership implements UseCase<CreateOrganizationMembershipInput,{membership:OrganizationMembership}>{constructor(private readonly deps:Deps){} async execute(input:CreateOrganizationMembershipInput):Promise<Result<{membership:OrganizationMembership},CreateOrganizationMembershipError>>{const organizationId=input.organizationId.trim() as Id<"Organization">,personId=input.personId.trim() as Id<"Person">;if(!organizationId||!personId)return fail("invalid_input","Organization and Person identifiers are required.");const person=await this.deps.personRepository.findById(personId);if(person.kind==="not_found")return fail("person_not_found","Person does not exist.");if(person.kind!=="found")return fail(person.kind==="invalid_persistence_state"?"invalid_persistence_state":"persistence_unavailable","Person lookup failed.");const organization=await this.deps.organizationRepository.findById(organizationId);if(organization.kind==="not_found")return fail("organization_not_found","Organization does not exist.");if(organization.kind!=="found")return fail(organization.kind==="invalid_persistence_state"?"invalid_persistence_state":"persistence_unavailable","Organization lookup failed.");const existing=await this.deps.membershipRepository.findByOrganizationAndPerson(organizationId,personId);if(existing.kind==="found")return fail("duplicate_membership","This Person already has a membership in this Organization.");if(existing.kind!=="not_found")return fail(existing.kind==="invalid_persistence_state"?"invalid_persistence_state":"persistence_unavailable","Membership lookup failed.");const built=createOrganizationMembership({membershipId:this.deps.idGenerator.next("OrganizationMembership"),organizationId,personId,now:this.deps.clock.now(),eventId:this.deps.idGenerator.next("DomainEvent")});if(!built.ok)return fail("invalid_input",built.error.message);const saved=await this.deps.membershipRepository.create(built.value.membership);if(!saved.ok){const kind=saved.error.kind;return fail(kind==="duplicate_membership"||kind==="duplicate_membership_id"||kind==="invalid_persistence_state"?kind:"persistence_unavailable","Membership could not be created.");}await this.deps.domainEvents.publish(built.value.event);return {ok:true,value:{membership:saved.value}};}}
function fail(kind:CreateOrganizationMembershipError["kind"],message:string):Result<never,CreateOrganizationMembershipError>{return {ok:false,error:{kind,code:kind,message}};}
