import type { AppError, Clock, DomainEventPublisher, IdGenerator, OrganizationRepository, SportDirectory, TeamRepository, UseCase } from "@app/contracts";
import type { AuthorizeOrganizationPermission } from "@app/use-cases/authorize-organization-permission";
import { createTeam } from "@domain/team/team";
import type { Team } from "@domain/team/team.types";
import type { Id, Result } from "@shared/kernel";
export interface CreateTeamInput { actingMembershipId:string;organizationId:string;sportId:string;name:string;key:string; }
export interface CreateTeamError extends AppError { kind:"invalid_input"|"forbidden"|"organization_not_found"|"sport_not_found"|"duplicate_team_key"|"persistence_unavailable"; }
export class CreateTeam implements UseCase<CreateTeamInput,{team:Team}>{constructor(private d:{repository:TeamRepository;organizationRepository:OrganizationRepository;sportDirectory:SportDirectory;authorization:AuthorizeOrganizationPermission;clock:Clock;idGenerator:IdGenerator;domainEvents:DomainEventPublisher}){}async execute(i:CreateTeamInput):Promise<Result<{team:Team},CreateTeamError>>{const organizationId=i.organizationId.trim() as Id<"Organization">,sportId=i.sportId.trim() as Id<"Sport">,membershipId=i.actingMembershipId.trim();if(!organizationId||!sportId||!membershipId)return fail("invalid_input","Organization, Sport, and acting membership are required.");const org=await this.d.organizationRepository.findById(organizationId);if(org.kind==="not_found")return fail("organization_not_found","Organization does not exist.");if(org.kind!=="found")return fail("persistence_unavailable","Organization lookup failed.");const auth=await this.d.authorization.execute({organizationId,membershipId,permission:"organization.teams.manage"});if(!auth.ok)return fail("persistence_unavailable",auth.error.message);if(!auth.value.allowed)return fail("forbidden","Team management is not permitted.");if(!(await this.d.sportDirectory.exists(sportId)))return fail("sport_not_found","Sport does not exist.");const made=createTeam({teamId:this.d.idGenerator.next("Team"),organizationId,sportId,name:i.name,key:i.key,now:this.d.clock.now(),eventId:this.d.idGenerator.next("DomainEvent")});if(!made.ok)return fail("invalid_input",made.error.message);const persisted=await this.d.repository.create(made.value.team);if(!persisted.ok)return fail(persisted.error.kind==="duplicate_team_key"?"duplicate_team_key":"persistence_unavailable","Team could not be created.");await this.d.domainEvents.publish(made.value.event);return {ok:true,value:{team:persisted.value}};}}
function fail(kind:CreateTeamError["kind"],message:string):Result<never,CreateTeamError>{return {ok:false,error:{kind,code:kind,message}};}
