import type {Clock,CompetitionFormatRepository,CompetitionOutcomeFinalizer,CompetitionRepository,CompetitionStructureMaterializer,DivisionRepository,DomainEventPublisher,EventRepository,IdGenerator} from "@app/contracts";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import type {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import {validateCompetitionFormatPlan} from "@domain/competition/competition-format-plan-validation";
import type {DomainEvent} from "@domain/aggregate";
import type {Id,Result} from "@shared/kernel";
export type FinalizeCompetitionOutcomeError={kind:"not_found"|"forbidden"|"format_inactive"|"unsupported_outcome_format"|"format_not_materialized"|"seeding_not_finalized"|"participants_not_materialized"|"competition_cancelled"|"invalid_scoped_division"|"invalid_format_plan"|"invalid_terminal_structure"|"terminal_contest_not_found"|"terminal_result_not_finalized"|"terminal_result_not_progressed"|"invalid_terminal_progression"|"malformed_terminal_result"|"cross_format_authority"|"competition_outcome_already_finalized"|"persistence_unavailable";code:string;message:string};
const fail=(kind:FinalizeCompetitionOutcomeError["kind"],code:string=kind,message:string=code):Result<never,FinalizeCompetitionOutcomeError>=>({ok:false,error:{kind,code,message}});
type Deps={formatRepository:CompetitionFormatRepository;competitionRepository:CompetitionRepository;eventRepository:EventRepository;divisionRepository:DivisionRepository;structure:CompetitionStructureMaterializer;finalizer:CompetitionOutcomeFinalizer;engines:CompetitionFormatEngineRegistry;authorization:AuthorizeOrganizationPermission;clock:Clock;idGenerator:IdGenerator;domainEvents:DomainEventPublisher};
export class FinalizeCompetitionOutcome{constructor(private readonly d:Deps){}async execute(i:{actingMembershipId:string;competitionFormatId:string}){
 const ff=await this.d.formatRepository.findById(i.competitionFormatId as Id<"CompetitionFormat">);if(ff.kind!=="found")return fail(ff.kind==="not_found"?"not_found":"persistence_unavailable","competition_format_not_found");const format=ff.competitionFormat;
 const cf=await this.d.competitionRepository.findById(format.competitionId);if(cf.kind!=="found")return fail(cf.kind==="not_found"?"not_found":"persistence_unavailable","competition_not_found");const competition=cf.competition;
 const ef=await this.d.eventRepository.findById(competition.eventId);if(ef.kind!=="found")return fail(ef.kind==="not_found"?"not_found":"persistence_unavailable","event_not_found");
 const auth=await this.d.authorization.execute({organizationId:ef.event.organizationId,membershipId:i.actingMembershipId,permission:"organization.events.manage"});if(!auth.ok||!auth.value.allowed)return fail("forbidden");
 if(format.status!=="active")return fail("format_inactive");if(format.kind!=="single_elimination")return fail("unsupported_outcome_format");if(competition.status==="cancelled")return fail("competition_cancelled");
 if(format.divisionId){const df=await this.d.divisionRepository.findById(format.divisionId);if(df.kind!=="found"||df.division.competitionId!==competition.id||df.division.status!=="active")return fail("invalid_scoped_division");}
 const state=await this.d.structure.findState(format.id);if(!state.ok)return fail("persistence_unavailable");if(!state.value)return fail("format_not_materialized");if(!state.value.seedFinalizedAt)return fail("seeding_not_finalized");if(!state.value.participantsMaterializedAt)return fail("participants_not_materialized");
 const engine=this.d.engines.resolve(format.kind);if(!engine.ok)return fail("unsupported_outcome_format");const planned=engine.value.plan({formatKind:format.kind,entrantCount:state.value.entrantCount,scope:{competitionRef:competition.id,divisionRef:format.divisionId}});if(!planned.ok)return fail("invalid_format_plan",planned.error.code,planned.error.message);const valid=validateCompetitionFormatPlan(planned.value);if(!valid.ok)return fail("invalid_format_plan",valid.error.code,valid.error.message);
 const sources=new Set(planned.value.progressionRules.flatMap(r=>r.source.type==="contest_outcome"?[r.source.contestRef]:[]));const terminals=planned.value.contests.filter(c=>!sources.has(c.ref));if(terminals.length!==1)return fail("invalid_terminal_structure");
 const now=this.d.clock.now(),saved=await this.d.finalizer.finalize({competitionFormatId:format.id,competitionId:competition.id,terminalPlanRef:terminals[0]!.ref,expectedEntrantCount:state.value.entrantCount,outcomeId:this.d.idGenerator.next("CompetitionOutcome"),firstPlacementId:this.d.idGenerator.next("CompetitionPlacement"),secondPlacementId:this.d.idGenerator.next("CompetitionPlacement"),finalizedAt:now});if(!saved.ok){const k=saved.error.kind;return fail(k==="invalid_persistence_state"||k==="unavailable"?"persistence_unavailable":k);}
 const sourceContestResultId=saved.value.placements[0]!.sourceContestResultId,event:DomainEvent&Record<string,unknown>={type:"competition.outcome_finalized",eventId:this.d.idGenerator.next("DomainEvent"),occurredAt:saved.value.outcome.finalizedAt,aggregateId:saved.value.outcome.id,aggregateType:"CompetitionOutcome",competitionOutcomeId:saved.value.outcome.id,competitionFormatId:format.id,competitionId:competition.id,sourceContestResultId,placementCount:2,finalizedAt:saved.value.outcome.finalizedAt};await this.d.domainEvents.publish(event);return{ok:true as const,value:{outcome:saved.value.outcome,placements:saved.value.placements,competitionId:competition.id}};
}}
