import type {Clock,CompetitionEntryRepository,CompetitionFormatRepository,CompetitionRepository,CompetitionSeedAssignmentRepository,CompetitionSeedFinalizer,CompetitionStructureMaterializer,DivisionRepository,DomainEventPublisher,EventRepository,IdGenerator} from "@app/contracts";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import type {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import {validateCompetitionFormatPlan} from "@domain/competition/competition-format-plan-validation";
import type {Id,Result} from "@shared/kernel";
export type FinalizeCompetitionSeedAssignmentsError={kind:"not_found"|"format_inactive"|"format_not_materialized"|"already_finalized"|"forbidden"|"competition_closed"|"invalid_scope"|"unsupported_format"|"invalid_format_plan"|"seeding_incomplete"|"entrant_set_changed"|"persistence_unavailable";code:string;message:string};
const fail=(kind:FinalizeCompetitionSeedAssignmentsError["kind"],message:string):Result<never,FinalizeCompetitionSeedAssignmentsError>=>({ok:false,error:{kind,code:kind,message}});
const setEqual=(a:readonly unknown[],b:readonly unknown[])=>a.length===b.length&&new Set(a).size===a.length&&new Set(b).size===b.length&&a.every(x=>new Set(b).has(x));
type Deps={competitionFormatRepository:CompetitionFormatRepository;competitionRepository:CompetitionRepository;divisionRepository:DivisionRepository;eventRepository:EventRepository;competitionEntryRepository:CompetitionEntryRepository;assignmentRepository:CompetitionSeedAssignmentRepository;materializer:CompetitionStructureMaterializer;finalizer:CompetitionSeedFinalizer;engines:CompetitionFormatEngineRegistry;authorization:AuthorizeOrganizationPermission;clock:Clock;idGenerator:IdGenerator;domainEvents:DomainEventPublisher};
export class FinalizeCompetitionSeedAssignments{constructor(private readonly d:Deps){}async execute(i:{actingMembershipId:string;competitionFormatId:string}){
 const f=await this.d.competitionFormatRepository.findById(i.competitionFormatId as Id<"CompetitionFormat">);if(f.kind!=="found")return fail("not_found","CompetitionFormat does not exist.");const format=f.competitionFormat;if(format.status!=="active")return fail("format_inactive","CompetitionFormat must be active.");
 const c=await this.d.competitionRepository.findById(format.competitionId);if(c.kind!=="found")return fail("not_found","Competition does not exist.");const competition=c.competition;const e=await this.d.eventRepository.findById(competition.eventId);if(e.kind!=="found")return fail("not_found","Owning Event does not exist.");const auth=await this.d.authorization.execute({organizationId:e.event.organizationId,membershipId:i.actingMembershipId,permission:"organization.events.manage"});if(!auth.ok||!auth.value.allowed)return fail("forbidden","Seed finalization is not permitted.");if(competition.status==="completed"||competition.status==="cancelled")return fail("competition_closed","Competition is closed.");
 if(format.divisionId){const d=await this.d.divisionRepository.findById(format.divisionId);if(d.kind!=="found"||d.division.competitionId!==format.competitionId||d.division.status!=="active")return fail("invalid_scope","Format Division must be active and belong to the Competition.");}
 const state=await this.d.materializer.findState(format.id);if(!state.ok)return fail("persistence_unavailable","Materialization state could not be read.");if(!state.value)return fail("format_not_materialized","CompetitionFormat has not been materialized.");if(state.value.seedFinalizedAt)return fail("already_finalized","Seed assignments were already finalized.");
 const entries=format.divisionId?await this.d.competitionEntryRepository.listActiveForDivision(format.competitionId,format.divisionId):await this.d.competitionEntryRepository.listActiveForCompetition(format.competitionId);if(!entries.ok)return fail("persistence_unavailable","Active entries could not be read.");
 const resolved=this.d.engines.resolve(format.kind);if(!resolved.ok)return fail("unsupported_format",resolved.error.message);const planned=resolved.value.plan({formatKind:format.kind,entrantCount:state.value.entrantCount,scope:{competitionRef:format.competitionId,divisionRef:format.divisionId}});if(!planned.ok)return fail("invalid_format_plan",planned.error.message);const valid=validateCompetitionFormatPlan(planned.value);if(!valid.ok)return fail("invalid_format_plan",valid.error.message);const seeds=planned.value.progressionRules.flatMap(r=>r.source.type==="seed"?[r.source.seedNumber]:[]);
 const assigned=await this.d.assignmentRepository.listByFormat(format.id);if(!assigned.ok)return fail("persistence_unavailable","Seed assignments could not be read.");if(!setEqual(assigned.value.map(x=>x.seedNumber),seeds))return fail("seeding_incomplete","Assigned seeds do not exactly cover the plan SeedSources.");const activeIds=entries.value.map(x=>x.id);if(activeIds.length!==state.value.entrantCount||assigned.value.length!==state.value.entrantCount||!setEqual(assigned.value.map(x=>x.competitionEntryId),activeIds))return fail("entrant_set_changed","Assigned entries do not exactly match the current active scoped entries.");
 const now=this.d.clock.now();const finalized=await this.d.finalizer.finalize({competitionFormatId:format.id,expectedEntryIds:activeIds,expectedSeedNumbers:seeds,finalizedAt:now});if(!finalized.ok){if(finalized.error.kind==="already_finalized")return fail("already_finalized","Seed assignments were already finalized.");if(finalized.error.kind==="seeding_incomplete")return fail("seeding_incomplete","Seed assignments changed before finalization.");if(finalized.error.kind==="entrant_set_changed")return fail("entrant_set_changed","Assigned entries changed before finalization.");return fail("persistence_unavailable","Seed assignments could not be finalized.");}
 const event={type:"competition.seeding_finalized",eventId:this.d.idGenerator.next("DomainEvent"),occurredAt:now,aggregateId:format.id,aggregateType:"CompetitionFormat",competitionFormatId:format.id,competitionId:competition.id,...(format.divisionId?{divisionId:format.divisionId}:{}),entrantCount:state.value.entrantCount,seedCount:seeds.length,finalizedAt:now};await this.d.domainEvents.publish(event);return{ok:true as const,value:{competitionFormatId:format.id,competitionId:competition.id,divisionId:format.divisionId,entrantCount:state.value.entrantCount,seedCount:seeds.length,finalizedAt:now}};
}}
