import type {Clock,CompetitionEntryRepository,CompetitionFormatRepository,CompetitionRepository,CompetitionSeedAssignmentRepository,CompetitionStructureMaterializer,DivisionRepository,DomainEventPublisher,EventRepository,IdGenerator,InitialContestParticipantMaterializer} from "@app/contracts";
import type {AuthorizeOrganizationPermission} from "@app/use-cases/authorize-organization-permission";
import type {CompetitionFormatEngineRegistry} from "@domain/competition/competition-format-engine";
import {validateCompetitionFormatPlan} from "@domain/competition/competition-format-plan-validation";
import {createContestParticipant} from "@domain/competition/contest-participant";
import type {Id,Result} from "@shared/kernel";
export type MaterializeInitialContestParticipantsError={kind:"not_found"|"format_inactive"|"format_not_materialized"|"seeding_not_finalized"|"participants_already_materialized"|"forbidden"|"competition_closed"|"invalid_scope"|"unsupported_format"|"invalid_format_plan"|"invalid_finalized_seed_map"|"invalid_contest_mapping"|"invalid_contest_state"|"persistence_unavailable";code:string;message:string};
const fail=(kind:MaterializeInitialContestParticipantsError["kind"],message:string):Result<never,MaterializeInitialContestParticipantsError>=>({ok:false,error:{kind,code:kind,message}});
type Deps={competitionFormatRepository:CompetitionFormatRepository;competitionRepository:CompetitionRepository;divisionRepository:DivisionRepository;eventRepository:EventRepository;competitionEntryRepository:CompetitionEntryRepository;assignmentRepository:CompetitionSeedAssignmentRepository;structure:CompetitionStructureMaterializer;materializer:InitialContestParticipantMaterializer;engines:CompetitionFormatEngineRegistry;authorization:AuthorizeOrganizationPermission;clock:Clock;idGenerator:IdGenerator;domainEvents:DomainEventPublisher};
export class MaterializeInitialContestParticipants{constructor(private readonly d:Deps){}async execute(i:{actingMembershipId:string;competitionFormatId:string}){
 const found=await this.d.competitionFormatRepository.findById(i.competitionFormatId as Id<"CompetitionFormat">);if(found.kind!=="found")return fail("not_found","CompetitionFormat does not exist.");const format=found.competitionFormat;if(format.status!=="active")return fail("format_inactive","CompetitionFormat must be active.");const c=await this.d.competitionRepository.findById(format.competitionId);if(c.kind!=="found")return fail("not_found","Competition does not exist.");const competition=c.competition;if(competition.status==="completed"||competition.status==="cancelled")return fail("competition_closed","Competition is closed.");const e=await this.d.eventRepository.findById(competition.eventId);if(e.kind!=="found")return fail("not_found","Owning Event does not exist.");const auth=await this.d.authorization.execute({organizationId:e.event.organizationId,membershipId:i.actingMembershipId,permission:"organization.events.manage"});if(!auth.ok||!auth.value.allowed)return fail("forbidden","Initial participant materialization is not permitted.");if(format.divisionId){const division=await this.d.divisionRepository.findById(format.divisionId);if(division.kind!=="found"||division.division.competitionId!==format.competitionId||division.division.status!=="active")return fail("invalid_scope","Format Division must be active and belong to the Competition.");}
 const state=await this.d.structure.findState(format.id);if(!state.ok)return fail("persistence_unavailable","Materialization state could not be read.");if(!state.value)return fail("format_not_materialized","CompetitionFormat has not been materialized.");if(!state.value.seedFinalizedAt)return fail("seeding_not_finalized","Seed assignments have not been finalized.");if(state.value.participantsMaterializedAt)return fail("participants_already_materialized","Initial participants were already materialized.");const engine=this.d.engines.resolve(format.kind);if(!engine.ok)return fail("unsupported_format",engine.error.message);const planned=engine.value.plan({formatKind:format.kind,entrantCount:state.value.entrantCount,scope:{competitionRef:format.competitionId,divisionRef:format.divisionId}});if(!planned.ok)return fail("invalid_format_plan",planned.error.message);const valid=validateCompetitionFormatPlan(planned.value);if(!valid.ok)return fail("invalid_format_plan",valid.error.message);
 const assigned=await this.d.assignmentRepository.listByFormat(format.id);if(!assigned.ok)return fail("persistence_unavailable","Finalized assignments could not be read.");if(assigned.value.length!==state.value.entrantCount)return fail("invalid_finalized_seed_map","Finalized seed assignment count is invalid.");const bySeed=new Map(assigned.value.map(x=>[x.seedNumber,x]));if(bySeed.size!==assigned.value.length)return fail("invalid_finalized_seed_map","Finalized seed map is not unique.");for(const x of assigned.value){const entry=await this.d.competitionEntryRepository.findById(x.competitionEntryId);if(entry.kind!=="found"||entry.competitionEntry.competitionId!==format.competitionId)return fail("invalid_finalized_seed_map","A finalized assigned CompetitionEntry cannot be resolved.");}
 const now=this.d.clock.now();const placements=[];for(const rule of planned.value.progressionRules){if(rule.source.type!=="seed")continue;const assignment=bySeed.get(rule.source.seedNumber);if(!assignment)return fail("invalid_finalized_seed_map","A required finalized seed cannot be resolved.");const made=createContestParticipant({id:this.d.idGenerator.next("ContestParticipant"),contestId:rule.target.contestRef as Id<"Contest">,position:rule.target.position,competitionEntryId:assignment.competitionEntryId,sourceType:"seed",sourceSeedNumber:rule.source.seedNumber,now});if(!made.ok)return fail("invalid_format_plan",made.error.message);const{contestId:_,...participant}=made.value;placements.push({contestPlanRef:rule.target.contestRef,participant});}
 const persisted=await this.d.materializer.materialize({competitionFormatId:format.id,expectedEntrantCount:state.value.entrantCount,placements,materializedAt:now});if(!persisted.ok){const k=persisted.error.kind;return k==="seeding_not_finalized"?fail(k,"Seed assignments have not been finalized."):k==="participants_already_materialized"?fail(k,"Initial participants were already materialized."):k==="invalid_finalized_seed_map"?fail(k,"The finalized seed map changed or is invalid."):k==="invalid_contest_mapping"?fail(k,"Durable Contest logical-ref mapping is invalid."):k==="invalid_contest_state"?fail(k,"A target Contest has already begun or is closed."):fail("persistence_unavailable","Initial participants could not be persisted.");}const event={type:"competition.initial_participants_materialized",eventId:this.d.idGenerator.next("DomainEvent"),occurredAt:now,aggregateId:format.id,aggregateType:"CompetitionFormat",competitionFormatId:format.id,competitionId:competition.id,...(format.divisionId?{divisionId:format.divisionId}:{}),participantCount:persisted.value.length,timestamp:now};await this.d.domainEvents.publish(event);return{ok:true as const,value:{competitionFormatId:format.id,competitionId:competition.id,divisionId:format.divisionId,participantCount:persisted.value.length,materializedAt:now}};
}}
