import type { Clock,CompetitionEntryRepository,CompetitionFormatRepository,CompetitionRepository,CompetitionStructureMaterializer,DivisionRepository,DomainEventPublisher,EventRepository,IdGenerator } from "@app/contracts";
import type { AuthorizeOrganizationPermission } from "@app/use-cases/authorize-organization-permission";
import { createContest,createStage } from "@domain/competition/competition";
import type { CompetitionFormatEngineRegistry } from "@domain/competition/competition-format-engine";
import { validateCompetitionFormatPlan } from "@domain/competition/competition-format-plan-validation";
import type { Contest,Stage } from "@domain/competition/competition.types";
import type { Id,Result } from "@shared/kernel";
export type MaterializeCompetitionFormatPlanError={kind:"not_found"|"format_inactive"|"forbidden"|"competition_closed"|"invalid_scope"|"unsupported_format"|"invalid_planning_input"|"invalid_format_plan"|"already_materialized"|"persistence_unavailable";code:string;message:string};
const fail=(kind:MaterializeCompetitionFormatPlanError["kind"],message:string):Result<never,MaterializeCompetitionFormatPlanError>=>({ok:false,error:{kind,code:kind,message}});
type Deps={competitionFormatRepository:CompetitionFormatRepository;competitionRepository:CompetitionRepository;divisionRepository:DivisionRepository;eventRepository:EventRepository;competitionEntryRepository:CompetitionEntryRepository;materializer:CompetitionStructureMaterializer;engines:CompetitionFormatEngineRegistry;authorization:AuthorizeOrganizationPermission;clock:Clock;idGenerator:IdGenerator;domainEvents:DomainEventPublisher};
export class MaterializeCompetitionFormatPlan{constructor(private readonly d:Deps){}async execute(i:{actingMembershipId:string;competitionFormatId:string}){
 const f=await this.d.competitionFormatRepository.findById(i.competitionFormatId as Id<"CompetitionFormat">);if(f.kind!=="found")return fail("not_found","CompetitionFormat does not exist.");const format=f.competitionFormat;if(format.status!=="active")return fail("format_inactive","CompetitionFormat must be active.");
 const c=await this.d.competitionRepository.findById(format.competitionId);if(c.kind!=="found")return fail("not_found","Competition does not exist.");if(c.competition.status==="completed"||c.competition.status==="cancelled")return fail("competition_closed","Competition is closed.");const e=await this.d.eventRepository.findById(c.competition.eventId);if(e.kind!=="found")return fail("not_found","Owning Event does not exist.");const auth=await this.d.authorization.execute({organizationId:e.event.organizationId,membershipId:i.actingMembershipId,permission:"organization.events.manage"});if(!auth.ok||!auth.value.allowed)return fail("forbidden","Materialization is not permitted.");
 if(format.divisionId){const division=await this.d.divisionRepository.findById(format.divisionId);if(division.kind!=="found"||division.division.competitionId!==format.competitionId||division.division.status!=="active")return fail("invalid_scope","Format Division must be active and belong to the Competition.");}
 const claimed=await this.d.materializer.isMaterialized(format.id);if(!claimed.ok)return fail("persistence_unavailable","Materialization state could not be read.");if(claimed.value)return fail("already_materialized","CompetitionFormat was already materialized.");
 const count=format.divisionId?await this.d.competitionEntryRepository.countActiveForDivision(format.competitionId,format.divisionId):await this.d.competitionEntryRepository.countActiveForCompetition(format.competitionId);if(!count.ok)return fail("persistence_unavailable","Entrant count could not be derived.");const resolved=this.d.engines.resolve(format.kind);if(!resolved.ok)return fail("unsupported_format",resolved.error.message);const plan=resolved.value.plan({formatKind:format.kind,entrantCount:count.value,scope:{competitionRef:format.competitionId,divisionRef:format.divisionId}});if(!plan.ok)return fail("invalid_planning_input",plan.error.message);const valid=validateCompetitionFormatPlan(plan.value);if(!valid.ok)return fail("invalid_format_plan",valid.error.message);
 const now=this.d.clock.now(),stageIds=new Map<string,Id<"Stage">>(),stages:Stage[]=[],contests:Contest[]=[];for(const p of plan.value.stages){const id=this.d.idGenerator.next("Stage");stageIds.set(p.ref,id);const key=`format-${format.id.replace(/[^a-zA-Z0-9]+/g,"-").toLowerCase()}-${p.sequence}`;const made=createStage({id,competitionId:format.competitionId,divisionId:format.divisionId,competitionFormatId:format.id,name:String(p.metadata?.label??p.key.replace(/_/g," ")),key,sequence:p.sequence,now,domainEventId:this.d.idGenerator.next("DomainEvent")});if(!made.ok)return fail("invalid_format_plan",made.error.message);stages.push(made.value.value);}
 for(const p of plan.value.contests){const stageId=stageIds.get(p.stageRef);if(!stageId)return fail("invalid_format_plan","Contest Stage mapping is missing.");const made=createContest({id:this.d.idGenerator.next("Contest"),stageId,sequence:p.sequence,now,domainEventId:this.d.idGenerator.next("DomainEvent")});if(!made.ok)return fail("invalid_format_plan",made.error.message);contests.push(made.value.value);}
 const saved=await this.d.materializer.materialize({format,stages,contests,createdAt:now});if(!saved.ok)return saved.error.kind==="already_materialized"?fail("already_materialized","CompetitionFormat was already materialized."):fail("persistence_unavailable","Competition structure could not be persisted.");const event={type:"competition.format_materialized",eventId:this.d.idGenerator.next("DomainEvent"),occurredAt:now,aggregateId:format.id,aggregateType:"CompetitionFormat",competitionFormatId:format.id,competitionId:format.competitionId,divisionId:format.divisionId,stageCount:stages.length,contestCount:contests.length,timestamp:now};await this.d.domainEvents.publish(event);return{ok:true as const,value:{competitionFormatId:format.id,stageIds:stages.map(x=>x.id),contestIds:contests.map(x=>x.id),stageCount:stages.length,contestCount:contests.length}};
}}
