/* Sprint 8: sport-neutral competition structure. */
DO $$ DECLARE malformed_count integer; BEGIN
 SELECT count(*) INTO malformed_count FROM organization_roles WHERE role_kind='system' AND key='organization-admin' AND NOT (cardinality(permissions)=10 AND permissions @> ARRAY['organization.read','organization.update','organization.members.read','organization.members.manage','organization.roles.read','organization.roles.manage','organization.trust.read','organization.trust.manage','organization.teams.read','organization.teams.manage']::text[] AND permissions <@ ARRAY['organization.read','organization.update','organization.members.read','organization.members.manage','organization.roles.read','organization.roles.manage','organization.trust.read','organization.trust.manage','organization.teams.read','organization.teams.manage']::text[]);
 IF malformed_count>0 THEN RAISE EXCEPTION 'malformed organization-admin system role permission set'; END IF;
 UPDATE organization_roles SET permissions=ARRAY['organization.events.manage','organization.events.read','organization.members.manage','organization.members.read','organization.read','organization.roles.manage','organization.roles.read','organization.teams.manage','organization.teams.read','organization.trust.manage','organization.trust.read','organization.update']::text[],version=version+1,updated_at=clock_timestamp() WHERE role_kind='system' AND key='organization-admin';
END $$;
CREATE TABLE public.events(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES public.organizations(id),name text NOT NULL CHECK(char_length(btrim(name)) BETWEEN 1 AND 120),key text NOT NULL CHECK(key~'^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(key)<=64),status text NOT NULL CHECK(status IN('draft','active','completed','cancelled')),starts_at timestamptz NULL,ends_at timestamptz NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,version integer NOT NULL CHECK(version>0),CONSTRAINT events_organization_key_unique UNIQUE(organization_id,key),CONSTRAINT events_time_order CHECK(starts_at IS NULL OR ends_at IS NULL OR starts_at<=ends_at));
CREATE TABLE public.competitions(id text PRIMARY KEY,event_id text NOT NULL REFERENCES public.events(id),sport_id text NOT NULL REFERENCES public.sports(id),name text NOT NULL CHECK(char_length(btrim(name)) BETWEEN 1 AND 120),key text NOT NULL CHECK(key~'^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(key)<=64),status text NOT NULL CHECK(status IN('draft','active','completed','cancelled')),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,version integer NOT NULL CHECK(version>0),CONSTRAINT competitions_event_key_unique UNIQUE(event_id,key));
CREATE TABLE public.competition_divisions(id text PRIMARY KEY,competition_id text NOT NULL REFERENCES public.competitions(id),name text NOT NULL CHECK(char_length(btrim(name)) BETWEEN 1 AND 120),key text NOT NULL CHECK(key~'^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(key)<=64),status text NOT NULL CHECK(status IN('active','inactive')),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,version integer NOT NULL CHECK(version>0),CONSTRAINT divisions_competition_key_unique UNIQUE(competition_id,key),CONSTRAINT divisions_id_competition_unique UNIQUE(id,competition_id));
CREATE TABLE public.competition_stages(id text PRIMARY KEY,competition_id text NOT NULL REFERENCES public.competitions(id),division_id text NULL,name text NOT NULL CHECK(char_length(btrim(name)) BETWEEN 1 AND 120),key text NOT NULL CHECK(key~'^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(key)<=64),sequence integer NOT NULL CHECK(sequence>0),status text NOT NULL CHECK(status IN('pending','active','completed','cancelled')),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,version integer NOT NULL CHECK(version>0),CONSTRAINT stages_competition_key_unique UNIQUE(competition_id,key),CONSTRAINT stages_division_competition_fk FOREIGN KEY(division_id,competition_id) REFERENCES public.competition_divisions(id,competition_id));
CREATE TABLE public.contests(id text PRIMARY KEY,stage_id text NOT NULL REFERENCES public.competition_stages(id),sequence integer NOT NULL CHECK(sequence>0),status text NOT NULL CHECK(status IN('pending','scheduled','in_progress','completed','cancelled')),scheduled_at timestamptz NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,version integer NOT NULL CHECK(version>0),CONSTRAINT contests_stage_sequence_unique UNIQUE(stage_id,sequence));
CREATE INDEX events_organization_idx ON public.events(organization_id);CREATE INDEX competitions_event_idx ON public.competitions(event_id);CREATE INDEX divisions_competition_idx ON public.competition_divisions(competition_id);CREATE INDEX stages_competition_idx ON public.competition_stages(competition_id);CREATE INDEX contests_stage_idx ON public.contests(stage_id);
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;ALTER TABLE public.competition_divisions ENABLE ROW LEVEL SECURITY;ALTER TABLE public.competition_stages ENABLE ROW LEVEL SECURITY;ALTER TABLE public.contests ENABLE ROW LEVEL SECURITY;
